### ISSUE TITLE
Why does Hospitality remove minified things?

### ISSUE THREAD

**Issue by mibac138** [OrionFive/Hospitality#100]
[Hospitality removes minified things](https://github.com/OrionFive/Hospitality/blob/develop/Source/Source/Harmony/MinifiedThing_Patch.cs). Why is that?

**Comment by OrionFive** [comment]
It only removes minified things that have a def that is not minifiable. This is because there was a bug where minifying a guest bed would break people's save games. This code unbreaks them again.
I could restrict it to beds when I update it next time.
