### ISSUE TITLE
Unable to change guest permissions, or trade with other settlements

### ISSUE THREAD

**Issue by generalking007** [OrionFive/Hospitality#108]
I appear to have an issue wherein I cannot change any of the hospitality settings for guests, the menu is entirely blank, and I have no clue why. I tried moving the mod to near the top, and at the bottom, of my load order but that doesn't seem to have fixed it. I also cannot trade with other factions, when my caravan reaches them and i click trade i get "object reference not set to instance of an object" but I'm not sure if hospitality is causing it or not, though it seems to be the main mod giving me trouble. 
heres a link to my error log and some screenshots of my load order/ error log, and the issue in question.
[https://gist.github.com/7ec4c4658d536d0887c090257ce2a36d](url)
![screenshot 81](https://user-images.githubusercontent.com/33336160/32357731-01c2ab46-c005-11e7-83e5-a94573069cf4.png)
![screenshot 82](https://user-images.githubusercontent.com/33336160/32357726-016d996c-c005-11e7-9607-95f900029a64.png)
![screenshot 83](https://user-images.githubusercontent.com/33336160/32357727-0183a324-c005-11e7-87fe-d6def4b2102b.png)
![screenshot 84](https://user-images.githubusercontent.com/33336160/32357728-019408ea-c005-11e7-8780-00e95cf61dda.png)
![screenshot 85](https://user-images.githubusercontent.com/33336160/32357730-01abcf02-c005-11e7-90a4-410fe8501219.png)

apologies in advance if it turns out the problem here is "you didn't install things properly, you are dumb"

**Comment by OrionFive** [comment]
This may or may not be fixed in the B18 version. Let me know if it still occurs.
