### ISSUE TITLE
Unable to use v18 of the mod

### ISSUE THREAD

**Issue by fairwitness** [OrionFive/Hospitality#112]
I love this mod, it's definitely become a cornerstone mod for the way I play.
I'm new to the game updating, I started with v17 so I haven't had to update mods before.
I unsubscribed, then resubscribed to your mod, but it is still showing that it is for v17, and also when I try to load it it comes up with a host of errors. Please see attached screenshots. Please let me know if I need to change the order of anything.
Thanks!

![image](https://user-images.githubusercontent.com/33810275/32993364-cb7c3228-cd0b-11e7-8177-be2d5bc5c646.png)

**Comment by OrionFive** [comment]
That's pretty odd. There is only one screenshot, though...

**Comment by OrionFive** [comment]
Please reopen this when you can provide a full log (Ctrl-F12).
