### ISSUE TITLE
guest permissions menu still blank

### ISSUE THREAD

**Issue by generalking007** [OrionFive/Hospitality#113]
The issue i had in 17 is still occurring in 18, not sure if trade caravans work yet, but i get an error every time i open the guest permissions window, it is totally blank and i get "object reference not set to instance of an object" over and over in my error log. it works when trading caravans show up, and just shows "soandso is part of a trading caravan and not a guest" but when normal guests arrive it is blank. i am using less mods this time since most of mine haven't updated yet. here is my load order: 
![screenshot 104](https://user-images.githubusercontent.com/33336160/33102401-3b8fce30-cee2-11e7-98f9-66ca4ba70697.png)

![screenshot 105](https://user-images.githubusercontent.com/33336160/33102408-41dcc658-cee2-11e7-8f51-3acb1993368d.png)

![screenshot 108](https://user-images.githubusercontent.com/33336160/33111786-5c5b2c58-cf15-11e7-9a82-90b3a5e469a5.png)

**Comment by OrionFive** [comment]
Could it be that you're using a custom storyteller? Some are not implemented properly and will break Hospitality.

**Comment by generalking007** [comment]
that might account for it. the storyteller i am using is a chaos storyteller i think, from the imperial guard traitors faction mod. ill try using a normal one and see if that fixes it, thanks for the advice.
