### ISSUE TITLE
Visitors walking out of map immediately after spawning

### ISSUE THREAD

**Issue by 1-Rem** [OrionFive/Hospitality#125]
Very recently any groups of visitors that come to my colony have started immediately walking to the edges of the map and leaving. It isn't throwing any errors in the debug log and I can get the issue to repeat as many times as I want by spawning a visitorgroup from the debug menu, no matter the situation, they just leave the map straight after entering it. Using the inspector on them reveals that as soon as any of the pawns begin moving they have a job that (as far as I can tell) seems to be telling them to just leave instantly 

\"\<exitMapOnArrival>True\</exitMapOnArrival>\"

I don't think I have any mods that should be conflicting with Hospitality, and I haven't sold any prisoners to guests nor anything else I can think of would trigger this behaviour/break the mod. Changing the position of Hospitality in the load order appears to have no effect. Starting a fresh colony and forcing a spawn of a visitorgroup does however have them behave properly.

Here's the output_log:
https://gist.github.com/HugsLibRecordKeeper/2c434c401e7f55ec67b5b8cdc9ddd674
(**_NSFW_** because of the name of one of the mods (and the mod itself))

Given the results of trying a new colony it may just be the particular map hex/something in my current colony that's bugged, and not an overall issue with the mod in which case feel free to close this.

**Comment by OrionFive** [comment]
Thanks for reporting this. I'll see what I can do.

**Comment by OrionFive** [comment]
Do you get an in-game message that the visitors are leaving? If so, what does it say?
Is it particularly cold on your map?
What's the goodwill of the faction?

**Comment by OrionFive** [comment]
Reopen if it still occurs with 1.0.
