### ISSUE TITLE
Visitors will not eat and cannot be sent away.

### ISSUE THREAD

**Issue by Coda02** [OrionFive/Hospitality#127]
I've been having this bug for a while and just tried to play around it but it's getting pretty difficult. 

Sometimes the error starts spamming as soon as the map is generated and sometimes it doesn't start until I have my first visitors. Like I said in the title they won't leave when I try to send them away and they ignore food in their inventory and around the base until they break and start murdering each other. I don't think I've seen them leave fleeing after a series of fights and murders. 

Here is my output log, I hope it helps. Sorry for all the mods. 

https://gist.github.com/HugsLibRecordKeeper/85500f096529658af2163393b6c797f3

**Comment by OrionFive** [comment]
Oh, the visitors are just a symptom. You're getting more errors than you can shake a stick at.

You clearly are using conflicting mods. If you want to fix it, turn on developer mode and disable all your mods. Then enable a few, start a game and execute the visitor incident. 
If you don't get errors, turn on some more mods and try again. 
Keep doing this until you know which other mod(s) is/are causing the problem(s). 

Feel free to reopen this issue when you have found out and can give me more information.
