### ISSUE TITLE
Guests wandering outside of zone.

### ISSUE THREAD

**Issue by Killaim** [OrionFive/Hospitality#136]
My guests that arrive tend to walk around where i have not assigned them to be allowed to go.
![guestswandering](https://user-images.githubusercontent.com/35471569/34964947-c581caaa-fa50-11e7-851e-f10b93aafec8.png)

not errors popping up, its just something they do, so cant pinpoint "what" does it (modwise maybe)

**Comment by OrionFive** [comment]
That's pretty odd. Are you sure you've made your area settings default, so all guests are using them?
Otherwise some mod must be overriding where they can go, which seems quite unlikely.

**Comment by Killaim** [comment]
yeah its set to default (they all get chatted too also)

they have a shopping area to (which they use fine)
they just wander off slightly (not alot though)

**Comment by OrionFive** [comment]
Well, the thing is that they aren't actually prevented from going outside of their area. It's just that their targets (walk destination, objects to interact with, etc.) must lie within the zone. 
So if another mod would tamper with pathfinding, or add a joy activity that just lets them walk around randomly, or something like that, they might wander outside their zone.
