### ISSUE TITLE
Faction Discovery: Make compatible with [RF] Faction Control

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#143]
https://ludeon.com/forums/index.php?topic=25159.msg397934#msg397934

**Comment by OrionFive** [comment]
Mod doesn't exist anymore.

**Comment by thakyZ** [comment]
But [KV] Faction Control does exist.
https://github.com/KiameV/rimworld-factioncontrol

**Comment by OrionFive** [comment]
How odd. Couldn't find it on Steam. I'll search again... 🤔

**Comment by thakyZ** [comment]
Here's the link if you need it: https://steamcommunity.com/sharedfiles/filedetails/?id=1509102551

**Comment by OrionFive** [comment]
Sorry, should have mentioned that I found it. Unfortunately, it's not something I can solve. They'll have to do it.
Faction Discovery just calls the regular RimWorld function for getting a base location. Faction Control modifies that function, which causes things to break.
