### ISSUE TITLE
When hauling, the picked up item should be marked

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#148]
"I noticed a smaller bug that occured from time to time, combined with other mods that include hauling:

When someone hauls and picks up multiple stuff, close before he leaves your colony it might accure that he "leaves" your own stuff because he liked his stay."

**Comment by Mehni** [comment]
FYI this might've stemmed from an older issue with Pick Up and Haul. <https://github.com/Mehni/PickUpAndHaul/commits/master?after=f24afbf1657078655fd898388be0ca205c558c18+79>

Timeline (roughly) checks out.

**Comment by OrionFive** [comment]
Any idea what I can do about it? Is this issue fixed in Pick Up and Haul?

**Comment by Mehni** [comment]
It's fixed in Pick Up and Haul. You can close this issue.

> Any idea what I can do about it? Is this issue fixed in Pick Up and Haul?

**Comment by OrionFive** [comment]
Great, thanks for letting me know!
