### ISSUE TITLE
Crazy Animal (Manhunter) Event Guest Bug

### ISSUE THREAD

**Issue by Phantomiosus** [OrionFive/Hospitality#149]
Hi! First of all I am a big fan of this mod and i hope i can help with this bug report.

In my last session i had a guest walking in my homearea. Everything normal... Then there was the wild animal manhunter event and later two crazy animals attacked that one guest (it was the guest with the little yellow trade question marker icon). So what happened is that my guest lost that fight and falled down so i can rescue him (Luckily he did not died). (The guest also lost his complete inventory). I gave one of my colonists the priority order to rescue the guest. But before my colonist reached the guest to rescue him, the guest stood up because he already healed his wounds (he was only lightly wounded) and i was not able to rescue anymore. So okay, but here is the problem... After that the guest userinterface was not working anymore and I think the game treated him as no guest anymore. The yellow questionmark for trading was missing on him but the guest tab when i click on the charactar was still there, but the options in the guest tab where missing. I had only 2 default options, which normally prisoners have instead of the guest options.

Here is the link for the log files: https://git.io/vpYY1

**Comment by OrionFive** [comment]
Thanks for reporting this. 

I can't see any issues from the log. I assume it was caused by the specific circumstances. Those bugs are really hard to reproduce, so given that it didn't actually break your game I won't pursue this one.

Thanks anyway!
