### ISSUE TITLE
Bug: After loading a mod, colonists don't work and I can't command them

### ISSUE THREAD

**Issue by diaxover** [OrionFive/Hospitality#151]
When I turn on mod, I can't command colonists to do something (for example to build something - they don't do it and I can't click and choose to work). Also they don't work when they got "free time" and I can't choose their works as screenshot shows
![bez tytulu](https://user-images.githubusercontent.com/38959134/39595133-e98d532a-4f0e-11e8-8de0-9ee236414ab4.png)
. Please help, becouse I'd like to play with visitors and do something... Changing the place of mod doesn't changing the situation. :(

Version: 0.17.1546 (May 22 2017)

Mods: Core, HugsLib, Quantum Cooling, More vanilla turrets, Mending, Tilled soil, Rimatomics beta test

**Comment by OrionFive** [comment]
I'm sorry to say, but it's very unlikely an issue of this mod. Try reinstalling this mod. Try reinstalling RimWorld. Try not using test mods.
Also, post your error log.

**Comment by diaxover** [comment]
[output_log.txt](https://github.com/OrionFive/Hospitality/files/1974486/output_log.txt)
I'll try reinstalling RimWorld if you won't find anything in logs. I tried reinstalling mod, but it doesn't work anyway... (it these aren't what should I copy, tell me)
