### ISSUE TITLE
Negotiators in doors bug

### ISSUE THREAD

**Issue by pl-wiltschek** [OrionFive/Hospitality#154]
If a negotiator is standing in a doorway, then he can't speak to a guest. He can actually, but it won't make Charmed x3 message for example and it can get stuck in an infinite loop. He just speaks to him and nothing happens.

**Comment by OrionFive** [comment]
Haven't heard of this one in a while. Can't reproduce it either.

**Comment by OrionFive** [comment]
When a colony pawn tries to "improve relations with X's faction" and they are standing in a doorway with the guest pawn in a diagonal in any direction, there is a bug in which the "charming" will not work, and the colony pawn will continue to try to charm the guest forever until they become hungry or tired.

**Comment by OrionFive** [comment]
Still can't reproduce this.
