### ISSUE TITLE
Bug, Visitors stand around and slowly die

### ISSUE THREAD

**Issue by kcrash201** [OrionFive/Hospitality#155]
A large amount of visitors will come and stay the colony but will refuse to leave and stand around in a non standard spot and slowly starve/kill themselves
Here is the logs:
https://git.io/vhWRL

A constant error is "System.NullReferenceException: Object reference not set to an instance of an object at Verse.AI.Group.Lord.LordTick () [0x000001 in <filename unknown>:0"

I know it is most likley a conflicting mod or corruption so any insight on the issue would be greatly appreciated

**Comment by pl-wiltschek** [comment]
Sorry, I can't find any indication as to what causes the problem. And probably neither does the author of the conflicting mod.

Usually when this happens something went wrong when spawning the group. E.g. they have invalid items, bodyparts or races. 

I'm afraid the only way to narrow it down is to try with different combinations of mods and see if it happens again. Then check which mods are active when it happens and which ones aren't.

**Comment by OrionFive** [comment]
Reopen if still present in 1.0.
