### ISSUE TITLE
Guest group spawns endless 'Visitors from Federation of blahblah are leaving'

### ISSUE THREAD

**Issue by AdrienRion** [OrionFive/Hospitality#167]
I have a group of visitors at my base and when they decided to leave they suddenly started spawning the 'leaving' text. It never stops, and they never leave. I have 'try to entertain' checked on all of them, but otherwise all settings are default. 

I haven't had any problems up until now, and I've been using Hospitality with this save for a long while. No mods have been added recently.

Log: https://git.io/fAaII

The reporting of the bug starts around line 958, I think.

**Comment by OrionFive** [comment]
Thanks for the report. It looks like JecsTools has been changed recently and now collides with Hospitality. Could you send him the log as well? And maybe a link to this page...

**Comment by OrionFive** [comment]
I did it myself. Should be fixed now.
