### ISSUE TITLE
Conflict with Giddy Up

### ISSUE THREAD

**Issue by SkittyshSurkit** [OrionFive/Hospitality#168]
So, I was beginning to install some mods and came up with a complication with the Giddy Up Mod.

I had mods in order. the following in order. HugsLib> A Dog Said> Giddy Up: Core> Giddy Up: Rock & Roll> Giddy Up:Caravan> Giddy Up: Battle Mounts.
I have left a link to the scrips as evidence, these only appear on the menu screen in red text. 

https://gist.github.com/HugsLibRecordKeeper/685c1b9bf0d5c6a8adb5f42de8636ee4

**Comment by OrionFive** [comment]
Did you, by any chance, overwrite an old Hospitality folder with a new one?

**Comment by SkittyshSurkit** [comment]
All I've done till now was unsubscribe from every mod and delete every game file that I have saved before the update to start fresh.
I also install the mods via Steam Subscripion instead of the direct file download.

https://gist.github.com/HugsLibRecordKeeper/7043b3d9f69aaef738ac6b0ac5081f31

This is now without the saved files from the previous game update.

**Comment by OrionFive** [comment]
Hm. Strange. It shows all the symptoms of an old folder, overwritten with a new one.
Unsubscribing isn't even necessary. I always leave the mods alone, but only enable them when they've been updated to the right version (color code in mod list).

Your log still mentions data from previous versions that isn't included in the mod anymore, as if it's still loading old files. In your Steam folder under <steam>\steamapps\workshop\content\294100 are all the downloaded mods. If you close Steam, rename or delete that folder and start it up again, it should redownload all subscribed mods. Try that and see if it helps.

**Comment by SkittyshSurkit** [comment]
Alright, so apparently when I mass deleted the subscription lot may have left behind all that coding behind. So I deleted file and reinstalled and now seems to not have any errors anymore. Thanks for the help!

**Comment by OrionFive** [comment]
I'm glad you could solve it!
