### ISSUE TITLE
Having a guest bed and a normal bed in same room causing pawns to not eat and starve

### ISSUE THREAD

**Issue by kiprockz** [OrionFive/Hospitality#173]
Shortly after having elven guests arrive, all my pawns stopped eating on there own and all started to starve. I was also unable to interact with prisoners and unconscious pawns so they starved to death. I told the guests to leave and my pawns started eating again.

**Comment by OrionFive** [comment]
What makes you think it has to do with the beds?

Can you link your error log?

**Comment by kiprockz** [comment]
I’m not sure where to find the error log. I thought it had to do with beds, because I changed the guest bed back to a normal bed and then kicked out the guests and by pawns started eating again and I was able to interact with prisoners.

**Comment by OrionFive** [comment]
Okay, you have to wait until it happens again, then press CTRL-F12. You'll get a link that you can post here.
