### ISSUE TITLE
Nano Repair Tech Compatibility

### ISSUE THREAD

**Issue by cmdprompt** [OrionFive/Hospitality#177]
https://steamcommunity.com/sharedfiles/filedetails/?id=1447372624
https://github.com/cmdprompt/NanoRepairTech

The beds in Nano Tech inherit from `RimWorld.Building_Bed`, the UI gets updated with the `For Guests` button. But something is wrong. Hospitality isn't creating the `<defName>Guests` versions for all the beds like it does with other beds; and so it throws an exception when the button gets clicked.

Is this an issue with Hospitality? Or something I need to fix in the Nano Tech mod.

**Comment by OrionFive** [comment]
Hospitality is making defs for all beds that are humanlike:

`var bedDefs = DefDatabase<ThingDef>.AllDefsListForReading.Where(def => def.thingClass == typeof(Building_Bed) && def.building.bed_humanlike).ToArray();`

The only other cause I could imagine is mod load order.

**Comment by cmdprompt** [comment]
Type bed = typeof(RimWorld.Building_Bed);
    var bedDefs = DefDatabase<ThingDef>.AllDefsListForReading
        .Where(def => bed.IsAssignableFrom(def.thingClass) && def.building.bed_humanlike)
        .ToArray();

I think the `def.thingClass == typeof(Building_Bed)` won't look at classes that inherit from `Building_Bed`. The `IsAssignableFrom` method seemed to work for adding the nano beds to the list. Is this a fix?

**Comment by OrionFive** [comment]
Good idea. I've updated the mod. See if this solves the issue.
