### ISSUE TITLE
No guest beds

### ISSUE THREAD

**Issue by ghost** [OrionFive/Hospitality#183]
Hey, sadly i can´t make guest beds. 
I tried to unsub, resub, restart Steam, verify Files, load with many other Mods or only load Core, Hugslib and Hospitality. Tried it on old savegames and new ones. Nothing worked :/
I´m clueless what else to test.

Here are my logs (core, hugslib and hospitality) on a new game. 
"https://git.io/fxrqZ"

I hope this helps.

Btw. whenever i disable hospitality and the game reloads (only core and hugslib), i get a bunch of errors.
Just in case you could use those logs as well. 
"https://git.io/fxrma"
Reloading the game fixes them.

If there is anything else i can do, tell me.

**Comment by OrionFive** [comment]
Hm. Unfortunately your log doesn't give any useful clues. Except that it looks like you're still running the first release after 1.0, which indeed has the guest bed bug. 

Errors when disabling mods are quite normal and expectable. So that doesn't say much.

What you can try is unsubscribe it for now, and download the Dropbox version. Maybe if you try the Steam version later it might just work.

**Comment by ghost** [comment]
Hey, thanks for your answer. Just tried it with the "Hospitality 1.0" Version from Dropbox and it looks like nothing changed. As far as i can tell the mod loaded correctly. There were no errors, but still no option to place a guest bed.

Logs: https://git.io/fxobw

I unsubscribed, downloaded the mod and placed the unzipped files in the Rimworld\Mods folder. In case i did something wrong.

**Comment by OrionFive** [comment]
This should definitely work. Out of curiosity - how are you creating guest beds?
You know you have to select a normal bed and click the "For guests" button, right?

**Comment by ghost** [comment]
Oh man.... I watched a video of an Alpha 16 run and saw your mod in there. There used to be an extra option for guest beds under "furniture" (next to flood light). I thought it´d still work this way and therefore didn´t check the options on a bed itself...

I am so sorry... Obviously my fault.

Thank you verry much for your help - I´m really sorry :/

**Comment by OrionFive** [comment]
Ah yeah, A16 is a long time ago already :D
