### ISSUE TITLE
Translation: false Def-injected translations missings

### ISSUE THREAD

**Issue by rw-chaos** [OrionFive/Hospitality#191]
Attached the report. The most injecteds are already translated and don't need another translation. 
Furthermore should the update list be really translated? 

========== Def-injected translations missing (18) ==========
ThingDef: SleepingSpotGuest.label 'Gast Schlafplatz'
ThingDef: SleepingSpotGuest.description 'Kennzeichnet eine Stelle auf dem Boden, auf der Leute schlafen sollen. Nicht bequem.'
ThingDef: DoubleSleepingSpotGuest.label 'Gast GroÃŸer Schlafplatz'
ThingDef: DoubleSleepingSpotGuest.description 'Kennzeichnet eine Stelle auf dem Boden, auf der zwei Leute beieinander schlafen sollen. Nicht bequem.'
ThingDef: BedGuest.label 'Gast Bett'
ThingDef: BedGuest.description 'Eine gemÃ¼tliche Matratze mit BettwÃ¤sche auf einem Rahmen. Ein guter Ort zum Ausruhen.'
ThingDef: DoubleBedGuest.label 'Gast Doppelbett'
ThingDef: DoubleBedGuest.description 'Ein einfaches Doppelbett mit genug Platz fÃ¼r Zwei.'
ThingDef: RoyalBedGuest.label 'Gast KÃ¶nigliches Bett'
ThingDef: RoyalBedGuest.description 'Ein luxuriÃ¶ses, mit Gold verziertes Bett, das gerade ausreichend fÃ¼r die Person von Adel ist. Sehr schÃ¶n und bequem, schon fast ein eigenes Kunstwerk. Mit ausreichend Platz fÃ¼r zwei.'
ThingDef: HospitalBedGuest.label 'Gast Krankenbett'
ThingDef: HospitalBedGuest.description 'Ein Bett, das speziell fÃ¼r die KrankenhÃ¤user entworfen wurde. Anpassbar an den Patienten und mit eingebauten GerÃ¤tschaften. Es verbessert das Ergebnis von medizinische Behandlungen sowie Operationen gegenÃ¼ber normalen Betten.'
ThingDef: BedrollGuest.label 'Gast Schlafsack'
ThingDef: BedrollGuest.description 'Ein einfaches Bett, in dem man auf dem Boden schlafen kann. Es wird normalerweise aus Stoff oder Leder hergestellt und besitzt oft auch ein Innenfell. Der Schlafsack ist leicht und kann zum Transport zusammengerollt werden. Er ist aber nicht so bequem wie ein richtiges Bett. Karawanen kÃ¶nnen SchlafsÃ¤cke zur besseren Erholung verwenden.'
ThingDef: BedrollDoubleGuest.label 'Gast GroÃŸer Schlafsack'
ThingDef: BedrollDoubleGuest.description 'Ein einfaches, extra breites Bett, in dem man auf dem Boden schlafen kann. Es wird normalerweise aus Stoff oder Leder hergestellt und besitzt oft auch ein Innenfell. Der Schlafsack ist leicht und kann zum Transport zusammengerollt werden. Er ist aber nicht so bequem wie ein richtiges Bett. Karawanen kÃ¶nnen SchlafsÃ¤cke zur besseren Erholung verwenden.'
UpdateFeatureDef: Hospitality_0_19_0.content '- Updated to "0.19"|- Guests will now equip what they buy|- There is now a hefty penalty when noone from a group returns|- Various bug fixes|Wanna do me a personal favor? Then please click the link above for more information.'
UpdateFeatureDef: Hospitality_0_19_2.content '- You can now invite guests via the Comms Console. Try it, it's free!|Wanna do me a personal favor? Then please click the link above for more information.'

**Comment by OrionFive** [comment]
Thanks for the updated translations!

I don't understand the request here, though. Is there something I need to do?
I'm pushing a new UpdateFeatureDef today - I forgot the 1.0 message :/

**Comment by rw-chaos** [comment]
You're welcome, thank you for the greate mod!

Year I'm not sure whats going on here. I didn't look in the code, but from outside it looks like that the translation function is been called twice? The original translation with just "Gast" at the start is been used, so maybe after this merge comes the problem?

**Comment by OrionFive** [comment]
Hm. I see that except for the update message, all defs above are generated by code. So obviously there won't be a localisation file for them.
Does it work correctly in-game?

**Comment by rw-chaos** [comment]
But when it is generated: why is it trying to translate them, when they are already translated? 

Yes so far it's working fine. It's just this warnings in the log. But I will send you now a small fix in the translation.

**Comment by OrionFive** [comment]
Hm... Beats me. Probably it always tries, when new definitions are added.
