### ISSUE TITLE
Not sure if it's a hospitality issue

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [OrionFive/Hospitality#192]
But check out this log, bruv!

https://hastebin.com/ujanihoxip.txt
https://hastebin.com/xacugodidu.txt

Reaching the max message log limit in coupla seconds.

**Comment by OrionFive** [comment]
Looks fancy, although I think it's a psychology issue / conflict. I'll investigate when I have more time again.
Any idea how I can reproduce it?

**Comment by rw-chaos** [comment]
I have also psychology  installed and it's so far working fine together.

**Comment by OrionFive** [comment]
Sorry. I can't reproduce this. And how do you know psychology is working fine? You're getting hundreds of errors...

**Comment by OrionFive** [comment]
This is fixed now. It's caused by androids or similar pawns, which I obviously didn't test with.
