### ISSUE TITLE
"Standing" bug

### ISSUE THREAD

**Issue by gruntw0rk** [OrionFive/Hospitality#198]
I posted this on steam forums and ludeon. Someone who reads the logs better than I can told me it may be a hospitality conflict of some sort. I'd appreciate it if you could help me figure out the issue.

Some of my pawns are stuck standing around doing none of their jobs but still fulfilling essential tasks like firefighting, eating, and sleeping. I only noticed the issue recently after I installed the rubber bullets mod but I don't think that actually caused it. The error is still happening when I remove that mod. I've removed a few mods trying to narrow down the issue and been unsuccessful. The one line I saw in the log file was something about a party, so I went into dev mode and tried to start a party that way but it threw some errors. I'm not sure if it's hospitality, since it mentions a guest, or if it's some other mod and I'm not even sure that the party error is the cause of the standing bug. I read someone say something about drafting and undrafting to see what error is thrown but when I do that no error appears to help narrow it down. It does seem to be mostly affecting my pawns assigned to planting, not sure if that is relevant.

https://gist.github.com/HugsLibRecordKeeper/0f1385f6012dfee791744287f9c8def7/revisions

**Comment by gruntw0rk** [comment]
After further investigation it seems that my planting pawns are unable to sow automatically for some reason. They have a sowing job and just stop and stand instead.

**Comment by OrionFive** [comment]
Yeah people always see "Guest" and think Hospitality. So I get dozens of these reports every week.
The only player in this error is the Androids mod. I can't tell if it causes the issue, but errors often do. 

Do note that there is only one kind of mod that can be disabled without breaking the save game. Those are the tweak kind of mods that are not adding new content to the game. And then also not all of them. Colony Manager, for example might also cause problems when disabled mid-game.
