### ISSUE TITLE
Clamp maximum travel time

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#199]
Maybe to a month or so

**Comment by Ne0nJelly** [comment]
I really like this idea. With WalkingStudios' Trading Economy mod at least one group has a visit travel time of 2+ years

**Comment by OrionFive** [comment]
What is the link to Trading Economy?

**Comment by Ne0nJelly** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1130945311

http://walkingproblem.com/2018/10/28/1-0-trading-economy-3-0/

**Comment by OrionFive** [comment]
Sorry, I should have phrased it differently. I meant, why do you think it's related to Trading Economy?

**Comment by Ne0nJelly** [comment]
I'm rather using it as an example of a rather large travel time that would benefit from a maximum two month visitor travel time. Two factions added have bases that are a while away, with that over a year travel time. Requesting a visit from two resulted in travel times of over one and two years respectively. I believe you're talking about implementing a maximum possible travel time, right?

**Comment by OrionFive** [comment]
Yes, indeed. But I'm wondering if this might actually be a bug. Possibly the route isn't calculated from the closest base. Or it uses worst case scenario numbers, something like that.

**Comment by Ne0nJelly** [comment]
As far as I can tell from the base's distance, it may just be a matter of the closest base being simply that far away by calculations, so I don't believe it's a bug. Probably just unfavourable RNG.

**Comment by OrionFive** [comment]
The latest version now uses pathfinding to calculate the distance, which should be more accurate and hopefully fixes the issue.
