### ISSUE TITLE
Wildlife Tab won't work after latest update

### ISSUE THREAD

**Issue by Witwenmacher** [OrionFive/Hospitality#208]
Playing a tribal set-up with lots of mods. Everything worked fine until the update today. For some reason if I click on the wildlife tab, it won't open. 
Tried to deactivate Hospitality Mod, reloaded the save, everything worked fine. Reactiviated the Mod and again the Wildlife tab is useless. 

https://git.io/fhGgh

My Modlist should be available here:
https://steamcommunity.com/profiles/76561198001866021/myworkshopfiles/?appid=294100&browsefilter=mysubscriptions
Load sequence of Hospitality is "somewhat in the middle" but def after hugslib.

**Comment by theotherp** [comment]
Can confirm this. Same error at `Hospitality.GuestUtility+<GetPawnsFromBase>d__26.MoveNext ()`

**Comment by OrionFive** [comment]
Sorry, your subscriptions are private and the link leads to the local subscriptions.

**Comment by OrionFive** [comment]
Can you link the wildlife mod?

**Comment by theotherp** [comment]
In my case it's [Numbers](https://steamcommunity.com/sharedfiles/filedetails/?id=1414302321). Sorry, should've specified. I don't have a Wildlife mod installed. But I do have a Wildlife tab... Is it included in vanilla now?

[Pastebin with log](https://pastebin.com/PAXCsvz8)

Thanks for the prompt response.

**Comment by OrionFive** [comment]
Should be fixed now.

**Comment by theotherp** [comment]
Thank you!
