### ISSUE TITLE
Numbers compatibility

### ISSUE THREAD

**Issue by Mehni** [OrionFive/Hospitality#209]
https://github.com/OrionFive/Hospitality/blob/f1029b3353dfbb882d0a4a05c8b74b0bc82cef85/Source/Source/GuestUtility.cs#L123

Hey Orion :)

Looks like the above is what's currently breaking the Numbers and Wildlife Tab (Numbers hijacks the Wildlife tab, so that's why that one breaks too). 

Some background: Numbers creates a temporary pawn on a null map in its constructor and then populates the stat list with the stats from that pawn. I fully admit it's technical debt and not a best practice, but it's what I currently got.

**Comment by OrionFive** [comment]
Thanks for the info! I think it's fixed now.

**Comment by Mehni** [comment]
Thanks :)
