### ISSUE TITLE
Unable to do Recreation - Conflict with Jurrasic Rimworld 1.0

### ISSUE THREAD

**Issue by EnazTheMighty123** [OrionFive/Hospitality#214]
The error in the log i got was this:

Exception in Verse.AI.ThinkNode_PrioritySorter GetPriority: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.Pawn_DrugPolicyTracker.ShouldTryToTakeScheduledNow (Verse.ThingDef ingestible) [0x00000] in <filename unknown>:0 
  at RimWorld.JobGiver_TakeDrugsForDrugPolicy.GetPriority (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, JobIssueParams jobParams) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by OrionFive** [comment]
Thanks for reporting this. Usually, when something like this happens, the conflicting mod is not configured correctly and has missing values or the like. Or it does something very strange that can't be anticipated.

In either case it's not something I can solve. You should probably report it to the conflicting mod.

Let me know if there's anything I can do to facilitate compatibility.
