### ISSUE TITLE
No visitors listed in guest tab; it is empty.

### ISSUE THREAD

**Issue by bndki** [OrionFive/Hospitality#218]
As stated in the title, there is no visitors in the guest tab.
I've installed HugsLib above and Hospitality on the very botton of my list of mods.

This is a screenshot of it: https://i.imgur.com/1bYQzrh.jpg
And here is the log: https://git.io/fhHy0

I do believe it is an incompatibility issue with one of my installed mods..
The problem is that I have no idea which is the one that is causing this issue.
If it will be of little help, here is a list of mods I have currently installed (alphabetic order):

Advanced Biomes By: Hey my team rules!
Cheaper Components By: PinoChemicali
Chickens Efficient Light By: chicken305
Color Coded Mood Bar By: semTex.
Dubs Bad Hygiene By: Dubwise
Dubs Mint Menus By: Dubwise
Giddy-up! Battle Mounts By: roolo
Giddy-up! Caravan By: roolo
Giddy-up! Core By: roolo
Heat Map By: falconne
Hospitality By: Orion
HugsLib By: UnlimitedHugs
Interaction Bubbles By: Jaxe
Mod Manager By: Fluffy
Moody By: Giant Space Hamster
More Faction Interaction By: Mehni
More Furniture [1.0] By: Anonemous2
Multiplayer [1.0] By: Zetrith
Pick Up And Haul By: Mehni
Research Tree By: Fluffy
Rimworld Search Agency By: Killface
Roads of the Rim By: loconeko73
RunAndGun By: roolo
Sparkling Worlds - Full Mod By: Albion
Wall Light By: Murmur
While You're Up [1.0] By: kevlou
ZiTools Objects seeker (1.9.1) By: Zaazik (Only mid)
[FSF] Complex Jobs By: FrozenSnowFox
[KV] Trading Spot - 1.0 By: Kiame Vivacity
[RF] Fertile Fields [1.0] By: Rainbeau Flambe
[RF] Fishing [1.0] By: Rainbeau Flambe
[SYR] Set Up Camp By: Syrchalis

Thank you so much in advance!

**Comment by OrionFive** [comment]
That looks a lot like a caravan to me. Caravans are not guests, so they're not listed.
