### ISSUE TITLE
[Suggestion] Configurable BuyItem PriceFactor

### ISSUE THREAD

**Issue by Maeyanie** [OrionFive/Hospitality#220]
It seems like it would be a useful feature to have the PriceFactor for guests buying items configurable via the Mod Settings screen.

While the default 0.85 might be useful to prevent generating too much money, it's always kind of annoyed me that if I were to buy raw materials, make stuff, then sell it to guests, I generally end up turning a net loss. If it were configurable, it would let people decide the mark-(up|down) for themselves.

**Comment by OrionFive** [comment]
Good point. But then the guests have to be smarter about deciding when to buy, and I have to communicate to the player why things are not being bought. If done well, you can already turn quite a profit with the guests, especially on stuff you don't necessarily need, like fur or wood.

At this point, I'm not gonna do this because it means opening a can of worms.

**Comment by Maeyanie** [comment]
Well, I'm only suggesting having a way in the mod config menu to change the global multiplier, not per-item, so the buying logic wouldn't really have to change. It's just a slightly more user-friendly way of customizing it than having to download the source, change a number, and recompile it.

If I were to send you this as a PR, would you be interested in that? It would be done as a minimalistic change so as not to affect anything I don't know about, so might not be as neat and tidy as it could be.

**Comment by OrionFive** [comment]
Making it customizable is the easy part. But (as always) people will assume, and want, that if it can be changed, everything else should still work correctly no matter what numbers they fill in.
And that's not something I feel like fixing.

**Comment by Maeyanie** [comment]
Fair enough, I suppose. Thanks for explaining the logic behind that decision.

**Comment by OrionFive** [comment]
A compromise would be to expose the value in an xml file, so it can be configured more easily. If that's something you want to do, you have my blessing ;)

**Comment by Maeyanie** [comment]
I thought about the best way to do that, and I concluded that putting it in one of the regular .xml files wouldn't actually make it much easier, since it would still have to be re-done every time Hospitality updates. Especially for Steam Workshop users, who would have to hunt down the file in two-deep numbered directories.

The solution I went with was to add support for a Hospitality.cfg file in RimWorld's config directory. It's not created automatically, so you can change the default numbers without any trouble from regular users, and silently ignored if it doesn't exist. It's set up to be straightforward if you want to add any other "hidden" configuration options there too.
I went with plain text (Key=Value) instead of XML since it's intended to be created by hand, but that would be easy to change.

PR in #221

**Comment by OrionFive** [comment]
Sounds like a good solution.
