### ISSUE TITLE
Multiplayer Compatibility Update

### ISSUE THREAD

**Issue by tindolt-zz** [OrionFive/Hospitality#223]
Hi :) , 
May we please have an update for compatibility with zetriths multiplayer mod, I am sure that would please a lot of people.
Thanks bye!

**Comment by OrionFive** [comment]
I'm sure it would - me excluded, since it's a ton of work. But as you can see the mod is open source, so you can just fix it yourself.

**Comment by tindolt-zz** [comment]
Ok if I do get some campatibility fix made would you merge it into the main mod? Or would I have to make it a patch?

**Comment by OrionFive** [comment]
You're on GitHub right now. It's meant for merging changes.
But the fix has to be made in a way that the mod will still work without the Multiplayer mod.

**Comment by tindolt-zz** [comment]
Yes of course I will make sure not to break anything but I will just try to tweak it a bit or something to make it so desymcs don't happen or find what causes desymcs and handle it a different way maybe I'm not too sure I have done much modding for rimworld and my C# is pretty uh underwhelming.

**Comment by OrionFive** [comment]
Well, good luck. I'm not gonna touch multiplayer, it's nasty work. Maybe it's worth a shot petitioning [Charlotte](https://steamcommunity.com/sharedfiles/filedetails/?id=1629973374) for making a fix. She seems to have plenty of experience fixing mods for multiplayer.

**Comment by tindolt-zz** [comment]
K thanks
