### ISSUE TITLE
Error: the "source steam workshop mod" has been updated

### ISSUE THREAD

**Issue by 3DPrintedWaffles** [OrionFive/Hospitality#228]
Also appearing for three other mods, but I like this one the best so I thought I'd come for a visit.  Thank you for your hospitality.

I would think this would mean it would auto-update to the latest version, but maybe I'm interpreting it wrong.

**Comment by 3DPrintedWaffles** [comment]
Of course two minutes later I figure it out.  Thanks for hosting me.

**Comment by Asenar** [comment]
Hi, 

I was going to report this bug.

It seems [Fluffy's Mod Manager](https://github.com/fluffy-mods/ModManager) checks the version in github' main branch (`develop` in your repository). I supposed it's like this when you provide a download or source url.

If the last version is really 1.1.6, I think you juste have to tag it/build realease/publish it to steam.

**Comment by OrionFive** [comment]
That's correct. If I update the version number and upload to github, ModManager will tell everyone they're outdated, even though the update is not done yet.
Optimally I shouldn't increase the version number before it's done. But then I tend to forget, which is kinda even worse.

**Comment by Asenar** [comment]
Maybe you can increase it in `develop` if you set another branch as default branch (let's say `master` for example ^^).

You can set `master` branch and set it to the current tag (`git checkout -b master 1.1.5` then define it as default branch in github repository settings).

Then continue to work in `develop` as usual :)

And then, everytime you want to make a new release, you will add theses 3 commands : `git checkout master && git merge 1.1.6 && git checkout develop` (to make a new merge commit in master, then go back to your develop branch)

(sorry if you already knows that, but I prefer to give a max of details about how to in case of you didn't know, or if another developer has a similar problem)

**Comment by OrionFive** [comment]
I guess I could do that. I'll think about it. I'm not very keen on all the extra steps, though.
