### ISSUE TITLE
Wrong buy prices?

### ISSUE THREAD

**Issue by Maeyanie** [OrionFive/Hospitality#232]
This doesn't seem to be your bug, but not sure if you have any ideas on it... when my guests buy items, sometimes it seems to be for the wrong price.

For example, someone bought these for 12 silver (and 12 silver was correctly left on the ground):
![20190402045205_1](https://user-images.githubusercontent.com/206142/55390451-3db54c80-5505-11e9-918c-4351adf3488b.jpg)

But the actual market value is 28.9 silver:
![20190402045205_2](https://user-images.githubusercontent.com/206142/55390483-50c81c80-5505-11e9-9f52-933918bc188c.jpg)

I'm using a custom price factor of 1.0, so it should be either 28.9 silver (rounded down to 28), or 17.34 (17) if Item.MarketValue applies the 60% sell price multiplier... neither of which are 12.

I did add some debugging to a local copy, and it seems Item.MarketValue is the "wrong" number, Hospitality itself is doing everything right with the information it's given.
Sometimes it's lower, sometimes it's higher, I don't particularly see any pattern to it, and have no clue why it's different from what the GUI displays at all.

**Comment by OrionFive** [comment]
Hm... Sorry. I don't know where it goes wrong. It might be possible to fix it by looking at how the stat for the item is actually calculated.

**Comment by Maeyanie** [comment]
Alright... I've been poking through decompiled code trying to figure that one out, I'll keep looking and post back if I find anything.

**Comment by Maeyanie** [comment]
After watching this for a while, I'm starting to think it's not the price that's wrong, but that the item is changing as they buy it.
The purchase notification matches the item which appears in the guest's inventory, but while I haven't actually caught it on camera, some of the things they buy are items I'm reasonably sure I didn't have.

Edit:
That, or the notification message is for the wrong item. Going to keep watching and see for sure.

**Comment by Maeyanie** [comment]
Added some debugging info and caught an instance on camera. It looks like it's just the message is wrong.
The notification said:
![image](https://user-images.githubusercontent.com/206142/55459283-246fd700-55bd-11e9-9ed4-d5a61d9aaa03.png)
But some debugging code showed the actual item:
![image](https://user-images.githubusercontent.com/206142/55459302-36ea1080-55bd-11e9-8703-b913064ff22c.png)
Checking the visitor's inventory, both items are there, and it looks like the item he bought was equipped, and what he was wearing before ended up in the message:
![image](https://user-images.githubusercontent.com/206142/55459349-5bde8380-55bd-11e9-92bb-1f6b392e1f9b.png)

I'm guessing [toil.actor.inventory.innerContainer](https://github.com/OrionFive/Hospitality/blob/f2d3d1377fa864832ab25a417c0ec2a6dc28776d/Source/Source/JobDriver_BuyItem.cs#L124) isn't including equipped items, so the change-detection code sees the now-unequipped item instead of the bought one, and reports that.

The good news is, this is _much_ less strange than Item.MarketValue being wrong or items morphing on pickup.

Edit:
Testing a fix, will send you a PR for it if it works (and you don't fix it first... you know the code far better than me.)

Edit 2:
Nope, didn't work.

**Comment by OrionFive** [comment]
I've pushed a fix. Could you check it out and confirm that it works correctly now?

**Comment by Maeyanie** [comment]
Looks good... both items which get equipped and ones which don't both appear to report correctly.

**Comment by OrionFive** [comment]
Great! Then I'll roll it out with the next update. Thanks for your help.

**Comment by Maeyanie** [comment]
Thanks for the fix. :)
