### ISSUE TITLE
Visitors not entering map

### ISSUE THREAD

**Issue by benzory12** [OrionFive/Hospitality#233]
Something failed when spawning visitors: Spawned visitors without GuestComp.
  at Hospitality.IncidentWorker_VisitorGroup.CheckVisitorsValid (System.Collections.Generic.List`1 visitors) [0x00000] in <filename unknown>:0 
  at Hospitality.IncidentWorker_VisitorGroup.SpawnGroup (RimWorld.IncidentParms parms, Verse.Map map) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Hospitality.IncidentWorker_VisitorGroup:SpawnGroup(IncidentParms, Map)
Hospitality.<>c__DisplayClass9_0:<TryExecuteWorker>b__0()
Verse.DiaOption:Activate()
Verse.DiaOption:OptOnGUI(Rect, Boolean)
Verse.Dialog_NodeTree:DrawNode(Rect)
Verse.Dialog_NodeTree:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by benzory12** [comment]
https://gist.github.com/HugsLibRecordKeeper/82ec8ea6676c20782d3f9e6645620cff

**Comment by OrionFive** [comment]
Thanks for reporting this. The next update will improve the error message to provide more information. When you get it, please reopen this issue and post a new log.

The problem is most likely caused by spawning guests that are not humanlike. These are not supported.

**Comment by benzory12** [comment]
Will do, thank you.

**Comment by OrionFive** [comment]
Any chance you are using Giddy Up? It seems it tries to add animals to guests, but animals are not supported.

**Comment by benzory12** [comment]
I am indeed although strangely guests are now working after a simple mod re-subscribe! I will update if I encounter any other issues.
