### ISSUE TITLE
Something failed when spawning visitors

### ISSUE THREAD

**Issue by Krisocka** [OrionFive/Hospitality#238]
https://git.io/fjs85
Something failed when spawning visitors: Spawned visitors without GuestComp.
  at Hospitality.IncidentWorker_VisitorGroup.CheckVisitorsValid (System.Collections.Generic.List`1 visitors) [0x00000] in <filename unknown>:0 
  at Hospitality.IncidentWorker_VisitorGroup.SpawnGroup (RimWorld.IncidentParms parms, Verse.Map map) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Hospitality.IncidentWorker_VisitorGroup:SpawnGroup(IncidentParms, Map)
Hospitality.IncidentWorker_VisitorGroup:TryExecuteWorker(IncidentParms)
RimWorld.IncidentWorker:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire_Patch1(Object, FiringIncident)
RimWorld.IncidentQueue:IncidentQueueTick()
Hospitality.Hospitality_MapComponent:MapComponentTick()
Verse.MapComponentUtility:MapComponentTick(Map)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

I use Giddy Up, but have set the chance for friendly Pawns to have mounts to 0

**Comment by OrionFive** [comment]
Hm. Hard to tell. My guess is Animal Variations, since it is also sending errors.

Maybe I can make the error message more useful next version.

**Comment by Krisocka** [comment]
The Animal Variations is just for different coats for animals. Alpha Animals seems to have not done that correctly, but it shouldnt have to do anything with the Visitors.

**Comment by OrionFive** [comment]
I've improved the error message. Please update the mod and do another log after guests didn't spawn...

**Comment by Krisocka** [comment]
https://gist.github.com/HugsLibRecordKeeper/b2cdb4cfe3d9e636d2920d7dcddc452f

I spawned 3 groups with the debug menu, 2 spawned normal (1 tribal, 2 outlander)
The third didnt spawn

**Comment by OrionFive** [comment]
Well, for some reason it was trying to spawn a husky and muffalo with the 3rd group. Must be some mod doing this.
