### ISSUE TITLE
Guest not leaving

### ISSUE THREAD

**Issue by Slkamsteeg** [OrionFive/Hospitality#239]
https://git.io/fjs4N

A guest group would spam the message "Visitors are leaving" without actually leaving, I tried reloading/killing them but that did not solve the issue.

![Visitors not leaving](https://user-images.githubusercontent.com/44920608/56737663-30d5f280-676b-11e9-83c7-3161658e5307.PNG)

**Comment by Slkamsteeg** [comment]
note the multiplayer mod was enabled but this was not a hosted server

**Comment by OrionFive** [comment]
It's either the multiplayer mod (it overrides about 800 RimWorld functions, chance to break other mods is over 9000%) or, looking at the error message, some mod that contains a misconfigured piece of apparel.

I've made a fix that will allow the group to leave despite the error. It will be included with the next version.

**Comment by Slkamsteeg** [comment]
Thank you :)

**Comment by OrionFive** [comment]
I've uploaded the new version.

**Comment by Slkamsteeg** [comment]
Thanks, I found that soft warm beds was breaking the game

**Comment by OrionFive** [comment]
Soft Warm Beds is actually dependent on the version of Hospitality. This means it will break (your game) every time Hospitality is updated.

**Comment by OrionFive** [comment]
I don't think it caused your original problem, though. Because back then the versions still matched...

**Comment by Slkamsteeg** [comment]
Yeah right now softwarmbeds made every item in the game unclickable 

https://gist.github.com/HugsLibRecordKeeper/7fab7c8fb2b39a97aa057a0028da260b

should I open a new issue?

**Comment by OrionFive** [comment]
Just make sure you don't overwrite a savegame when a mod breaks your game.

You can open a new issue - but not here. There's nothing I can do about it.
