### ISSUE TITLE
"VisitorGroup" Debug Option Doesn't Use Point Values

### ISSUE THREAD

**Issue by brucethemoose** [OrionFive/Hospitality#242]
Spawning visitors using the "Do incident w/ points" debug option doesn't seem to use the point value specified. Even a 5000 point visitor incident always spawns a small group, or a moderately small group after ticking away a few years via debug mode and spawning in an absurd amount of colony wealth. 

Why does this matter? Well, I'm trying to track down a mod conflict (more specifically, find out which mod(s) spawn animals with visitor groups), but I can't seem to replicate the problem in debug mode. I can reliably trigger the error with about every 3rd visitor group in my old save (which I can't remove some mods from without breaking the save), but I can't trigger the error even once on a fresh debug map, even after spawning hundreds of visitor groups on several different worlds. I suspect the visitor groups aren't large enough to even consider spawning animals. 

Possibly related to this issue: https://github.com/OrionFive/Hospitality/issues/234

But I'm not convinced Giddy Up! is the culprit. I have all friendly/raid animal spawning disabled, removing the mod from the save doesn't mitigate the issue, and the Giddy Up! developer [claims](https://steamcommunity.com/sharedfiles/filedetails/?id=1216999901) "That error doesn't have anything to do with Giddy-up, since Giddy-up doesn't spawn animals for visitor groups created by Hospitality."

**Comment by OrionFive** [comment]
Hm.. Interesting endeavour. I'd be interested too.
The reason the point) point value is ignored is because Hospitality uses an independent formula for group sizes which is based on the time that has passed on the map.

**Comment by OrionFive** [comment]
This is not something I'm planning to change. Sorry that it makes error tracking harder.

I have, however, created a new debug option to spawn the largest possible group size (as configured in the mod options). It's not official yet so you have to download it here:
https://github.com/OrionFive/Hospitality/releases/tag/Experimental
