### ISSUE TITLE
no guests and can not invite guests

### ISSUE THREAD

**Issue by llamala** [OrionFive/Hospitality#248]
hello, I add some mods to my save. And there are now no new guests coming, when I tried to invite them, the outlanders said they are not interested. While I can still invite the tribes, the guests come as normal visitors (guest tab doesnt show them and they dont come in my colony,just pass away my map. Have not tested just a coincidence or I can still invite them but they come as visitors.)
I have attached my screenshot of the invite interface below.
![QQ截图20190516143109](https://user-images.githubusercontent.com/50715999/57878499-29dd5580-77e8-11e9-9259-799169bb9d88.png)
![QQ截图20190516143138](https://user-images.githubusercontent.com/50715999/57878500-29dd5580-77e8-11e9-95b0-7efd6ce398e1.png)
The mods I add are as follows
![image](https://user-images.githubusercontent.com/50715999/57878658-80e32a80-77e8-11e9-8dec-55bb6e70e493.png)
I wonder why the outlanders behave differently from the tribes. I see this mod is not compatible with closeddoor, but is it compatible with locks?
I do not have any issues before adding the new mods, so I guess my other old mods are fine and I do not have any mod you mentioned that will not work with the mod.
Thanks

**Comment by llamala** [comment]
I just found a group of guests from the tribe came, they showed up in the guest tab and I can try to recruit them etc. But they act as visitors, go straightly across my map, do not go in my colony. I watched them go straight from the bottom left corner to the upper right corner with the minimap mod.

**Comment by OrionFive** [comment]
Most likely the locks mod is not compatible. Also it looks like you are using mods that are for a different version of RimWorld.

When they are not interested this means they have visited recently. 

If you upload a full log (Ctrl-f12) I can maybe tell you more.
