### ISSUE TITLE
Enable tick Entertain automatically in Guests Tab

### ISSUE THREAD

**Issue by qaron84** [OrionFive/Hospitality#249]
i know it's not a really issue but a quality of life problem actually. As long as you have this mod enabled, you should get the option to "entertain" automatically enabled and you should tick the option "recruit" if you want manually. that way:
1. you can recruit the pawn you want and 
2. improve the relations with other factions at the same time... 
thank you for this great mod brother, keep up the good work!!

**Comment by OrionFive** [comment]
I hope you know that you can make the entertain option a default... by using the button "Make Default".
