### ISSUE TITLE
Free time can you help us support Multiplayer mod?

### ISSUE THREAD

**Issue by senioi** [OrionFive/Hospitality#251]
this is mod github page
https://github.com/Parexy/Multiplayer

**Comment by OrionFive** [comment]
Hey, sorry, but I don't have free time. I don't have time to learn how to support the multiplayer mod and I don't have time to then actually do it.

If you really want this, you will have to do it yourself. But I assume it will break as soon as I change anything about my mod. This is another reason I'm not going to do it. I don't have time to work on my mod and then also update a multiplayer patch.

Sorry.
