### ISSUE TITLE
Guests should be rescued automatically 

### ISSUE THREAD

**Issue by ghost** [OrionFive/Hospitality#254]
Guests will allow enemy pawns to freely shoot at them from a distance. They will also ignore allies being attacked, and ignore enemies in proximity unless they are attacked themselves (the default visitor behavior does this as well, but mobs the enemy when attacked.) Furthermore, downed guests do not receive any medical attention from neither their faction or the player’s pawns (unless the player rescues them themselves.)

Could it be possible to allow guests to bring downed pawns from their faction to guest beds, and then use their own medicine to treat the injured guests? Or perhaps add an option to let the player’s pawns treat downed guests as they would their own (automatic)?

**Comment by OrionFive** [comment]
Well, everything is possible, if you throw enough weeks or months of development time at it.
As it is right now, I can sometimes spare an hour. 
So the best I can do is try to make colonists rescue guests automatically.

**Comment by OrionFive** [comment]
Added in next version.
