### ISSUE TITLE
Guests buy & wear incompatible racial clothing

### ISSUE THREAD

**Issue by Psyradragon** [OrionFive/Hospitality#257]
Guests will buy clothing and immediately wear it, even if they are normally unable to wear them because of a racial incompatibility, such as avali wearing human clothes, or humans wearing avali clothes. The result is the guests' body texture glitching (the giant pink square bug). Perhaps make it so that guests won't buy items that they cannot (or at least SHOULD not) be capable of wearing/wielding.

**Comment by OrionFive** [comment]
Sounds like I'm missing another check. I'll investigate.

**Comment by OrionFive** [comment]
Fixed in new version.
