### ISSUE TITLE
Errors on loading the game and loading my save

### ISSUE THREAD

**Issue by carcigenicate** [OrionFive/Hospitality#260]
When loading the game:

https://gist.github.com/carcigenicate/51078c392b839e8884ed94f9334ad62e

When loading my save:

https://gist.github.com/carcigenicate/59bce6210f8e4fd246d1da89749723a3

I tried playing around with mod order and it didn't seem to change anything.

I saw a reference to the "min visitor group size" in the error, so I went into the mod settings, and if I try to change the min settings, I get:

https://gist.github.com/carcigenicate/1be07f422b6e8367ec21f5949dda017b

Changing the other settings.

And I just noticed that for some reason, the "max" setting is missing from yesterday:

![20190703074948_1](https://user-images.githubusercontent.com/18216244/60597017-63056100-9d67-11e9-97a0-09df37e5304a.jpg)

-----

I unsubscribed/resubscribed and all the errors stopped happening and I got the "max" settings back 

¯\\_(ツ)_/¯

**Comment by OrionFive** [comment]
Sometimes Steam doesn't update mods correctly. Resubscribing can fix this. Glad you could sort it out.

**Comment by carcigenicate** [comment]
@OrionFive I'm not so sure this is related to updating mods. It just happened again, and it says you haven't updated the mod since Jun 10. Re-subscribing is also no longer fixing it.

**Comment by OrionFive** [comment]
Well, the errors you're having mean that your mod config file is busted. So I was surprised that it fixed itself.
The easiest fix is to just find and delete that file (or rename it, so you have a backup).
