### ISSUE TITLE
Faction visit spam

### ISSUE THREAD

**Issue by wallacemcduff** [OrionFive/Hospitality#262]
Here's my log

https://gist.github.com/7e3c82b982a274d267fa44743d0c0b1a

Getting a lot of slowdown with "Faction are coming after 45.644433 days" messages endlessly looping and slowing down the game. The error message mentions hospitality but it might be another mod conflict, I just can't think which one would be doing it.

**Comment by OrionFive** [comment]
Looks like a mod conflict, but I'll see if I can recreate it.

**Comment by OrionFive** [comment]
Hm. You mention an error message. There's no error in your log, so I can't see what's going wrong. Also, your log misses the stack traces. No idea how you managed to turn that off... 
Sorry. At this point, I don't have the information I need to help you. You could try resubscribing the mod or changing the load order. These things sometimes help.
