### ISSUE TITLE
[Suggestion] Occasionally visitors will come for medical treatment

### ISSUE THREAD

**Issue by ThePuzzlemaker** [OrionFive/Hospitality#266]
I had an idea for an addition to this mod or some type of addon that could be made to it where occasionally, visitors will come with various medical issues and will need treatment.

**Comment by OrionFive** [comment]
But then I'll have to make medical beds work correctly for guests 🙄

**Comment by PentalimbedPuss** [comment]
I have an idea. Disable self tending for patient type guests but add an option to manually talk (right click) about starting the operation. After that the patient will collapse and behaves just like escape pod refugees. If fully recovered (or some checking on certain Hediff removed) the guest will leave gifts as fee. For severly injured, just let them arrive in drop pod.

**Comment by ghost** [comment]
> But then I'll have to make medical beds work correctly for guests

I have an idea. Disable self tending for patient type guests but add an option to manually talk (right click) about starting the operation. After that the patient will collapse and behaves just like escape pod refugees. If fully recovered (or some checking on certain Hediff removed) the guest will leave gifts as fee. For severly injured, just let them arrive in drop pod.

**Comment by OrionFive** [comment]
Hm... It might work, but also adds micro management, which doesn't sit well with everybody.
Also, when a pawn collapses he drops his entire inventory. That might be a bit too much payment sometimes.

**Comment by ghost** [comment]
It seems like Down For Me has made it that you don't drop everything when you fake down,  or you could make patient come with clothes only, accompanied by their friends as normal guests who will pay later. 
As for micro management, this is probably the minimum effort I could think of without digging into the code. I suppose patients wouldn't be that frequent, so it couldn't be more bothersome than actual escape pod rescues where you may have to travel across the map to fetch them. In this case they will just walk to or drop in right place like orbital traders.

**Comment by OrionFive** [comment]
I think the best solution is probably a dedicated letter saying "person x is in need of treatment and has asked for your help. If you do not help, he might be able to treat himself."  If the player chooses "Offer help"  the pawn will be marked for treatment, with "Refuse" marked for no treatment. This might be a whole lot of work - but then I think this feature will be a lot of work in any case.
Maaaybe I could even show a list of all wounded pawns in the dialog, with a selector for each, what kind of medication they will get.
What I'd like to avoid for convenience is that the player has to check every guest and/or find them on the map.

One thing to keep in mind is that I can't just make a pawn collapse unless I damage them to a point that they can't walk anymore. If they can walk, they will.
Another is that currently, the player's doctors will treat guests anyway, once they lie down in a bed - unless they treat themselves first. So by setting the guests' treatment option, the player will have the best control over how they're dealt with. It does mean I should also expose those settings again to the guests' personal guest dialog.

**Comment by ghost** [comment]
Well, I was thinking about adding a hediff that does nothing but zeros movability and some floating icons like the ? on traders, but obviously you know about modding better than me. It seems a lot of work to do. Good luck.

**Comment by OrionFive** [comment]
Yeah it can probably be hacked somehow. But every time you do that, you risk trouble with countless mods.

**Comment by OrionFive** [comment]
In the next version, guests will use medical beds when they need treatment. They will also not self tend anymore. I'm not interested in doing more in that direction for now.

**Comment by OrionFive** [comment]
I consider this covered by Royalty quests. Not exactly the same, but close enough, given how much work this is.
