### ISSUE TITLE
Visitors not arriving after announcement

### ISSUE THREAD

**Issue by Sonsalt** [OrionFive/Hospitality#279]
With the latest version, visitors are being announced but don't actually show up.

When clicking on the "go to" button it moves to the edge of the map but there is nothing.

**Comment by OrionFive** [comment]
Log?

**Comment by Sonsalt** [comment]
didn't get any error messages, or I would have added them.

Next time it happens I will share the entire log file.

**Comment by OrionFive** [comment]
It's not only about the errors, but I need to see your mod list, load order, warnings, etc.
Can't promise you it'll help, but I don't know until I've seen it.

**Comment by Sonsalt** [comment]
[output_log.txt](https://github.com/OrionFive/Hospitality/files/3490025/output_log.txt)
all the critical errors are accounted for.

**Comment by OrionFive** [comment]
Hm, can't read that on the go. I'll take a look at home tomorrow... Or you can just use Ctrl-f12. That I can read on my phone.

**Comment by OrionFive** [comment]
Hm. The best I can find is that What The Hack failed to generate a pawn. If this happens, a visitor group might not spawn. Sorry, I can only assume it's a more or less random mod conflict and there's nothing I can do about it.
