### ISSUE TITLE
issue with the android tiers mod

### ISSUE THREAD

**Issue by fluffmeister123** [OrionFive/Hospitality#294]
When an android is a quest and they try to sleep or do other "normal" activities like eating it shows an error that the android (name) does not need to sleep

**Comment by OrionFive** [comment]
Thanks for adding it here. Unfortunately, this is a fix that will take me quite a lot of time (I'm expecting a full day at least). So I'll put it up for a vote when I update the voting poll.
This does mean there won't be a fix any time soon, though. You'll be notified via GitHub when something moves along, though.

**Comment by OrionFive** [comment]
Is this still an issue in 1.1?

**Comment by mc-oofy** [comment]
> Is this still an issue in 1.1?

@OrionFive tried in 1.1 and no error

**Comment by OrionFive** [comment]
Thanks for letting me know!
