### ISSUE TITLE
Not all friends are being counted

### ISSUE THREAD

**Issue by rlancaster** [OrionFive/Hospitality#295]
I have a guest who requires 3 friends to recruit.  Her social tab indicates that she has 3 friends in my colony, but her guest tab shows her at only 1 of 3.  [Here are screenshots of these tabs ](https://imgur.com/a/H4Uel7w).

**Comment by OrionFive** [comment]
Ah, I see where the confusion comes from. Do you see the green bar in the background of the social tab? It has to be full for them to count as friends for Hospitality.
