### ISSUE TITLE
Trigger current action cancel on joining as guest

### ISSUE THREAD

**Issue by ssauraabi** [OrionFive/Hospitality#296]
Currently when someone leaves a medical bed they start a walk to the edge of the map and during this walk the trigger for making them a guest will occur, but they will not go to the guest area until they have completed their current walk to the map edge.

This can cause some issues (if they're leaving mid raid, if you're playing with Zombieland, etc.) with the safety of the guests.

If possible, it would be preferable that them joining as a guest interrupts/cancels their current walk path.

**Comment by OrionFive** [comment]
I can fix that. Thanks for the report.

**Comment by OrionFive** [comment]
Should be fixed in the next update.
