### ISSUE TITLE
Refugees who become un-incapacitated cant be healed, end up bleeding to death 

### ISSUE THREAD

**Issue by 321nick** [OrionFive/Hospitality#30]
so, if a refugee from a escape pod, or any other event, gets wounded and bleeding ,is incapacitated, but then becomes un-incapacitated, they will usually walk to one of my medical beds, then lay there and die as i cannot heal them as there is no option.

**Comment by OrionFive** [comment]
Will look into it, thanks!

**Comment by OrionFive** [comment]
Okay, from what I can tell this is a vanilla problem.
