### ISSUE TITLE
Rescued guests being stuck is back 

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#306]
****ing house of cards.

**Comment by OrionFive** [comment]
Couldn't reproduce this yet.

**Comment by Tharn** [comment]
![Untitled](https://user-images.githubusercontent.com/13466852/65823080-b9434c80-e24f-11e9-806b-0065b8aed440.png)

Is this it?

I rescued a guest who got injured during a raid. He stayed in bed, but got up before his injuries had fully healed, stuck on the spot. His status is set to 'wandering', but once every few seconds for a fraction of a second it says 'standing'.

Setting his accomodation to 'Unrestricted' fixed it. He went back to bed.

**Comment by OrionFive** [comment]
Interesting! What area was he set to before? Was the bed inside that area?
What does his guest tab look like?

**Comment by Tharn** [comment]
No, he was set to a 'Guest' area which was another building quite a bit away from the colony hospital. So as soon as he got out of bed, he was out of bounds and I guess that resulted in him being unable to move. I don't have him anymore, but he had both residence & buy areas set to 'Guest', as well as to be entertained.

**Comment by OrionFive** [comment]
That would make sense then. I'll see if I can reproduce this.

**Comment by Tharn** [comment]
If the pawn makes it out of the hospital before he turns back into a Guest, it seems him being out of his allowed area is enough to get him stuck. Even if there aren't any doors in the way.

**Comment by Tharn** [comment]
A twist on this rescued guests bug:
I rescued an already established guest after a fist fight with a colonist. I was able to take him to the hospital and bandage him. After a while (still bandaged), he got up by himself and started wandering back to the Guest allowed area. He never slept or got food even though he had a designated bed. I could only fix this by allowing the hospital area. He went back into a hospital bed immediately. Without this change, he would have fallen asleep on the floor and / or starved. Even though guests appear to take food without paying when they have no money and are close to starving, this one never did.

A guest who has been rescued like this will also be charmed by colonists even though he's in a hospital bed.

**Comment by OrionFive** [comment]
Yeah that doesn't sound surprising. Hospital beds are a bit of a special case. RimWorld has so much stuff hard-coded with them.
Thanks for the insight. Maybe this is the problem in the first place.

**Comment by OrionFive** [comment]
I can't fix this. Since guest beds aren't "real" beds, which RimWorld has hardcoded into all the resting jobs, I can't find a reasonable way to solve this. Guests just can't heal in guest beds. But once a guest is injured, he'll try to heal, so he won't use them.
