### ISSUE TITLE
Rescue -> Guest bug

### ISSUE THREAD

**Issue by Tharn** [OrionFive/Hospitality#311]
I rescued someone from a neighboring faction from a pod. She was brought to the hospital with a couple of bleeding cuts and about 10 hours to live. So far, so good.

Before my medic could tend to her, her allegiance was changed and she was now a 'Guest'. She started tending to herself **at a snail's pace**. Before she could even finish fixing a single cut, she passed out. I rescued her and put her in bed. I set a medic to tend to her. Seconds later she's back up and tries to fix her own bleeding cuts again. 'X is now a Guest' message pops up a second time. The whole thing repeats. The death timer keeps on ticking.

This is with v1.0.29.

**Comment by Tharn** [comment]
She was eventually saved. The 'became a Guest' popup happened in total 4 times. After the 4th time, she had her bandages on and managed to leave the hospital to go to the guest quarters.

Without food and money, she began to starve quickly. And without hospital beds, behaving like a normal guest and not staying in bed, the wounds healed very slowly, exacerbating the issue.

I suggest not turning rescues into guests. I don't see this working as intended. As a compromise, you could enable rescues turning into guests **after** they've been healed. When they would normally leave the map.

**Comment by OrionFive** [comment]
I'll look into it.

**Comment by Tharn** [comment]
Cheers. One correction: The colonists do feed starving guests when they're in bed, so she made it out alive.

**Comment by OrionFive** [comment]
I've looked into it. Self-tending is a vanilla thing. They will do it, guest or not. I am, however, adding a clause that they will only become guests once they don't need urgent tending anymore.
