### ISSUE TITLE
Error Loop on Event Trigger

### ISSUE THREAD

**Issue by Sharkeybtm** [OrionFive/Hospitality#32]
I'm playing on a heavily modded playthrough, so i don't know if that causes any problems. This incident has happened when Hospitality has been loaded first and as well as last. Event gets stuck in a loop and drops FPS to 2-3.

System.NullReferenceException: Object reference not set to an instance of an object
  at Hospitality.IncidentWorker_VisitorGroup.TryExecute (RimWorld.IncidentParms parms) [0x00000] in <filename unknown>:0 
  at RimWorld.Storyteller.TryFire (RimWorld.FiringIncident fi) [0x00000] in <filename unknown>:0 
  at RimWorld.IncidentQueue.IncidentQueueTick () [0x00000] in <filename unknown>:0 
  at RimWorld.Storyteller.StorytellerTick () [0x00000] in <filename unknown>:0 
  at Verse.TickManager.DoSingleTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by OrionFive** [comment]
Sorry... from this I can't reproduce the problem.

**Comment by Sharkeybtm** [comment]
It's not reliably reproducible for me either. It's just a matter of when this event happens. I haven't found a way to force it and can't reliably solve it. Saving and reloading results in a unloadable save. Loading the previous auto save is the only reliable way to avoid this event.

**Comment by Sharkeybtm** [comment]
If you can tell me a way to force the events, I can find a way to reproduce it and give you the results then.

**Comment by OrionFive** [comment]
This is possible through the developer menu and called execute incident.

**Comment by Quarabi** [comment]
I did get something similar, where:
while starting the Visitors incident it stuck in an infinite loop spawning infinite Pawns, which tried to leave the map again.
Saving and reloading fixed the Problem for me and I got the massage that visitors came. 

I could not reproduce it whith the dev mode.
(also with a lot of mods)

**Comment by Sharkeybtm** [comment]
Yeah, I've been trying but I can't seem to reproduce it. Is there an old piece of code hanging around that gets triggered normally but not with dev mode?

**Comment by OrionFive** [comment]
Yeah there is one piece, and that is the check if it's actually allowed to spawn visitors. But it doesn't do anything special.

**Comment by OrionFive** [comment]
Can't reproduce.
