### ISSUE TITLE
Some guests can't be rescued 

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#321]
> It appears I have the same issue as @Coldsteel122. Visitor came, as a wimp and had gut worms. The gut worms got more severe and downed the visitor in their bed. My colonists were treating and feeding her but I just wanted to send her away. I unmarked the bed for visitors and it kicked her out now she's downed outside the bed. I can't rescue her because I have no non-prisoner-safe-temperature beds when I have both empty colonist beds and medical beds. Remarked the bed for visitors and it didn't change anything. I've seen visitors get injured and downed before but I believe because she's downed but not injured it may be causing an issue.

**Comment by Coldsteel122** [comment]
https://gist.github.com/HugsLibRecordKeeper/1d904b74cef9dc4437f8e465134b1511
Saw you wanted logs for this, on your Steam.

**Comment by OrionFive** [comment]
Thanks! Sorry Sorry for the late response. Busy days. It looks like zombie land is breaking the door code for pathfinding in your game. That could mean that the medical beds are not considered reachable (or the code flow stops with the first door that is encountered).

**Comment by OrionFive** [comment]
Hm. I'm not sure if you can rescue pawns that aren't injured. Just downed is kind of a weird situation. 

I've tried some fixing, but I can't even recreate the situation.
