### ISSUE TITLE
pawn.story is null resulting in root level exception

### ISSUE THREAD

**Issue by SmashPhil** [OrionFive/Hospitality#324]
In WorkGiver_Recruiter it calls ShouldSkip which attempts to call a method from pawn.story, except in a mod I'm currently making the pawns (boats) don't have a storytracker, resulting in a root level exception.  Can you add a null-conditional (?.) operator so that if the pawn does exist without a storytracker (in this case boats) it won't attempt to call that method.  Could be something as simple as
`return pawn.story?.WorkTagIsDisabled(def.workType.workTags) ?? true;`  

thanks!

**Comment by OrionFive** [comment]
Sure, I can do that. Not sure when I'll get around to an update, though. Maybe you can overload the method from your end until then?

**Comment by OrionFive** [comment]
I've applied the fix. Will be rolled out with the next update (whenever that will be...).
