### ISSUE TITLE
Possible issue with this mod & Psychology

### ISSUE THREAD

**Issue by Tharn** [OrionFive/Hospitality#326]
Discovered an issue between this mod and Psychology:

A guest received a social smackdown by one of my bionic terminators and later developed anxiety while in the hospital (highly entertaining so far).

However, as all her bruises had healed and the anxiety had been treated, she got up and was stuck in 'Cowering. Queued: Fleeing'. She was stuck on the tile of her hospital bed, similar to that other hospital-related issue. Idk if this is a mod mixup or what.

**Comment by OrionFive** [comment]
Hospitality has trouble with hospital beds. Is the hospital bed inside the guest area?

**Comment by Tharn** [comment]
Yes, I expanded the guest area after this other issue became apparent.
However, the guest wasn't *in* bed anymore. She was just not moving off the tile.

Anyway, I reported this just on the off chance that it's not related to the hospital beds.

**Comment by OrionFive** [comment]
I'm closing this for now. Odds are that the new conflicts with psychology are of an entirely different nature. Feel free to open it again, should the issue arise again.
