### ISSUE TITLE
Option to feed rescued pawns that become guests or give them food or other items as gifts.

### ISSUE THREAD

**Issue by Negomir** [OrionFive/Hospitality#328]
Rescued pawns from the transport pod crash event that become guests won't have their own food and there is no way to feed them other than downing/arresting them, or waiting for them to collapse.

**Comment by OrionFive** [comment]
That is a solid point. I never had issues with this myself, but I can see how it could be problematic.

**Comment by OrionFive** [comment]
#329 will solve this.

**Comment by OrionFive** [comment]
Fixed in new version.
