### ISSUE TITLE
Visitors would overdose themselves all the time.

### ISSUE THREAD

**Issue by SheakZarnn** [OrionFive/Hospitality#33]
Not really a bug, more of a strange behaviour. I've noticed that most of my visitors are total junkies. I mean if they manage to lay their hands on some drugs, they'll just overdose themselves to death. When they have nothing to do, they'll look for closest entertainment (which is drugs in their inventory), so they'd naturally use them till their joy bar is full. When that bar drops abit naturally (and I mean a few ticks later), they'd just use another dose. And another a few more ticks later, eventually killing themselves.
Visitors really need some mood, or joy check before using drugs.

**Comment by OrionFive** [comment]
Thanks for reporting this. I haven't had that yet. Chances are some other mod affects their behavior. But it's not the first time I hear of this issue, so it would be good to find out what causes it.

**Comment by OrionFive** [comment]
I've slightly reduced this. Let's see how bad it gets.
