### ISSUE TITLE
Toggling guest bed deletes delivered plan

### ISSUE THREAD

**Issue by Aurani** [OrionFive/Hospitality#330]
1) Construct a bed and set it as a guest bed.
2) Place a plan for any other bed on top of the guest bed to replace it.
3) Deliver any amount of materials to the plan.
4) Toggle the guest bed into a normal bed. (Edit: Toggling a non-guest bed into a guest bed also works)
5) The plan with all its contained materials vanish from the game.

[Logs here](https://gist.github.com/384df7e2c5436ffce98e3784599f4063)

**Comment by OrionFive** [comment]
Thanks for reporting this. I hadn't heard of this issue before.

**Comment by OrionFive** [comment]
I've looked into this. It shouldn't be possible to place a new plan on a guest bed. So this must be from some mod.
