### ISSUE TITLE
Problem with saved guests staying on the map until they die

### ISSUE THREAD

**Issue by PlatoSoft** [OrionFive/Hospitality#335]
I saved a downed / injured guest and installed a new leg for her, but she didn't leave afterwards and almost starved to death. She didn't eat, didn't use any beds. Basically stuck in a logic loop.
**_Restarting the game made her snap out of it and she left the map and i got my points for saving her._**

Using a fair bit of mods (not in load order):
HugsLib
Hospitality
SmartMedicine
Color Coded Mood Bar
Mining Priority
DIY Neutroamine
Miniaturisation
Mod Manager (Fluffy)
Replace Stuff
Show Hats With Hair
Better Vanilla Masking
Research Tree
Relations Tab
Medical Tab
RPG-Style Inventory
and RimHUD

more context:
she arrived with a trading caravan and they started fighting in my guest area 😄 
the caravan left while she was resting, so i decided to give her a new leg.
everything seemed fine but she stopped interacting after surgery
i tried to lure her to the fridge but she ignored the food and any furniture/recreationals.

great mod btw! really gives it more depth.
thanks for your time.

**Comment by OrionFive** [comment]
Thanks for reporting this. I don't think I can fix it for 1.0, though. These obscure circumstantial bugs are almost impossible to reproduce. 
And with 1.1 there will be a hundred new, more pressing bugs.

**Comment by PlatoSoft** [comment]
No worries, my workaround of letting the game restart works for now. This is probably the last game of 1.0 i play anyway.

**Comment by OrionFive** [comment]
Please reopen if this issue happens again in 1.1.
