### ISSUE TITLE
Visitors leaving spam

### ISSUE THREAD

**Issue by Dovafox** [OrionFive/Hospitality#34]
System.NullReferenceException: Object reference not set to an instance of an object
  at Hospitality.LordToil_VisitPoint.Leave () [0x00000] in <filename unknown>:0 
  at Hospitality.LordToil_VisitPoint.Cleanup () [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Lord.GotoToil (Verse.AI.Group.LordToil newLordToil) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Transition.Execute (Verse.AI.Group.Lord lord) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Transition.CheckSignal (Verse.AI.Group.Lord lord, TriggerSignal signal) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Lord.CheckTransitionOnSignal (TriggerSignal signal) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Lord.LordTick () [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.LordManager.LordManagerTick () [0x00000] in <filename unknown>:0 
  at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

This is causing the visitors is leaving to spam 10 times a second. They won't leave so there is no point in waiting.

**Comment by OrionFive** [comment]
That's unfortunate. Thanks for reporting it. But it's also not enough information to reproduce the problem. 
Could you attach your complete log?

**Comment by Dovafox** [comment]
I can only show you the old one which is pretty spammed. Since when I restarted about 5 times it actually worked, I guess it was because it restarted the whole script sequence since I made an alternate save when the glitch was happening. Nonetheless, some other guy on steam have the problem too. Might aswell figure out why this is happening. 
[eb19995270bc24f692858818c6e5acf1-0958c85a609345cea734ef43743770044788290d.zip](https://github.com/OrionFive/Hospitality/files/721036/eb19995270bc24f692858818c6e5acf1-0958c85a609345cea734ef43743770044788290d.zip)
The complete output file is attached to this comment.

**Comment by NightBurst** [comment]
Just had this problem, i don't have the logs cause I don't know where to find them, but it went on for close to 20 minutes while I tried to seal them and freeze them to death.

**Comment by rb303** [comment]
I have this exact same problem, and I've resorted to just killing them
http://prntscr.com/e66p5x
here's the uploaded logs:
https://gist.github.com/HugsLibRecordKeeper/ea2def392455b16a9cf0b8127c198526#file-output_log-txt-L474

**Comment by OrionFive** [comment]
Thanks for the log, I so think I can narrow it down with this. How far into the game were you? Did you have a second base or caravan spot? Have you destroyed any enemy bases?

**Comment by YamaOfParadise** [comment]
I'll bump this to say that I just ran into the same error; from what I can tell, the visitors are stuck in a loop between trying to sleep/relax socially (at the end of a day) and leaving. They'll get part of the way through each activity before cycling to the next. (It does show up as being disturbed during sleep.)

As for the progress I've been in, not particularly far. This is perhaps the third group that's managed to show up, I've yet to make a caravan (though that may just be because I'm lagging behind in "normal" progress) nor have I ever built a new base.

I'll work on getting another log of this on my end for you.

**Comment by OrionFive** [comment]
Thanks

**Comment by OrionFive** [comment]
Ah, wrong button. Thanks for the input. The log will help a lot.

**Comment by OrionFive** [comment]
It seems the latest version has resolved this issue.
