### ISSUE TITLE
Hospitality 1.1 Update

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#341]
- [x] 1. Update all other mods first
- [x] 2. Test the DLC sufficiently to get an idea what needs to be adjusted/integrated
- [x] 3. Fix the most important remaining usability issues of the other mods
- [x] 4. Adopt the new multi-version file structure (easy)
- [x] 5. Change the code files to match Unity's new paths and .Net framework (easy)
- [x] 6. Update all files using Harmony to now say HarmonyLib, it also updated (fortunately that's about all, could be much worse, still easy)
- [x] 7. Go through the code and find all RimWorld methods/fields that obviously changed and use whatever they are now (usually easy, but takes some time, especially if they were just made private or completely removed)
- [x] 8. Fix any obvious issues arising from these changes (can be hard)
- [x] 9. Run the game to get the first list of issues
- [x] 10. Fix all the definition files that are listed as broken (can take quite some time)
- [x] 11. Fix all the Harmony patches and code that refers to methods/fields by name, look them up in the RimWorld code and see how and why they changed (time-consuming, also hard if it's transpilers) 
- [x] 12. Do the steps 5-8 until no more errors show when the mod is loaded
- [x] 13. Load a game with the mod active
- [x] 14. Do those steps again, until no more errors show when loading a game (can take hours to days in the worst case)
- [x] 15. "Play" the game and try to produce all the special situations that can arise with the mod to see if they work correctly or give errors, then fix them (difficult, can take days to weeks)
- [x] 16. Implement all the Todos that are only possible when a major version change happens (can be an extra few days)
- [x] 17. Clean up the code, remove testing logs, refactor, etc. (goes pretty quick usually)
- [x] 18. "Play" again to see if anything broke (see above)
- [x] 19. Activate a list of common mods that should be compatible, and "play" again (see above) 
- [x] 20. Fix any mod conflicts that popped up (often very hard and time-consuming)
- [x] 21. Cross my fingers, release the update
- [x] 22. Await the inevitable shitstorm because steam didn't update someone's mod correctly, someone has a broken save file that breaks my mod, or the mod is not compatible with obscure mod x, or someone's game is so broken everything is in pieces, including my mod so it must be the cause
- [x] 23. Deny any responsibility, while following every lead to find out if it's actually a bug in my mod, then fix it
- [x] 24. Since any fix potentially breaks something new, go back to step 15 and start over from there 
- [x] 25. Consider the update process complete

**Comment by Ooraka** [comment]
CANNOT wait for this to be finished for 1.1

**Comment by OrionFive** [comment]
Me neither. But since people get notifications for comments here, let's keep the chit-chat to the Steam comments ;)

**Comment by tizubythefizo** [comment]
For number 17, you could keep your test logs and do some #if DEBUG 's. Make sure to test in debug mode, then step 17 would just become "Switch to release mode and build" and you could keep important testing logs for future regression purposes to boot.

**Comment by OrionFive** [comment]
Thanks to @simplyWiri for helping with steps 4-7. 
@tizubythefizo, yeah, not a terrible idea. Although most of the time the logs are really specific to what I'm currently testing. So turning all of them on at once might do more harm than good. I could replace them with assertions or something. That might actually help.

**Comment by eksynn** [comment]
`hype mode: activated!`

**Comment by OrionFive** [comment]
![](https://media.giphy.com/media/URuzvsMZNVm2wRd9K3/giphy.gif)
Almost there!

**Comment by tizubythefizo** [comment]
Oh you tease you ;)

**Comment by simplyWiri** [comment]
I've done some relatively extensive testing with a few other common mods (some publicly released, some testing for 1.1 as well)

I've ran into one crash to desktop. The issue plagued a certain save, I can't seem to recreate it using the same collection of mods in other saves.

This error occurred when; 
The first two guests of the save attempted to leave the map.  To stop this save crashing to desktop, I could forcibly dismiss them, however, they ended up bugged and stood around on the edge of the map. In the same save, I've had no issues with guests since. (The two colonists simply starved to death at the edge of the map). I saw no errors in the log, I assume it was a bizarre one off error, and I'm not familiar enough with your code base to track it down myself :)

I'll keep trying to recreate the error, If I have any luck i'll file an issue / PR.
Cheers for your work updating the mod!

**Comment by OrionFive** [comment]
![](https://media.giphy.com/media/39pru9GPwMT6cEafLy/giphy.gif)

**Comment by tizubythefizo** [comment]
Woohoo! Thanks for all the hard work Orion.

Now the real question is do I grab it now, or quietly and patiently sit and watch others pain in the comments while steps 22-25 happen >.>

**Comment by OrionFive** [comment]
So far there's not that many issues reported. We'll see how that goes.

**Comment by CuteLasty** [comment]
Can I share you my traditional Chinese translate file to put on github?

But there are some lines I'm not sure how to translate, still English.

**Comment by OrionFive** [comment]
Sure. Either make a pull request with your files or upload them somewhere as a zip file and send me a link. You can best open a new issue for that.
