### ISSUE TITLE
1.1 W.I.P Version breaks wardening 

### ISSUE THREAD

**Issue by canefe** [OrionFive/Hospitality#351]
Finally I could find which mod is breaking that. I know the 1.1 version still on development but I thought this would help with bug-solving.

Bug: Wardening does not work. (even though it is only priority for the colonist, colonist just won't do any actions about wardening).

Mods: (just incase it is about incompatibility with another mod)

- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: roolo.giddyupcore
  Name: Giddy-up! Core
- Id: dylan.csl
  Name: Children, school and learning
- Id: pyrce.mass.graves
  Name: Mass Graves
- Id: dubwise.dubsbadhygiene
  Name: Dubs Bad Hygiene
- Id: community.psychology.unofficialupdate
  Name: '[1.1] Psychology (unofficial)'
- Id: mlie.wehadatrader
  Name: We Had a Trader? (Continued)
- Id: mlie.foodalert
  Name: Food Alert (Continued)
- Id: edb.preparecarefully
  Name: EdB Prepare Carefully
- Id: murmur.walllight
  Name: Wall Light
- Id: jaxe.rimhud
  Name: RimHUD
- Id: gt.sam.tilledsoil
  Name: Tilled Soil
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: weilbyte.snapout
  Name: Snap Out!
- Id: jaxe.bubbles
  Name: Interaction Bubbles
- Id: crashm.colorcodedmoodbar.11
  Name: CM Color Coded Mood Bar [1.1]
- Id: roolo.giddyupcaravan
  Name: Giddy-up! Caravan
- Id: orion.hospitality
  Name: Hospitality
- Id: fluffy.relationstab
  Name: Relations Tab
- Id: roolo.giddyupbattlemounts
  Name: Giddy-up! Battle Mounts
- Id: roolo.runandgun
  Name: RunAndGun
- Id: roolo.giddyuprideandroll
  Name: Giddy-up! Ride and Roll
- Id: showhair.kv.rw
  Name: '[KV] Show Hair With Hats or Hide All Hats - 1.1'
- Id: roolo.searchanddestroy
  Name: Search and Destroy
- Id: gloomy.gloomyhairmk2
  Name: Gloomy Hair mk2
- Id: ogliss.thewhitecrayon.quarry
  Name: Quarry 1.1
- Id: fluffy.medicaltab
  Name: Medical Tab
- Id: avius.locks
  Name: Locks
- Id: usgiyi.slaveoutfits
  Name: Slave Outfits [1.1]
- Id: avius.prisonlabor
  Name: Prison Labor
- Id: jelly.puahunofficial
  Name: Pick Up And Haul - Unoffical
- Id: fluffy.blueprints
  Name: Blueprints
- Id: fluffy.colonymanager
  Name: Colony Manager
- Id: fluffy.researchtree
  Name: Research Tree
- Id: sarg.smartspeed
  Name: Smart Speed
- Id: uuugggg.replacestuff
  Name: Replace Stuff
- Id: crlsniper.realisticrooms
  Name: Realistic Rooms
- Id: neptimus7.progressrenderer
  Name: Progress Renderer
- Id: taveron.increasedstack
  Name: Increased Stack
- Id: rimfridge.kv.rw
  Name: '[KV] RimFridge - 1.1'
- Id: fluffy.modmanager
  Name: Mod Manager

**Comment by canefe** [comment]
After removing majority of mods:
I realized it is %100 incompatibility issue with another mod

I
v
Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: orion.hospitality
  Name: Hospitality

**Comment by canefe** [comment]
Just started playing game once again and realized it wasn't the hospitality. Problem is still going on for reason and most likely it is not hospitality.

**Comment by OrionFive** [comment]
Fair enough. Thanks for looking into it.
