### ISSUE TITLE
Sound Effect loop when opening Guest tab

### ISSUE THREAD

**Issue by dsp1207** [OrionFive/Hospitality#354]
[Log here](https://gist.github.com/HugsLibRecordKeeper/58d503cf00e39deb46d16b90bf227267)

When I open the Guest tab on a pawn the game plays the slider movement sound on rapid repeat, which goes away when I close the tab, pretty annoying. It's the slider movement sound, same as when changing max range on tasks. 

[Here's a quick screengrab](https://www.dropbox.com/s/e74kcgrkszt6hke/Untitled.mp4?dl=0)

**Comment by OrionFive** [comment]
You have a mod that adds ants and it requires Alien Races Framework. Try adding that and see if it helps.
