### ISSUE TITLE
Guest not claiming a bed

### ISSUE THREAD

**Issue by misterstormcrow** [OrionFive/Hospitality#356]
Hi Orion, many thanks for the mod!
I have an issue where one of the latest group of guests, isn't claiming a bed, despite there being plenty.
In her needs tab, it says "could not afford a bed", even though they are 0 silver and she has 47 silver in her gear tab.
It also says "not enough guest beds" which presumably should be mutually exclusive to the affording a bed message?
The log is collected after she woke up and set off for a game of billiards.
I read your bug reporting instructions and tried to fix it with an unsub/resub.
I've tried setting a cost of some beds, setting a cost and removing the cost and unsetting guest/resetting guest for the unused beds.

Log:
https://gist.github.com/HugsLibRecordKeeper/a4af3b3d57a665d6ffc9f5b797bd08b0
Guest room:
![Beds](https://user-images.githubusercontent.com/12295224/77253533-d7b06080-6c52-11ea-8900-323550d1e136.jpg)
Hobo Guest:
![Sleeping](https://user-images.githubusercontent.com/12295224/77253538-dd0dab00-6c52-11ea-9382-8eeec38bc047.jpg)

Before posting, I decided to see if I could get some more insight into it.
I set a rent a on a few beds which did nothing.
Abram wasn't in bed so I unset/set guest on his bed.
He immediately fell asleep on the floor of the rec room with the needs "could not afford a bed" and "not enough guest beds". His rest bar is at 66% and his name is still on his guest bed.
This was captured shortly after Abram fell asleep.
Many Thanks!

2nd Log:
https://gist.github.com/c03bda1b8a474efdbed2516abf789da6

**Comment by OrionFive** [comment]
Thanks for the thorough report. Unfortunately I can't see anything that would give an indication to what's wrong. I'm guessing it's a mod conflict. You could try moving Hospitality around a bit in the load order, see if that helps.

**Comment by OrionFive** [comment]
Let me know when you have more information. You can reopen the issue then.

**Comment by misterstormcrow** [comment]
Hi Orion, I am glad to be able to tell you the issue was between the keyboard and the screen.
My home area wasn't covering all of the guest room so only some of the beds were available.
Thanks again for the mod and my apologies for any time you've spent investigating.

**Comment by OrionFive** [comment]
Thanks for letting me know! I'm glad you figured it out!
