### ISSUE TITLE
Mod seems to not be working anymore

### ISSUE THREAD

**Issue by C9BigBalls** [OrionFive/Hospitality#357]
Hey,
So, I was using this mod with no problem, but I decided to add some more mods to my collection last night. For some reason, I received a guest on the first couple of minutes, but then it seems as if the option to have guests just disappeared. I also don't receive any visits from any traders now, which is kinda weird. Chances are it's not this mode, but something in conflict. Here is a log from when I load my mods:
https://gist.github.com/f67464f7953e1659775057f67f1dedb3

Thanks

**Comment by OrionFive** [comment]
Did you make the log from the main menu?
Could you load your game, and trigger the visitor group event from the dev menu and make a new log then?

**Comment by OrionFive** [comment]
Feel free to reopen this when you have more information.

**Comment by C9BigBalls** [comment]
Yep, there was actually an error for a while. I found the problem and it seems fixed now. Altough the number of traders I get is super low, at least there are some friendlies now
