### ISSUE TITLE
Traditional Chinese support for 1.1

### ISSUE THREAD

**Issue by CuteLasty** [OrionFive/Hospitality#359]
https://github.com/CuteLasty/Hospitality-1.1-zhTW

**Comment by OrionFive** [comment]
Thanks, I've added it. Next version it will be included.

**Comment by CuteLasty** [comment]
@OrionFive I still have some question:
What are these lable (or tag) means? Something like:
[ConceptPositive]
[ConceptNegative]
[ConceptAny]

Where can I see that? The best way is use debugger/debug system forced to appear.

**Comment by OrionFive** [comment]
I don't understand... Where did you find that?

**Comment by OrionFive** [comment]
Ah, I see what you mean. These are defined by vanilla. You can find them in the core languages.
