### ISSUE TITLE
Suggestion: Invite non-aggressive passerbys to be guest

### ISSUE THREAD

**Issue by CYFire2402** [OrionFive/Hospitality#364]
Hi there, love this mod and use it since hour one - started with a youtubers modlist.
However, I have a suggestion:

It may occur because of other mods I use, never played Vanilla, but sometimes neutral or allied travel groups traverse through my map. I could arrest them to recruit them, but rather I would send my most sociable Pawn over and invite them to stay as guests (to lull them with my hospitality and recruit them later).

Same issue with Transport Pod Crash and highly tough pawns just standing up and moving out of the map.

I know Rimworld isn't the best place for a pacifistic playstyle, but nonetheless... pretty please?

**Comment by OrionFive** [comment]
That's pretty tricky. Also, there's a very high chance those travelers will show up in one of the guest groups later.

This is one of those features where the cost (the work I have to do for it) by far outweighs the benefits (you being able to invite people earlier).
