### ISSUE TITLE
Guests leave and all have yellow trade question mark

### ISSUE THREAD

**Issue by Polandra** [OrionFive/Hospitality#368]
When guests leave after staying they all get the yellow trade question mark above their heads as they are exiting the map. It has happened twice that I have noticed in game play just as of 3/30/20.

Error log here: https://gist.github.com/HugsLibRecordKeeper/52ce1143f7ced8c9b8ce349221a82746

![image](https://user-images.githubusercontent.com/62924371/77988048-3cf9f680-72d0-11ea-8553-b15768240667.png)

**Comment by OrionFive** [comment]
Thanks for reporting!

**Comment by OrionFive** [comment]
Should be fixed next version.
