### ISSUE TITLE
Lag spikes occur when attempting to sell biocoded weapons

### ISSUE THREAD

**Issue by Pingvinen5** [OrionFive/Hospitality#371]
I realized that the game started to lag when i made a shopping area. Therefore i investigated what could be wrong and found that biocoded weapons don't have a market value. This probably caused the lag spikes due to an error occurring when the guests attempt to buy, or at least check their value. This could probably be fixed by making the guests incapable of trying to purchase biocoded weapons.

**Comment by OrionFive** [comment]
I'll look into it. That indeed shouldn't happen.

**Comment by OrionFive** [comment]
I can't reproduce it. However next version will have a check against guests trying to buy stuff that is biocoded for someone else.
