### ISSUE TITLE
Guests do not show up, all buttons are displayed wrong

### ISSUE THREAD

**Issue by ElvezTheElf** [OrionFive/Hospitality#387]
https://gist.github.com/3535b358958b1c1bfbbf7a5b7987982e

I couldn't find the respective part for hospitality in the log which is causing the issue but guests do not show up and when the action menu which asks for letting guests in pops up buttons are displayed like (ActionGuestsAllow etc. dont remember exactly).

Tried the mode by itself and it didnt work again

**Comment by OrionFive** [comment]
Your setup is broken. Hospitality is not the issue. Make sure you have the latest version of RimWorld, HugsLib, Harmony, Hospitality, etc.
Delete 1.0 mods that you're not using.
