### ISSUE TITLE
Weird Letters and Guest can't spawn

### ISSUE THREAD

**Issue by iComii** [OrionFive/Hospitality#388]
Loading game from file The Sick Tribe with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - Haplo.Miscellaneous.Core
  - Haplo.Miscellaneous.Robots
  - Alaestor.MiscRobots.PlusPlus
  - Haplo.Miscellaneous.MAI
  - com.yayo.runtimeGC
  - 7H28J.nomoresleepingzs
  - CrashM.ColorCodedMoodBar.11
  - EdB.PrepareCarefully
  - eagle0600.massCooking
  - Jaxe.RimHUD
  - PeteTimesSix.SimpleSidearms
  - Siscos.adv.power
  - TheGoofyOne.AreaRugs
  - Buildable.Terrain
  - Linq.DeathRattle
  - dracoix.doormat.r11a
  - Taveron.IncreasedStack
  - notfood.MendAndRecycle
  - Extracting.Organs
  - RusticFox.ChickenPlucker.RR
  - Crustypeanut.RC2.Core
  - rimfridge.kv.rw
  - weilbyte.snapout
  - Orion.Therapy
  - PinoChemicali.MoreTradeShips
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - Proxyer.DESurgeries.DESurgeries
  - fluffy.blueprints
  - jelly.PUAHUnofficial
  - crlsniper.realisticrooms
  - GT.Sam.TilledSoil
  - GHXX.TechAdvancing
  - Orion.Hospitality
[Tech Advancing] [Information] Loading finished.
[Tech Advancing] [Information] Flushing old Research Manager values.
[Tech Advancing] [Information] Loading finished.
[Tech Advancing] [Information] Flushing old Research Manager values.
[Tech Advancing] [Information] Loading finished.
[Tech Advancing] [Information] Flushing old Research Manager values.
[Tech Advancing] [Information] Detected existing world. Loading existing config...
[Tech Advancing] [Information] Loading config...
Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 20514.
Total: 444.397500 ms (FindLiveObjects: 2.927800 ms CreateObjectMapping: 3.258200 ms MarkObjects: 438.074700 ms  DeleteObjects: 0.136000 ms)

Created 4 new pawns for The Red Empire.
Hospitality: Something failed when setting up visitors from faction The Red Empire(shattered empire):
bool RimWorld.DropCellFinder.TryFindDropSpotNear(Verse.IntVec3,Verse.Map,Verse.IntVec3&,bool,bool,bool,System.Nullable`1<Verse.IntVec2>)
  at Hospitality.IncidentWorker_VisitorGroup.GetSpot (Verse.Map map, Verse.Area guestArea, Verse.IntVec3 startPos) [0x0003b] in <aaca645e09e44164a5ea2a669b9155e3>:0 
  at Hospitality.IncidentWorker_VisitorGroup.SpawnGroup (RimWorld.IncidentParms parms, Verse.Map map) [0x0004a] in <aaca645e09e44164a5ea2a669b9155e3>:0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by OrionFive** [comment]
#387
