### ISSUE TITLE
Some guests don't have space and/or beauty needs

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#4]
Seemingly randomly guests are missing these needs.

**Comment by CallMeOzz** [comment]
confirmed, although it may just be a UI issue.  

Tested with multiple consecutive groups of visitors; each appeared to have at least one member missing the space and beaty needs bars (it seemed more like only one member of the group WOULD show the bars properly). 

Upon save and reload of game, I noticed that the missing space/beauty bars were available.  It seems like the needs are reflected and saved properly, but the bars are not being rendered in the UI tabs.

**Comment by OrionFive** [comment]
Both bars are situational, afaik. So even if they were created when loading the game, they would show the correct results. But when they are not there, they are not taken into account for mood, so I think this should be fixed.
