### ISSUE TITLE
Visitors digging through walls

### ISSUE THREAD

**Issue by Tiikeria** [OrionFive/Hospitality#40]
I'm playing on a newer game, and visitors, instead of routing through doors or normal entryways, dig through walls. My buildings are built into a mountain, but they aren't always digging though walls inside the mountain. They also dig into areas outside of the set Guest area. There are no debug errors reported in the log that I can give you, unfortunately.

**Comment by OrionFive** [comment]
Thanks for reporting this. This problem has existed since A16, but I can't fix it, since I never get it myself. It must come from another mod that I'm not using myself.

**Comment by Tiikeria** [comment]
That could very well be, as I do have quite a few mods active. I adjusted my guest areas a bit and it seemed to have made it happen less often. I'll see if I can possibly get a bit more information in the future for you! Thanks for all you do, Orion!
