### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by kamadz** [OrionFive/Hospitality#405]
Hi there!

**Comment by OrionFive** [comment]
Oh hey, sorry for the late reply. I thought the files would be attached already, so I just put this item in my agenda.

**Comment by OrionFive** [comment]
You can best upload the files somewhere and put a link here. Or you can send it to me on Discord.

**Comment by kamadz** [comment]
Can I just fork and then create a pull request?

**Comment by OrionFive** [comment]
Of course. That's also fine.

**Comment by kamadz** [comment]
Ok then. I'll start my work in several days, need to finish with other mod.

**Comment by OrionFive** [comment]
Sure. I'll close this issue for now. I'll see your pull request when you're done.
