### ISSUE TITLE
Locks mod still causes guests not to arrive

### ISSUE THREAD

**Issue by CrazyPenguin22** [OrionFive/Hospitality#406]
Guests and Visitors that arrive just walk around my base and leave the map immediately. Some pawns walk on the edge of the map before leaving the map. No one goes into my guest house. I have beds placed and its selected for Guests. The area lights up in blue color. I even placed a zone for guests in that room and selected it as default zone for all guests/visitors. Beds that I have placed are regular vanilla beds with prices set $30 silver for each bed.

Might be a incompatibility with some mod. No errors pop out in the log. This is the only mods I could think of that might cause the issue:

Locks
Doors Expanded
Locks Doors Expanded Patch
Vanilla Expanded Furniture
(everything from vanilla expanded)
Harmony
Alpha Animals
Alien Races
Forsakens
Vanilla Factions expanded Settlers
Vanilla Factions expanded Medival
Empire
Faction to Empires
Giddyup core
Giddyup and go
Giddyup Caravan

**Comment by OrionFive** [comment]
Until recently the Locks mod has been on the incompatible list, because exactly what you mentioned happens. I took it off the list, because when I used it, it worked just fine.
But I'm pretty sure that's what causes the problem.

**Comment by OrionFive** [comment]
I've uploaded a new version that hopefully fixes this issue. Please reopen if it still happens

**Comment by CrazyPenguin22** [comment]
Thank you. Appreciate you putting time and effort into this. Will try it out. If I don't report anything back in the next 2-3 days assume everything works fine.
