### ISSUE TITLE
Hospitality causing an issue with Simply Storage

### ISSUE THREAD

**Issue by Silentmatten** [OrionFive/Hospitality#408]
https://gist.github.com/c74df731bb0a28aa6216391a54378d62

i've come across a very unique bug where hospitality has essentially disabled my ability to allow/forbid things on my simply storage mod items. Before rimworld core got updated, everything was working fine, but after the update the function broke.

If i disable the hospitality mod though, everything works as it should. Is this a new compatability issue?

**Comment by OrionFive** [comment]
Can you test with a new colony? Just turn on God mode and quickly set up some beds and fridges to see what happens.
If it the problem doesn't happen, your savegame is broken. There are a couple of indicators that would suggest that.
If the problem does happen, we have to keep looking. I recommend deleting mods that are disabled and not up to date. Especially 1.0 mods are known to cause problems, even when disabled.

**Comment by Silentmatten** [comment]
On a new colony it worked, is there any methods i can try to fix my save game?

**Comment by OrionFive** [comment]
If you haven't yet, make a backup of your savegame.

Your log lists the following issues when loading the game:

> Could not load reference to Verse.ResearchProjectDef named TechHyperweaveCrafting
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Null key while loading dictionary of Verse.ResearchProjectDef and System.Single. label=progress
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Could not find think node with key 1640241512
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Could not find think node with key 1640241512
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Could not find think node with key -154852687
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Could not find think node with key -154852687
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Could not find think node with key 1640241512
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Two power nets on the same cell (136, 189). First transmitters: Power conduit and Power conduit.
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Two power nets on the same cell (137, 189). First transmitters: Power conduit and Power conduit.
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Two power nets on the same cell (123, 186). First transmitters: Power conduit and Power conduit.
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Two power nets on the same cell (122, 186). First transmitters: Power conduit and Power conduit.
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

You can ignore the filenames, they're useless. But each warning or error is an indication of something that could be the cause. 
You can find your savegame somewhere in %appdata% ludeon studios or so. It can be edited with notepad (not recommended), or notepad++, or visual studio code. Whatever floats your boat.

What I would try is to use the find function to see if you can find back the line in question. Usually there is some correspondence, like the name, key or coordinate. 
Then remove the element that you think causes it. Save the file. Load it in RimWorld (no restart required). See if the warning / error disappears. If not, go back, undo, and look further. Or maybe you removed it wrong.

Sorry, but that's the best I have. You can and should also Google the messages and see if you can get help on the RimWorld discord if you can't fix one of them yourself. 

Fixing savegames is tricky stuff. Good luck!

**Comment by Silentmatten** [comment]
i found that it was 
> Could not find think node with key 1640241512
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Apparently the mod rimjobworld was causing an issue with guests who were trying to take care of their sex need with certain methods of doing it. Idk if that information helps at all, but deleting everything that had "1640241512" in it fixed the problem

**Comment by OrionFive** [comment]
Hmm, when does it ever not cause issues.

Great that you found it! And thanks for reporting the solution.
