### ISSUE TITLE
"Visitors from <faction> are leaving" spam

### ISSUE THREAD

**Issue by BingersInBingland** [OrionFive/Hospitality#414]
I had a visitor that finished their stay, gave a few gifts, and left. But then they wandered around the centre of my base and wouldn't leave. The notification in the top left then spammed "Visitors from <faction> are leaving' with a contact beep. The spam persists after saving and loading, and restarting the game. I managed to fight, capture, and release the guest and I can't find them on the map.

It;s making the game almost unplayable.

I've had the hospitality mod loaded since before I started this map.

Log file:
https://gist.github.com/7175585f44d72831587de52cf8781b2c

Screenshot:
https://steamcommunity.com/sharedfiles/filedetails/?id=2106847431

Order of events as I remember them:

- The visitor party was a single guest
- Guest was an android from an android faction
- After their stay the left 3 or 4 gifts, and were very happy
- Their faction became an ally
- The visitor then hung around the middle of my base. selecting them it said they were Wandering
- I tried trading with them and completed a successful trade
- I tried sending them away on their guest tab after selecting them, nothing happened
- I made a new area around the edge of the map to set that as their allowed area, nothing happened
- Their faction relation went from ally down to hostile eventually
- I attacked the guest, captured them, and released them
- I forced a colonist to release them and they were taken to outside the home area.
- I didn't watch them exit the map, but I can't find them on the map and mousing over the notification spam no longer brings up the large white arrow to show where they are.
- I tried saving and loading, and also exiting and restart the game.
- I tried moving the hospitality mod to the very end of the modlist (it was already pretty low)

Thanks in advance for helping, and also thanks for such an awesome mod.

**Comment by OrionFive** [comment]
Thanks for the thorough report.

Unfortunately, it looks like your savegame is pretty busted. In fact I've never seen so many different errors in one single log before. 
Did you by any chance remove mods? That's not supported by RimWorld and creates busted savegames like yours. It also looks like the most plausible reason for Hospitality breaking. At some point it wrote data (maybe a faction) into its event queue, but whatever it was is not available anymore. 
If you want to remedy the situation, load the game again from before it broke, with all the mods you ever used on that map. 

Please let me know if there's anything else I can do for you.

**Comment by BingersInBingland** [comment]
Thanks @OrionFive 

Yeah I got carried away with adding and removing mods. I also had an issue where I'd basically stopped getting quests and only ever the initial Royal Quest and none others. I've got no idea which ones I removed over the course of the last month.

> Please let me know if there's anything else I can do for you.

Press F to pay respects to my beloved colony.

At least now I know which mods I like and don't like.

Feel free to remove this bug report as it looks like it's not really a bug with your mod.

Cheers

Bingers

**Comment by OrionFive** [comment]
Adding mods is usually no issue. But when removing, you should only remove QOL mods, those are usually fine. Otherwise start a new game.
I wish there was a disclaimer in RimWorld: "You're trying to remove a mod midgame. Hereby you forfeit all your rights on support from modders or devs. Are you certain?"

Haha, that's be great XD
