### ISSUE TITLE
Hospitality: Failed to read royalty titles

### ISSUE THREAD

**Issue by MrShadex** [OrionFive/Hospitality#422]
**Describe the bug**
Hospitality is messing up with another mod and breaking events so I don't get quests or raids.

**To Reproduce**
1. Have the same mods I do installed.
2. Play the game, or use dev tool to progress story teller days
3. Open debug tool.
4. When an event would happen it shows a bug that has hospitality and royalty in the name

**Console log**
https://gist.github.com/HugsLibRecordKeeper/cc34781ae2e27e0999a0299157b73729

**Error stacktrace**
Failed to read royalty titles or their required apparel. This means you are using a mod that changes these and broke them.
System.NullReferenceException: Object reference not set to an instance of an object
  at Hospitality.ItemUtility+<>c__DisplayClass2_0.<IsRequiredByRoyalty>b__0 (RimWorld.RoyalTitle title) [0x00000] in <e0fec532deb04859a225f5d58b1534f8>:0 
  at System.Collections.Generic.List`1[T].FindIndex (System.Int32 startIndex, System.Int32 count, System.Predicate`1[T] match) [0x0003b] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Collections.Generic.List`1[T].FindIndex (System.Predicate`1[T] match) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Verse.GenCollection.Any[T] (System.Collections.Generic.List`1[T] list, System.Predicate`1[T] predicate) [0x00000] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
  at Hospitality.ItemUtility.IsRequiredByRoyalty (Verse.Pawn pawn, Verse.ThingDef apparelDef) [0x00023] in <e0fec532deb04859a225f5d58b1534f8>:0 
Verse.Log:Error(String, Boolean)
Hospitality.ItemUtility:IsRequiredByRoyalty(Pawn, ThingDef)
Hospitality.ItemUtility:PocketHeadgear(Pawn)
Hospitality.GuestUtility:Arrive(Pawn)
Hospitality.LordToil_VisitPoint:Arrive()
Hospitality.LordToil_VisitPoint:Init()
Verse.AI.Group.Lord:GotoToil(LordToil)
Verse.AI.Group.Transition:Execute(Lord)
Verse.AI.Group.Transition:CheckSignal(Lord, TriggerSignal)
Verse.AI.Group.Lord:CheckTransitionOnSignal(TriggerSignal)
Verse.AI.Group.Lord:ReceiveMemo(String)
Hospitality.LordToil_CustomTravel:LordToilTick()
Verse.AI.Group.Lord:LordTick()
Verse.AI.Group.LordManager:LordManagerTick()
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Screenshots**

![image](https://user-images.githubusercontent.com/66928266/84609516-47666e00-ae85-11ea-8098-a685342b7729.png)

**Comment by OrionFive** [comment]
I quickly took a peek at the problem. That error does not happen when an event would happen, but when guests come in range of your base. It's most likely unrelated.

**Comment by MrShadex** [comment]
> I quickly took a peek at the problem. That error does not happen when an event would happen, but when guests come in range of your base. It's most likely unrelated.

So is there another thing that should pop up I should look for? That's the only thing that would pop up. Still events and raids happen without Hostpitality, but with it on I get nothing.

**Comment by OrionFive** [comment]
I would hope that you get a different error when another event should happen. What happens when you trigger raids manually via the dev tools?

**Comment by MrShadex** [comment]
They spawn in and work as normal, I tested that out. But I didn't check the error logs, so I'll test that out tomorrow for you.

**Comment by OrionFive** [comment]
I finally got around to digging through your logs. Are you absolutely certain all storyteller events work without Hospitality?
Because when you load your game, you have more errors than you can shake a stick at. 
Pretty much all of them from removing mods midgame. Which is a first order RimWorld sin that can not be undone once saved. 

I'm pretty certain when you start a new game it will go perfectly fine.

**Comment by OrionFive** [comment]
I think I fixed this one and it should work again. Please reopen it if it still happens. Also restart Steam to make sure you get the update.
