### ISSUE TITLE
Hospitality: Store front

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#430]
Maybe as a submod?

A workbench that has to be manned where guests can shop. Higher prices, based on seller's skill.

**Comment by neekode** [comment]
+1 on this. thanks so much for your work btw your mods are staples in how i play. now building out a AIO shopping, hotel, and dining resort-y colony and expanded merchant functionality would make it literally perfect!

**Comment by OrionFive** [comment]
The groundwork for this exists, but I can't find the time to actually make it. I was thinking about commissioning it with the Patreon money, but that's become a lot less while expenses are rising.
I haven't played RimWorld myself for years, so there isn't really any incentive anymore for me to spend days or weeks of free time, or large amounts of money.

I'm glad you enjoy the mods I've made, but probably there won't be any new features unless something changes.

**Comment by neekode** [comment]
ahhhh makes sense, well thanks for the reply! hope the other stuff you're up to is successful and fun

**Comment by OrionFive** [comment]
This is a thing now, thanks to Adamas.
