### ISSUE TITLE
Hospitality: Pet store

### ISSUE THREAD

**Issue by Lolsworth** [OrionFive/Hospitality#439]
Either a separate area or added to the shop area.  Allow animals assigned to the area can be bought by guests.  Maybe they would prefer animals that have more frequent nuzzle intervals like cats, dogs and rabbits.

**Comment by OrionFive** [comment]
It's a cool idea, but I'm afraid I have to decline it for technical reasons since I can't support guest groups with slaves and/or animals. 
The only way it would work is to fake it and destroy the animal and spawn an animal box in their inventory. Not sure if that has the same charm.

**Comment by OrionFive** [comment]
I'm gonna leave this here for now anyway. If there's a lot of interest in this I might consider it.
