### ISSUE TITLE
Guests not using rec items

### ISSUE THREAD

**Issue by KarlKillsPeople** [OrionFive/Hospitality#441]
My guests are wandering in, refusing to use rec items, then storming out angrily when they reach critical boredom. Also I can't seem to find the ability/means to make a shopping center or recruit anyone even if I wanted to. Overall just seems to not be working too well.

**Console log**
https://gist.github.com/457651744f312ef13f3098fd913202c7

**Error stacktrace**
Don't know how to find this

**Comment by OrionFive** [comment]
As you can see from the first exception (line 222) it's an error in SimplyMoreBridges.

**Comment by OrionFive** [comment]
As a side note, this exception can happen when invalid assemblies are loaded. That could be 1.0 mods that never were updated, or duplicate assemblies with different version...

**Comment by KarlKillsPeople** [comment]
I see, thank you. I have the simply more bridges AND the SMB fix installed, because the base mod was left in 1.0. Should I reinstall both or...?

**Comment by KarlKillsPeople** [comment]
I see, thank you. I have the simply more bridges AND the SMB fix installed, because the base mod was left in 1.0. Should I reinstall both or...?

**Comment by OrionFive** [comment]
I have no idea. You'll have to ask that at Simply More Bridges.
