### ISSUE TITLE
Hospitality: incapacitated guests lose lodging

### ISSUE THREAD

**Issue by meldra** [OrionFive/Hospitality#443]
**Describe the bug**
I had a new attacker incapacitate several existing guests. The guests promptly lost their guest bed allocations and could not be rescued until I set those beds to be medical beds. They also appear to have turned from purple to blue name plates but i'm not exactly clear on when but i'll try get an approximate reproduction of this for a better trace.

**To Reproduce**
This is going to take some time to reproduce but I still have an autosave from after i got them to the medical beds... but that might be too late. Timeline was basically:

Bunch of visitors arrive, fill up all guest beds. 2 colonists with beds. No spare beds and I didn't think to make sleeping spots.

Attacker arrives, mauls the crap out of 3 guests, 2 of them (and one colonist) become incapacitated.

Can rescue colonist to assigned colonist bed but can't rescue guests to their (still name badged iirc, but not 100% sure anymore) guest beds.

Toggle beds to guest off then medical on and can rescue visitors. Not sure when name badges of guest changed from guest purple to visitor blue as I lost the save beforehand.

Toggling other guest beds off does not make them swap from guest to visitor.

**Console log**
https://gist.github.com/HugsLibRecordKeeper/d89aa9169551ccec616ffcfa7d6d2315

**Comment by OrionFive** [comment]
It could be that there isn't much I can do about this. Once downed, guests aren't guests anymore and follow different rules. When they recover they become guests again.
Currently, guest beds can't be used for medical purposes. And indeed toggling a guest bed will clear the reservation, since it stops being a guest bed.
I'm not sure which part here needs fixing, or even which part can be fixed at all.

**Comment by meldra** [comment]
No problem if you can't fix it within the framework you have available. Just wasn't sure it was supposed to happen like that so figured I'd check :)
