### ISSUE TITLE
MainButtonDef defines the same field twice: iconPath.

### ISSUE THREAD

**Issue by marceel** [OrionFive/Hospitality#445]
Hi, 

Can this be fixed from your side?
 It's likely a incompatibility between Hospitality and Vanilla Textures Expanded - Mod Expansion.

XML RimWorld.MainButtonDef defines the same field twice: iconPath.

Field contents: UI/Buttons/MainButtons/IconGuests.

Whole XML:

<MainButtonDef>
    <defName>Guests</defName>
    <label>guests</label>
    <description>List guests in the area and manage hospitality.</description>
    <tabWindowClass>Hospitality.MainTab.MainTabWindow_Hospitality</tabWindowClass>
    <order>53</order>
    <iconPath>UI/Buttons/MainButtons/IconHospitality</iconPath>
    <iconPath>UI/Buttons/MainButtons/IconGuests</iconPath>
</MainButtonDef>
Verse.Log:Error(String, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:DMD<DMD<DefFromNode_Patch3>?-649417856::DefFromNode_Patch3>(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:DMD<DMD<ParseAndProcessXML_Patch1>?-1833407232::ParseAndProcessXML_Patch1>(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by OrionFive** [comment]
I know. They have to make their code conditional instead of just plopping in content.
I can't fix this properly from my end, sorry.
