### ISSUE TITLE
Hospitality: Bestowing ceremony stuck because bestower was currently a guest.

### ISSUE THREAD

**Issue by kembial** [OrionFive/Hospitality#455]
**Describe the bug**
Royalty: Bestower shows up as guest and visits often. Initiating a bestower Quest while the bestower is a Guest makes the empire party unable to leave after the ceremony.

**To Reproduce**
1. Bestower is part of a guest party.
2. Gain enough honor for a title ceremony.
3. Call ceremony shuttle while Bestower is a guest.
4. Empire soldiers arrive in shuttle, ceremony completes. No one boards the shuttle. Wandering and passing out on floor. Only interaction is to arrest.

**Console log**
https://gist.github.com/32f7dbe1a1b5a3d5e2b368b64f162012

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2206321742
Dees is Bestower guest. Blue names are shuttle soldiers from title quest.

**Comment by kembial** [comment]
Shuttle outside of allowed guest area.

**Comment by OrionFive** [comment]
This is related to #454. I'll add that special characters won't spawn as guests.
