### ISSUE TITLE
Hospitality: Casino add-on

### ISSUE THREAD

**Issue by Sisyphus15** [OrionFive/Hospitality#456]
Been looking for a Casino mod to pair with Hospitality for a while. Haven't been able to find one, so I started to look into what it would take to build my own mod... one very short and uneventful how to make Rimworld mod's YouTube/Google search later, I figured I better just ask (an expert) if it's something you'd be interested in or already thought of, and decided not to do, or not possible due to some coding issues.

Slots, craps tables, roulette, blackjack etc. I'd imagine, some of the events would naturally be things like guest's winning jackpots (which come directly out of your silver), guest counting cards, high rollers visiting the settlement with enough money to bankrupt you, assuming your pawn has low entertainment skills while manning a table. All while trying to protect your settlement from raids and natural disasters.

After reading the Spacer thread (which I thought was a great idea) on here I'd imagine it could work in much of the same way as far as reputation. As far as balance is concerned I don't feel like it would be unbalanced because you can lose wealth, or perhaps in order to attract a large number of guest you have to offer a large jackpot, that again comes out of your silver pile if won, and might peak the interest of some raiders as well.

I'd be willing to help with the mod but i have no coding experience, you'd have to hold my hand during the process but it is a legitimate offer to help.

**Comment by OrionFive** [comment]
Hey,
Thanks for your interest. I can't afford any side projects at the moment, unfortunately. And what you're describing is weeks or months of work.
So if you want to give it a shot, I won't stand in your way, maybe I can even help out here and there. But I don't have the time to make a real contribution or tutor you. At least not in the foreseeable future. 
You can best contact me on Discord (Orion#6215).
