### ISSUE TITLE
 Dragon's Descent: Incompatible "CompAssignableToPawn_Bed' in comps"

### ISSUE THREAD

**Issue by ottersholdhands** [OrionFive/Hospitality#457]
We have been getting various reports of people using your mod and getting an error of 

_ThingDef DragonNest must have a 'CompAssignableToPawn_Bed' in comps. This is a misconfiguration in Dragon's Descent.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

ThingDef DragonPillow must have a 'CompAssignableToPawn_Bed' in comps. This is a misconfiguration in Dragon's Descent.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)_

This error appears when a dragon egg is hatched in a dragonpillow or dragon nest. 

Our c# wizard in our mod has recommended :

"In Hospitality.DefsUtility.CheckBedDef(), can you change your check of
if (!item2.HasComp(typeof(CompAssignableToPawn_Bed)))

to
if (!item2.HasAssignableCompFrom(typeof(CompAssignableToPawn_Bed)))
Reason:
We have a Comp that is a subclass of CompAssignableToPawn_Bed.
Your check trips on this for no reason.
public class CompAssignableToPawn_Nest : CompAssignableToPawn_Bed {}"

Feel free to contact me on the rimworld discord at Ottersholdhands or on our mod page. Thanks for making such an amazing mod :D!

[](https://gist.github.com/HugsLibRecordKeeper/b5e75e5cefbb6bbc5ae211318bcc2624)

**Comment by OrionFive** [comment]
Good catch. I didn't take that situation into account. I'll include it in the next round of fixes.

**Comment by OrionFive** [comment]
Fixed in next version.
