### ISSUE TITLE
Denser Beds Duping

### ISSUE THREAD

**Issue by DisKorrupt** [OrionFive/Hospitality#460]
While the Denser Beds can be turned into hospitality beds, if you attempt to do so using the Denser Beds' bunk beds, this will not properly delete the original bed but instead will duplicate and spawn more beds on the spot

**Comment by OrionFive** [comment]
Sorry I didn't reply yet. This one must have slipped past me.

**Comment by DisKorrupt** [comment]
No worries, it happens, people get busy with things

**Comment by OrionFive** [comment]
I never got around to fixing this, but I see Denser Beds is a very obscure mod (280 subscribers). Given how long a fix will probably take, I'm afraid to say that my time is better spent elsewhere.
