### ISSUE TITLE
Hospitality: startup error message

### ISSUE THREAD

**Issue by ianmpl** [OrionFive/Hospitality#466]
**Describe the bug**
I have been getting this error message when I am loading the mods (game menu screen startup).

**To Reproduce**
I have been getting this error message when I am loading the mods.

Whole XML:

<MainButtonDef><defName>Guests</defName><label>guests</label><description>List guests in the area and manage hospitality.</description><tabWindowClass>Hospitality.MainTab.MainTabWindow_Hospitality</tabWindowClass><order>53</order><iconPath>UI/Buttons/MainButtons/IconHospitality</iconPath><iconPath>UI/Buttons/MainButtons/IconGuests</iconPath></MainButtonDef>
Verse.Log:Error(String, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:DefFromNode(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
That makes not much sense. I'll need your complete log. On 9/28/20, 00:56 ianmpl <notifications@github.com> wrote:

   
  Describe the bug I have been getting this error message when I am loading the mods (game menu screen startup). 
  To Reproduce I have been getting this error message when I am loading the mods. 
  Whole XML: 
  GuestsguestsList guests in the area and manage hospitality.Hospitality.MainTab.MainTabWindow_Hospitality53UI/Buttons/MainButtons/IconHospitalityUI/Buttons/MainButtons/IconGuests Verse.Log:Error(String, Boolean) Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean) Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean) Verse.DirectXmlLoader:DefFromNode(XmlNode, LoadableXmlAsset) Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2) Verse.LoadedModManager:LoadAllActiveMods() Verse.PlayDataLoader:DoPlayLoad() Verse.PlayDataLoader:LoadAllPlayData(Boolean) Verse.<>c:b__6_1() Verse.LongEventHandler:RunEventFromAnotherThread(Action) Verse.<>c:b__27_0() System.Threading.ThreadHelper:ThreadStart_Context(Object) System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean) System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean) System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object) System.Threading.ThreadHelper:ThreadStart() 
  Fixing bugs takes a lot of time. Please consider becoming a patron to support development.

**Comment by OrionFive** [comment]
Please reopen this when you have more information for me.
