### ISSUE TITLE
Visitors arrived, but they dont appear

### ISSUE THREAD

**Issue by LiMoNaToU** [OrionFive/Hospitality#469]
It happens what it says in the title, but items dont have any description, configs and the visitors arrived neither. It only says "ExampleThingDesc" 
Log: https://gist.github.com/3a389b326f20b5e5c688c8104c1721b4

**Comment by OrionFive** [comment]
Looks like you've removed a mod mid-game. That's not something RimWorld supports. On 10/15/20, 23:46 LiMoNaToU <notifications@github.com> wrote:

   
  It happens what it says in the title, but items dont have any description, configs and the visitors arrived neither. It only says "ExampleThingDesc" Log: https://gist.github.com/3a389b326f20b5e5c688c8104c1721b4
