### ISSUE TITLE
Gastronomy: JobDriver red error after pawn finishes eating ordered meal

### ISSUE THREAD

**Issue by spoden** [OrionFive/Hospitality#478]
**Describe the bug**
JobDriver red error after pawn finishes eating ordered meal

**To Reproduce**
1. Pawn orders food
2. Waiter brings food
3. Pawn finishes eating food 
4. ERROR

**Console log**
https://gist.github.com/HugsLibRecordKeeper/30a78d412b6b76e6c992eb6ccaa89a00

**Error stacktrace**
See screenshot for trace, forgot to copy

**Screenshots**
https://i.imgur.com/xP6gT6E.png

**Comment by OrionFive** [comment]
Thanks. I think I found the problem. Should be fixed next version.
