### ISSUE TITLE
Gastronomy: Random 'Tried to set dining spot' error

### ISSUE THREAD

**Issue by spoden** [OrionFive/Hospitality#479]
**Describe the bug**
If table is placed up against a wall, then red error after waiter takes pawn's order and sets their spot

**To Reproduce**
1. Place table against wall
2. Pawn orders food
3. Waiter sets spot for pawn that just ordered
4. ERROR

**Console log**
https://gist.github.com/HugsLibRecordKeeper/6230c518ef8d122a5b3a770278272636

**Error stacktrace**
See screenshot for trace, forgot to copy

**Screenshots**
https://i.imgur.com/Dk4mke1.png

**Comment by OrionFive** [comment]
This error is a problem, but it's not actually caused by tables set against a wall.

**Comment by OrionFive** [comment]
To be honest, I couldn't nail down yet what exactly does cause this error.

**Comment by OrionFive** [comment]
I made it a warning for now, since players can pretty much ignore this error.

**Comment by spoden** [comment]
Sounds good, thanks for looking into this!
