### ISSUE TITLE
Let only one pawn improve relationship at time

### ISSUE THREAD

**Issue by vezixig** [OrionFive/Hospitality#48]
Currently I'm having three colonists assinged to negotiating. If one of the guests is ready for talking, all of my pawns try to rush and make the same guest happy. If the winner finishes talking to the guest the others instantly stop and return to their normal duties. Would be way better if only one pawn goes talking to a single guest at a time.

**Comment by OrionFive** [comment]
You're right. Something goes wrong with reserving the target. I'll see what I can do. Thanks for reporting.

**Comment by OrionFive** [comment]
This should be fixed again.
