### ISSUE TITLE
Orions Hospitality: Game crashes immediately after loading map on a new save 

### ISSUE THREAD

**Issue by Sloppybroth789** [OrionFive/Hospitality#488]
**Describe the bug**
Game crashed right after selecting characters and right after generating map. I mean the map loads and that message saying "you awake from your sleep after hearing alarms..." but right after that the game crashes and unity crash loader comes and closes the game i was unable to extract the log file with CTRL-F12 but managed to find the player log from app data roaming.
I hope it might prove useful to you to solve my problem.
Thanks in Advance 

**To Reproduce**
1. Start new colony
2. Select seed and generate planet
3. Select pawns and press ready
4. Loading scree showing generating map comes and right after i see a glimpse of the map the game crashes and unity crash support comes ip

**Console [log**]
 
[Player.log](https://github.com/OrionFive/Hospitality/files/5558007/Player.log)

**Comment by OrionFive** [comment]
(un/fortunately) you're the only one this happens to. I don't have enough information to tell you more (I also need a ctrl-f12 log from before it happens - after would be better, but before is better than not having it). 
Usually something like this points at a mod conflict or a malfunctioning mod in your setup (e.g. a disabled mod in your downloads folder).
Please reopen this when you have more information for me.
