### ISSUE TITLE
Hospitality Suggestion

### ISSUE THREAD

**Issue by MeatBeatMarv** [OrionFive/Hospitality#491]
I want to apologize in advance if this isn't the proper place for this.  I am unfamiliar with github, and the steam workshop page said github is where one should make suggestions.

I suggest a button available to player caravans when they arrive at friendly settlements to stay there as guests.  Instead of generating a map/building for the player caravan, this would just let the carvan pay a small ammount of silver for a rest boos, and for their food/recreation needs to be handled by the host settlement.  Functionally, this would just fill the food/recreation needs without taking anything from caravan inventory aside from the silver cost mentioned earlier.  The better your relations with a faction, the cheaper your stay could be.

**Comment by OrionFive** [comment]
This is indeed the right place. It's a great idea, however, I don't see any reason why it should be part of Hospitality. It would work just fine as a standalone mod. 
So actually what you're looking for is a new mod ;)
