### ISSUE TITLE
Simple sidearms: guests equip my items as sidearms

### ISSUE THREAD

**Issue by kacpeG** [OrionFive/Hospitality#496]
Guests sometimes equip everything that can be used as a weapon, as a sidearm: weapons, beer, and its no matter where this item is somewhere on the floor, or in zones or in the shop zone.

But when they equip beer or logs as sidearm they equip them few at a time and then stop for a while and do it again, they can equip them even above their mass capacity, and at the time they equip, i get this in log:

Slick started 10 jobs in 10 ticks. List: (ReequipSecondary (Job_9714370) A=Thing_Beer3673047) (Wait_MaintainPosture (Job_9714371)) , (ReequipSecondary (Job_9714375) A=Thing_Beer3673047) (Wait_MaintainPosture (Job_9714376)) , (ReequipSecondary (Job_9714378) A=Thing_Beer3673047) (Wait_MaintainPosture (Job_9714379)) , (ReequipSecondary (Job_9714382) A=Thing_Beer3673047) (Wait_MaintainPosture (Job_9714383)) , (ReequipSecondary (Job_9714385) A=Thing_Beer3673047) (Wait_MaintainPosture (Job_9714386)) curDriver=JobDriver_WaitMaintainPosture (toilIndex=0) curJob=(Wait_MaintainPosture (Job_9714386))

Verse.Log:Error(String, Boolean)

Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)

Verse.AI.Pawn_JobTracker:FinalizeTick()

Verse.AI.Pawn_JobTracker:JobTrackerTick()

Verse.Pawn:DMD<DMD<Tick_Patch1>?-1855585536::Tick_Patch1>(Pawn)

Verse.TickList:Tick()

Verse.TickManager:DoSingleTick()

Verse.TickManager:TickManagerUpdate()

Verse.Game:UpdatePlay()

Verse.Root_Play:Update()

**Comment by OrionFive** [comment]
I'm sorry to say, but this is not the fault of Hospitality.

Guests perform many colony jobs when they're satisfied. So if equipping anything as a sidearm is a colony job, they will do that as well. It's up to the mod adding sidearms to make sure only sensible and owned sidearms are equipped.
