### ISSUE TITLE
Gastronomy: When recruiting guests, pending orders get stuck

### ISSUE THREAD

**Issue by NotherGithubAccount** [OrionFive/Hospitality#504]
I have an order pending (needs serving) from one of my colonists. Colonists are not allowed to order, but that colonist was recruited from guests.

I did not observe it, but assume the guest had just ordered when he was recruited.

**Comment by NotherGithubAccount** [comment]
... this also seems to happen if the serving gets interrupted in other ways. Had a waiter dragged away a few times by the leadership mod's school task, and at some stage the guest pulled out some pemmican and the order stayed in undelivered status.

**Comment by OrionFive** [comment]
Fixed in next version.
