### ISSUE TITLE
Gastronomy: Pawn stuck by waitig beside the table.

### ISSUE THREAD

**Issue by QQLQ** [OrionFive/Hospitality#506]
One of my pawns is stuck by the table and there pop out a large amount of red error logs. Meanwhile other pawns seem alright. Tried cancel all of this pawn's work and the problem remains. Also tried reorder this mod and put in different order.

https://gist.github.com/26afd436cabfebe4fbd1b20b46548fa7

**Comment by OrionFive** [comment]
Please download this version: https://github.com/OrionFive/Gastronomy/archive/master.zip
and try again. 

If it still doesn’t work, please send me a new log.
