### ISSUE TITLE
A Bug, or I must be amazing at hospitality....

### ISSUE THREAD

**Issue by zero127** [OrionFive/Hospitality#51]
Its probably something funky with my lot of mods, but i seem to be able to do no wrong with guests. This was not the case last time i did an a16 playthrough a couple weeks ago (I had a very nice environment, and averaged between 70-100%). The only new mod additions are Vegtable Garden, and a couple faction/alien races (Asari, Jaffa)? And it does seem to be the new factions visiting most of the time, rarely humans. Could be a possible incompatibility with alien races? Anyway, happy to help further if you're interested or want the mod list. I'm keeperoflenneth on Steam, same icon you see here. This mod is literally mandatory to my game from now on, its so good, so if i can make it better by sorting this out, i'd like to help in any way i can.

But it just seemed weird that i 100% the visit 100% of the time, so i figured i'd ask.

**Comment by OrionFive** [comment]
Hmm. This one will be very hard to track down. Although I have the feeling that since recently I'm also getting too high scores. I'll have to see if I can reproduce the issue.

**Comment by zero127** [comment]
If you need anything from me holler, happy to assist.

**Comment by OrionFive** [comment]
I think I found the issue. Entertaining guests was too effective. I'll roll out the update soon. 

About the races: It depends on the distance of their bases how frequent different factions come by.
