### ISSUE TITLE
Hospitality - Incompatibility with Where's My Weapon

### ISSUE THREAD

**Issue by Hamartio** [OrionFive/Hospitality#513]
This new feature isn't compatible with the behavior of Where's My Weapon (possibly Simple Sidearms too). All pawns, not just friendlies, will rarely drop their weapon when downed but usually will once brought to a bed, causing them to forget their loadout and not automatically seek their weapon once back up.

**Comment by OrionFive** [comment]
Hm, I'll look into it.

**Comment by OrionFive** [comment]
I've created a fix for the problem. It does
- colonists are not affected by the fix
- when put to bed, pawns don't drop their weapon

Can you [try the fix](https://github.com/OrionFive/Hospitality/archive/develop.zip) and let me know if that solves the issue for you?

**Comment by Hamartio** [comment]
Sorry for the delay. I just tried turning it back on, downed a pawn with dev mode, and same behavior as before once they were brought to a bed.

**Comment by Hamartio** [comment]
My bad - didn't see that fix was a special download. I've located my 294100 folder for rimworld mods, but I've 171 in there, and I'm not seeing much telling me what's what. Should I just toss it in the 294100 and unsub from the main hospitality so they don't conflict?

**Comment by OrionFive** [comment]
Oh no, never do that.It goes into the mods subfolder of RimWorld.If you use the mod manager mod, you can then switch between using the workshop version and this one. On 1/23/21, 07:11 Hamartio <notifications@github.com> wrote:

   
  My bad - didn't see that fix was a special download. I've located my 294100 folder for rimworld mods, but I've 171 in there, and I'm not seeing much telling me what's what. Should I just toss it in the 294100 and unsub from the main hospitality so they don't conflict?

**Comment by Hamartio** [comment]
Awesome - looks like the fix works. You do good work, man.

**Comment by OrionFive** [comment]
Thanks. I'll roll it out to steam with the next update. So that might take a while. On 1/24/21, 00:41 Hamartio <notifications@github.com> wrote:

   
  Awesome - looks like the fix works. You do good work, man.
