### ISSUE TITLE
Hospitality: TPS drop in CustomTravel

### ISSUE THREAD

**Issue by skyarkhangel** [OrionFive/Hospitality#516]
Hello, Orion :) Possible reason: Every 205 tick, Every pawn in group check in one tick (moment) CanReach at any distance. Is it necessary to check reachability constantly?
https://github.com/OrionFive/Hospitality/blob/e72657a49171248bfca536729e3e1e1a98cebb21/Source/Source/LordToil_CustomTravel.cs#L55

![Screenshot_28](https://user-images.githubusercontent.com/13723006/105639434-5a183b00-5e89-11eb-9bfb-6739988c0617.png)

**Comment by skyarkhangel** [comment]
Vanilla TryFindTravelDestFrom already check the reachability to destination cell. The best solution, is almost remove. But if you need this check, try to make it in a limit distance. Like, at first try to check distance between pawn and dest. cell and then if it in 50-60 cells check reachability. Vanilla CanReach using Rimworld pathfinder which is not very fast and the greater the distance between the targets, the greater the impact on the game.
https://github.com/OrionFive/Hospitality/blob/e72657a49171248bfca536729e3e1e1a98cebb21/Source/Source/LordToil_CustomTravel.cs#L44

**Comment by OrionFive** [comment]
There's a distance check already that happens before CanReach:
https://github.com/OrionFive/Hospitality/blob/e72657a49171248bfca536729e3e1e1a98cebb21/Source/Source/LordToil_CustomTravel.cs#L55

There can be a wall between the destination and the pawn (suddenly), so only checking in Init is not enough.

**Comment by OrionFive** [comment]
I'm now caching the arrived pawns so they don't check again, and I'm spreading out the pawn checks over multiple ticks, so there are no spikes. Included in the next version.
