### ISSUE TITLE
Gastronomy: Pawn will be stuck at standing when they couldn't find a chair near the table mark as dining

### ISSUE THREAD

**Issue by practicalproblems23** [OrionFive/Hospitality#517]
**Describe the bug**
Pawn will be stuck at standing if there a table mark for dining doesn't have a chair nearby.
**To Reproduce**
1) Mark a table with no chair good for dining
2) Wait for a pawn to get hungry
3) Pawn get stuck at standing mode 

**Console log**
https://gist.github.com/HugsLibRecordKeeper/e9e27886a78b13fa6a9a7bb02c34bc3e

**Error stacktrace**
<color=#D09B61FF>Zoya</color> could not find a chair around (143, 0, 202).
Verse.Log:Message(String, Boolean)
Gastronomy.Dining.<>c__DisplayClass0_0:<GoToDineSpot>b__0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:Verse.AI.JobDriver.ReadyForNextToil_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1(Pawn_JobTracker, JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0(Pawn_JobTracker)
Verse.Pawn:Verse.Pawn.Tick_Patch1(Pawn)
Verse.TickList:Verse.TickList.Tick_Patch0(TickList)
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch0(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Verse.Root_Play.Update_Patch0(Root_Play)

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

![image](https://user-images.githubusercontent.com/78232228/106320012-45002b00-6240-11eb-8e42-e247aa95a692.png)

**Comment by OrionFive** [comment]
Thanks for reporting, great catch!

**Comment by OrionFive** [comment]
Should be fixed in next version. Please reopen if it persists in 1.2.6.
