### ISSUE TITLE
Hospitality: Guests come for medical operations

### ISSUE THREAD

**Issue by Vergathos** [OrionFive/Hospitality#519]
Perhaps add an event or visitors in general who come seeking medical treatment?

An event may work, perhaps a quest, or even the player being able to offer a visitor a surgical operation or prescription to fix their asthma, missing or hindered limbs, addictions, or simply installing a joy-wire.

These operations or clinical visits can be done for either silver and/or faction goodwill.
In order to keep things compatible, the silver/goodwill you can get from these actions could be a percent of the value of the item being installed/given. This may even be able to be made adjustable in a mod menu.

As a quick example, if we used the vanilla Bionic arm valued at 1030 silver, You could have the mod charge the visitor %10 value in silver for the operation, which would be 103 silver, then take a further %10 from the silver charged (103) as the goodwill gained (10.3) from the visit. A mod menu would ideally allow one to change both percent rates, change whether one wanted silver, goodwill, or both as a reward, set a max number of visitors per group asking for medical attention, as well as a max reward limit for those who want some extra balancing capabilities.

I do not know if fractions can exist in goodwill values so rounding it down or to the nearest whole number would probably be best.

**Comment by OrionFive** [comment]
This is quite some work to implement. Maybe I'll get around to it one day.

**Comment by OrionFive** [comment]
What you're writing in the second sentence is the biggest problem, actually. If it's a quest, it's out of scope for this mod and should be a stand-alone mod. 
With just offering operations it's hard to tell if the player is harvesting organs or stealing implants or actually doing something for the person.
So I have to come up with a whole system for how guests want fixes (and where is the prosthetic coming from?). So yeah. A quest would actually work best, but then that's not for Hospitality anymore.

**Comment by Vergathos** [comment]
I hadn't thought of it like that nor did I know the game engine made it difficult to detect an operation type. Perhaps a solution would be to detect the amount a body function Improved? On the back-end, when loading the game, the mod could detect prosthetics and other related items and compare and contrast the before and after stats of the patient? 

The thought process that sparked this idea from me was a pawn visiting with heart and kidney problems that was vomiting everywhere. Since my cleaner was running all over the place I thought it would be pretty neat if I could help the guest by installing some synthetic organs to fix the issue.

**Comment by OrionFive** [comment]
Yeah, you could probably do some smart stuff to check if the person's stats get better or worse. You could probably still replace a better prosthetic with a worse one and gain the favor. And you can't do the check immediately after the operation either, since then the anesthetics are still in effect.
To be honest, this one isn't for me. Maybe someone will make a proper quest for it some day.
