### ISSUE TITLE
Hospitality: Happy Guests not granting faction relations improvement anymore

### ISSUE THREAD

**Issue by log163** [OrionFive/Hospitality#521]
**Describe the bug**
the last couple sessions in my colony guests leaving happy have stopped giving me positive relations with thier faction

**To Reproduce**
1. Have guests
2. Let them leave with score between 80-100
3. no faction relation improvment

**Console log**
https://gist.github.com/c560dcfcd677f339ab5ecf56d385b671

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```
no error in log

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
You got hundreds of errors from other mods. I can't find the incident you're referring to in the log. Are you sure it happened when you created the log?

**Comment by log163** [comment]
Yes, the log was created at the end of a full session which is when I noticed it happening, theirs errors at the top of the log about mods that aren’t even loaded and the errors about stuff not being deep saved are actually equipment on guests, the drug policy errors happen when guests buy chocolate or chocolate eggs, the comp colorable is between Polaris core and change dresser mods and harmless, the tried to destroy already destroyed item has to do with SAL machines in project rim factory trying to do a bill when it doesn’t have enough ingredients, and the thing about guest beds remove hediff bedroom is about guests that aren’t their anymore? I think? And the spam at the end is I have no idea

**Comment by OrionFive** [comment]
Well, I'm not seeing anything that would indicate it went wrong.But just because your game doesn't crash to desktop immediately doesn't mean errors are harmless. This is exactly the kind of thing that happens.But maybe your Hospitality rating just always matched the faction relationship, in which case nothing happens.

**Comment by log163** [comment]
Hmm, the only one still in my log says they left with a score of 86, and then later it says I traded with them and it changed from 71 to 79, but it was a caravan I requested so the numbers do match

edit: ya sorry for bothering you with this, I am getting faction points it seems, it just stopped telling me the +/- change when they leave which I’m sure it used to but, o well. Thanks for helping me

**Comment by OrionFive** [comment]
Ah yes, I removed that a few years ago.
