### ISSUE TITLE
Hospitality: Guests should only leave during the day

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#525]
So the player has a chance to recover their mood before they go.

**Comment by ChristinaJMeakim** [comment]
![image](https://user-images.githubusercontent.com/62406602/113867696-dd54e780-977c-11eb-9c62-287edff8a635.png)

Not sure if this would be a separate issue or if it would be part of this one, but it seems like guests rest for extended periods of time even when they're not tired and despite being starving.

**Comment by OrionFive** [comment]
> Not sure if this would be a separate issue or if it would be part of this one, but it seems like guests rest for extended periods of time even when they're not tired and despite being starving.

Yeah, that's unrelated and a mod conflict on your end.

**Comment by OrionFive** [comment]
Added to next version.
