### ISSUE TITLE
Hospitality Mod : Guests wake up and are stuck in place, talk to each other but don't move anywhere

### ISSUE THREAD

**Issue by krismom1** [OrionFive/Hospitality#526]
**Describe the bug**

A group of 9 guests arrived. I have 7 guest beds so 7 of them took the beds and the other two passed on the dinning room floor. I installed 2 bedrolls for the other 2 for later.
The message "No Guest Beds x9" was appearing and all guests had the "No guests beds" debuff.
In the morning, all guests woke up and were stuck in place. They still interacted with each other, tried to get their food out to eat it (and were unsuccessful, leading to increasing piles of food) but couldn't move or do anything else.

**To Reproduce**
N/A

**Console log**
I'm sorry but Ctrl-F12 did not give me a link, anything plus f12 adjusts my brightness (laptop) and shift-F12 takes a screenshot. 

**Error stacktrace**
could not access log file

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

![Guestsfrozen](https://user-images.githubusercontent.com/80128403/110171406-abd9ac80-7dc9-11eb-8190-53c13cfb45f9.png)

Thank you for taking a look! and thank you for this Mod, it has added so much fun to the game and I promote it on my youtube channel with a link to the workshop page. :)

I have done the Unsub/Resub on the Mod (Steam workshop), have rearranged my Modlist (the only Mod underneath Hospitality is SoftWarmBeds).

Oddly enough, I had a weird problem a week ago and ended up just giving up that save and starting a new colony. The Guest beds had turned into weird images that could not be interacted with or moved (grey boxes). I'll attach a pic of that problem in case they are related.

![Guestbedsweird](https://user-images.githubusercontent.com/80128403/110171965-7c776f80-7dca-11eb-863c-c06facabb72d.png)

I'll attach my Mod list below. I haven't messed with any of them recently except for uninstalling Map reroll once I have my map figured out. But I did notice the Dubs Bad Hygiene Mod updated recently to add a couple new features so I wonder if that had an effect? Just wanted to make sure to report this in case it was happening to others too.

Thanks,
Krismom

(core)
(royalty)
Harmony
HugsLib
EdB Prepare Carefully
Fluffy Breakdown
Smart Medicine
Dismiss Trader
Underground Power Cables
No Mech Raids
Jobs of Opportunity
Run and Gun
Hospitality
Musical Instruments
Vanilla Expanded Framework
Vanilla Furniture
Vanilla Cooking
Vanilla Fishing
Vanilla Apparel
Vanilla Animals – Cats/Dogs
Vanilla Animals – Arid Shrubland
Vanilla Animals – Extreme Desert
Vanilla Animals – Boreal Forrest
Vanilla Animals – Tropical Rainforest
Vanilla Animals – Tropical Swamp
Vanilla Animals –Australia
Vanilla Plants Expanded
Soft Warm Beds
Night Lights
No sympathy for prisoners
Glass & Lights
Camera +
Graphics Settings +
Jewelry
Simple Stockpile presets
HC Animal
Minify Everything
More Floors
Rimsenal Rimhair
Tilled Soil
Colony Manager
Pharmacist
Avoid Friendly Fire
Snap Out!
Dubs Bad Hygiene
CM Colony Manager
Doormats
Bionic icons
Stack XXL
Show hair with hats
Trading Spot
Heatmap
Better Pawl Control
Replace Stuff
Blueprints
Interaction Bubbles
RimFridge
Set up camp
Wall Light
Complex jobs
Smarter construction
RimWriter
Dormitories, not barracks
LWM’s Deep storage
Smart Speed
Outfitted
Use Bedrolls
Simple Sidearms
Share the load
Room Food
More planning
Meals on Wheels
TD Enhancement Pack
Everybody Gets One
Don’t block door
Houseplants
Labels on floor
No power wires

**Comment by OrionFive** [comment]
That's a lot of mods that could potentially conflict. But without the console log, I can't help you. In the options you should be able to turn on developer mode. Then you can open the console with the key above tab on your keyboard (usually). There's a green "share" button in the lower left corner of the console. That should also give you a link you can post here. Do note that if you just load that game now, the damage is probably already done and the content of the console will be misleading. Important is the error that happened when the guests or beds broke in the first place. 

Please reopen when you have a log.

**Comment by krismom1** [comment]
Thank you for the additional instructions about how to access the log!

I captured the log the next time there was an issue with Guests. Here's the link:

https://gist.github.com/HugsLibRecordKeeper/a07b1ce14f75b7558db13a467454eb25

Thanks so much!

**Comment by OrionFive** [comment]
And what was the issue?I can see there's a reference to a group missing. That can cause issues. But it probably happened in a previous session, so I don't know what caused it.
