### ISSUE TITLE
Bug(?) Report - Arresting Guests

### ISSUE THREAD

**Issue by CitatusLingua** [OrionFive/Hospitality#53]
Copy/Paste from the discussion on the Steam Workshop:

"So, I ran into something wierd.
Apparently, trying to arrest a Guest causes a random different guest to be arrested instead. They just drop what they had and become a prisoner; they don't even try to escape - and as long as you don't try to arrest the WHOLE group, the faction doesn't seem to mind either.
However, the last pawn to be "arrested" always is the one you tried to arrest originally - and trying to arrest that one might make the faction hostile."

I am running other mods, so I don't know if that may be the cause; still - this seems like something that should be brought up.

Here two Screenshots of what I'm doing to make the error happen:
![20170328184145_1](https://cloud.githubusercontent.com/assets/26746156/24416961/d519d76a-13e6-11e7-9ed7-6ef113d9b75b.jpg)
![20170328184157_1](https://cloud.githubusercontent.com/assets/26746156/24416964/d7a9f442-13e6-11e7-94af-56a1b4bc2ad6.jpg)

I'm trying to arrest "Boss". Yet, upon doing so, the game trows an error message, and "Bison" becomes a prisoner instead - who then tries to excape immedeately (all the other arrest actions before were inside my base, so I guess that's why they didn't try to escape.). The stuff on the ground was dropped by "Bison" upon his arrest. From earlier (unlogged) tests, distance between the target of the arrest and the person being converted to prisoner doesn't seem to matter.

This is the output log, with everything from before loading the save cut:
[output_log_shortened.txt](https://github.com/OrionFive/Hospitality/files/876412/output_log_shortened.txt)

And this is the full output_log, in case the information from starting the game itself is needed:
[output_log.txt](https://github.com/OrionFive/Hospitality/files/876415/output_log.txt)

**Comment by OrionFive** [comment]
Thanks for the thorough report. I'll see what I can do.

**Comment by OrionFive** [comment]
Gah. I had this fixed days ago already, but hadn't released the fix. Next version it should be fine again.

**Comment by OrionFive** [comment]
Okay. The fix doesn't work. In fact the whole prisoner / arrest system is so ridiculously ****ed up I've spent half the day and got nowhere. Everything is hardcoded all over the place, I can't even disable arresting guests without having to make some serious incisions into RimWorld code.

Right now I'm thinking I should just make RimWorld crash to desktop when a guest is arrested. That'd at least be a solution that works.

**Comment by OrionFive** [comment]
I fixed it for the next version. Now they get aggressive as one would expect.
