### ISSUE TITLE
Hospitality: Rescued Traders stay forever until they die. [name] is part of a cavavan trader and not a guest

### ISSUE THREAD

**Issue by mmance** [OrionFive/Hospitality#530]
When I rescue a member of a caravan, they roam around the home area, don't eat, sleep on the floor, and eventually die.
When you look at the guest tab,  it shows they are a member of a caravan trader and not a guest.

I honestly don't know if this is even a hospitality problem.

EDIT:
I just rescued a member of "Request Immediate Military Aide" and they also say member of a trading caravan and not a guest.

**Comment by OrionFive** [comment]
I honestly don't know either. Without a log of the incident, there's nothing I can do for you.
