### ISSUE TITLE
Royalty conflict

### ISSUE THREAD

**Issue by axlegear** [OrionFive/Hospitality#531]
Error in logs when starting any new maps with Hospitality installed.  Latest Steam version.

`Failed to read royalty titles or their bedroom requirements. This means you are using a mod that changes these and broke them.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0000d] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at Hospitality.Building_GuestBed.GetMetRoyalTitles (Verse.Room room) [0x00021] in <f7f6b1b841ba4733b81d7ee58f78f413>:0 
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Hospitality.Building_GuestBed:GetMetRoyalTitles(Room)
Hospitality.Building_GuestBed:UpdateStats()
Hospitality.Building_GuestBed:SpawnSetup(Map, Boolean)
Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch7(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
RealRuins.BlueprintTransferUtility:Transfer(CoverageMap)
RealRuins.RuinsScatterer:Scatter(ResolveParams, ScatterOptions, CoverageMap, List`1)
RealRuins.GenStep_ScatterRealRuins:Generate(Map, GenStepParams)
Verse.MapGenerator:GenerateContentsIntoMap(IEnumerable`1, Map, Int32)
Verse.MapGenerator:GenerateMap(IntVec3, MapParent, MapGeneratorDef, IEnumerable`1, Action`1)
Verse.Game:Verse.Game.InitNewGame_Patch3(Game)
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()`

**Comment by OrionFive** [comment]
It's exactly what it says in the error. You're using another mod that messes with your Royalty requirements and breaks them.
