### ISSUE TITLE
Hospitality: Hard crash? Removing moods from buried pawn?

### ISSUE THREAD

**Issue by madamunkey** [OrionFive/Hospitality#532]
The game hard crashes, and spits this error log, Im submitting here since the error involves hospitality
This is a consistent issue that seemingly cannot be solved by:
Removing the guest beds (crashes once theyre readded)
Deleting the offending pawns (including the one in the grave)
Enabling "Pause on Error" does nothing

[Player.log](https://github.com/OrionFive/Hospitality/files/6338192/Player.log)
https://a.uguu.se/0zyoHMkxqpb0_Autosave-2.rws

**Comment by OrionFive** [comment]
I don't see why this should cause a hardcrash.

You could try and load the game without Hospitality if you want to get rid of the beds. However, if you have groups of guests on the map, it can create new problems.

This is not usually a problem, so either your savegame is borked or you have a conflicting mod active.
