### ISSUE TITLE
Hospitality: Guests clean their own rooms

### ISSUE THREAD

**Issue by madamunkey** [OrionFive/Hospitality#533]
**What problem does your suggestion solve**
Makes guests stuck with dirty rooms not perpetually hit with the small mood debuff

**Describe the solution you propose**
You could have guests cleaning their own room and have (mainly how dirty it was on arrival) factored into their departure score 

**Describe alternatives you've considered**
Make rooms with guests in them (or just rooms with guest beds) higher priority for cleaning so when a pawn does get around to cleaning they actually prioritize making guests happy

Adding features takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Happy guests will do chores at the colony.
I recommend using a mod like Cleaning Priority, CleaningArea, or PriorityClean (with sterile tiles in the guest room), to make sure guest rooms are regularly cleaned. Nice for your kitchen and hospital too.
