### ISSUE TITLE
Skip copying the designationCategory for guest beds

### ISSUE THREAD

**Issue by emipa606** [OrionFive/Hospitality#534]
**What problem does your suggestion solve**
Some mods reloads the Architect tab, making all generated guest-beds show up.
![image](https://user-images.githubusercontent.com/6932991/115712750-6e2ee400-a375-11eb-8d75-97b30f98c4f3.png)

**Describe the solution you propose**
In the Hospitality_SpecialInjector.cs, row 60
Check if the field is the designationCategory-field, if so skip it

**Comment by OrionFive** [comment]
Thanks for the solution. It will be included with the next update. But I'm not sure yet when that will be.
