### ISSUE TITLE
Hospitality: Gift whitelist and value options

### ISSUE THREAD

**Issue by MercuryDoll** [OrionFive/Hospitality#535]
While i love the idea of happy visitors leaving gifts behind, i feel like it currently is too extreme and they either fill up your warehouse with junk or they drop a real silverbomb on you. Probably both later on when the groups become large.

A possible solution would be to add a filter-list for players to define what items they are willing to accept as gifts. Perhaps an option in the modsettings menu to limit the value range of gifts too.

**Comment by OrionFive** [comment]
The items are already filtered by value. So junk it is.
