### ISSUE TITLE
Guestbed Config Error

### ISSUE THREAD

**Issue by 65001** [OrionFive/Hospitality#54]
I am getting the following config error on the start of Rimworld.
`
Config Error in Guestbed : Guestbed has components but it's thingClass is not a ThingWithComps
`

[Output_Log](https://pastebin.com/NXRgfbSV)
Mod Order:
<ol>
			<li>Core</li>
			<li>RT Fuse</li>
			<li>Medical Tab</li>
			<li>RimFridge</li>
			<li>Expanded Prosthetics and Organ Engineering</li>
			<li>Power Logic</li>
			<li>Glass+Lights</li>
			<li>Dubs Rimkit(Medkit)</li>
			<li>Trading Spot</li>
			<li>Colony Manager</li>
			<li>More Vanilla Turrets</li>
			<li>Hospitality</li>
</ol>

Is this due to a known mod conflict and is there anymore info you would need to solve this problem?

**Comment by OrionFive** [comment]
I'm not sure what the issue is yet, but the problem is line 64, that Hospitality can't load the HugsLib library.

**Comment by OrionFive** [comment]
And now that I'm looking at your list again - yeah, you have to load the HugsLib mod before Hospitality!

**Comment by 65001** [comment]
Okay Thanks!
