### ISSUE TITLE
Mod name: hospitality - RimWorld.MainButtonDef defines the same field twice: iconPath

### ISSUE THREAD

**Issue by PapaWraiths** [OrionFive/Hospitality#541]
**Describe the bug**
What happened? - loaded the game, error shows in the main menu

**To Reproduce**
1. Select 'load the game'
2. Click on 'nothing at main menu'
3. Open ' the game '
4. This happens every time 

**Console log**
Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.
https://gist.github.com/c573c8fc9dd66892202a2a0966168c7e
**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
XML RimWorld.MainButtonDef defines the same field twice: iconPath.

Field contents: UI/Buttons/MainButtons/IconGuests.

Whole XML:

<MainButtonDef><defName>Guests</defName><label>guests</label><description>List guests in the area and manage hospitality.</description><tabWindowClass>Hospitality.MainTab.MainTabWindow_Hospitality</tabWindowClass><order>53</order><iconPath>UI/Buttons/MainButtons/IconHospitality</iconPath><iconPath>UI/Buttons/MainButtons/IconGuests</iconPath></MainButtonDef>
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:Verse.DirectXmlLoader.DefFromNode_Patch1(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by PapaWraiths** [comment]
if I can get log link from f12 ill update  here with it

**Comment by PapaWraiths** [comment]
https://gist.github.com/c573c8fc9dd66892202a2a0966168c7e

**Comment by OrionFive** [comment]
Do you use a mod that replaces or adds icons for the tabs?
If so, that's causing it, since Hospitality already has an icon. If not, check again. Disabled mods count as well.

**Comment by PapaWraiths** [comment]
i think I am using a few.. i'll have to have a look this weekend, working night shifts till Friday
thanks for the quick response!! new to modding and such still learning things.

________________________________

**Comment by OrionFive** [comment]
You can reopen this issue if you can't work it out. But odds are you're using one that (aggressively)adds an icon to Hospitality (but Hospitality already has one).
