### ISSUE TITLE
Hospitality : Two guests share a royal bed

### ISSUE THREAD

**Issue by topdsoft** [OrionFive/Hospitality#543]
**Describe the bug**
I have a royal (double) bed in my best guest room.  Unfortunately two guests will both use the bed and get the "Sharing bed" -5 debuff.  
Not a huge issue, but I wanted to let you know.
Thank you for a really great mod.  I can't play without it :)

**To Reproduce**
1. Select '...'
3. Open '....'
4. This happens

**Console log**
Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Yeah, it's not a bug. It comes down to the guests taking the -5 into account for that specific bed.
