### ISSUE TITLE
Hospitality: Pawns freezing and not moving at all anymore

### ISSUE THREAD

**Issue by noobthemaster** [OrionFive/Hospitality#546]
**Describe the bug**
So I have been playing on this save for some hours. Suddenly an android from the android mod gets downed near my base, so i try to recuse him. I get a lot fps drops after I have carried him so I try to restart my rimworld, but when I load the save again, all my pawns are frozen and can only move when drafted. Dubs hygiene is complaining that there is a mod not functioning. When I tried to remove hospitality they can move again but I still have fps drops every 2 seconds. I really enjoy hospitality and this have not happend before. It would be nice to keep playing with dubs hygiene and hospitality. Also dubs hygiene is still complaining when I remove hospitality but the pawns can move again.

**To Reproduce**
As I wrote, I have tried to remove hospitality and this seem to fix the freezing bug however dubs is still complaining and it is also laggy

**Console log**
Doesnt work, says bad request

**Error stacktrace**
I will upload the whole error message from the debuglog, it mentions at exceptions hospitality.harmony a lot
[Player.log](https://github.com/OrionFive/Hospitality/files/6644366/Player.log)

**Comment by OrionFive** [comment]
I'm sorry, but there's not much I can do for you here. It looks like your save game is broken. The main culprit seems to be one or more invalid areas. If you're lucky you can clean these up in-game, or remove them from your save game.

**Comment by noobthemaster** [comment]
Alright, Thanks
