### ISSUE TITLE
Hospitality - guests not arriving

### ISSUE THREAD

**Issue by Azzuron73** [OrionFive/Hospitality#548]
Guests never arrive.

For a new game (log file attached) a message popped up asking if I wanted visitors. I selected the "assure safety" option but no one appeared. In previous games, no guests ever visited. When an allied faction was called on the comms concole it would say they are on their way and arriving in x amount of days, but never actually appear. When called again, they aren't interested in visiting - I guess because the game thinks they have just been.

I have uninstalled and reinstalled the game, verified the files, played around with removing certain mods and starting a new game, changed the order of mods, all with no result. Options to receive guests within mods are enabled.

https://gist.github.com/HugsLibRecordKeeper/caa4ad29854c8e4951e6aebb4f5f4bef

Many thanks.

**Comment by OrionFive** [comment]
There are errors from MoreFactionInteraction. Might be outdated, broken, or conflicting.
But the Hospitality error is caused by an old RimWorld version. Are you maybe on a beta branch of RimWorld?
