### ISSUE TITLE
Harmony: The guest menu does not work

### ISSUE THREAD

**Issue by Zelkioz** [OrionFive/Hospitality#552]
When I open the guest menu, nothing is displayed and I can no longer manage my guests 

**Console log**
https://gist.github.com/HugsLibRecordKeeper/da1db26516849c81cd9195f661bf5164

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/87701387/126311369-87ea03f3-7aa8-4148-9132-11b0cd645480.png)
![image_2021-07-20_124641](https://user-images.githubusercontent.com/87701387/126311392-c6b45e3c-1146-4837-9d63-f1d7bf419002.png)

**Comment by Daxtonian** [comment]
I am experiencing this same bug.

**Comment by Daxtonian** [comment]
> I am experiencing this same bug.

I'm still playing on 1.2 by the way.

**Comment by OrionFive** [comment]
I've pushed a new version that should address this issue. Let me know how it goes.
