### ISSUE TITLE
Mod name: Missing Method Exception: Verse.Room thrown and pawns tasked with Entertaining can no longer find jobs. Permanently idle until Guest Beds are created..

### ISSUE THREAD

**Issue by undeadbanana** [OrionFive/Hospitality#566]
**Describe the bug**
What happened?

**To Reproduce**
1. When guest notification appears saying you don't have beds, click "Don't Accept Guests Until I Have Beds."
2. Eventually an exception will be thrown saying -
"Exception in Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage: System.MissingMethodException: Verse.Room Verse.GridsUtility.GetRoom(Verse.IntVec3,Verse.Map,Verse.RegionType)
  at RimWorld.JobGiver_Work.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00681] in <1d0fff66c69441c2a312a44c03271deb>:0 
     - transpiler net.pardeike.rimworld.lib.harmony: IEnumerable`1 VisualExceptions.RunloopExceptionHandler:Transpiler(IEnumerable`1 instructions)
     - prefix Orion.Hospitality: Boolean Hospitality.Patches.JobGiver_Work_Patch+TryIssueJobPackage:Prefix(Pawn pawn)
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x0012f] in <1d0fff66c69441c2a312a44c03271deb>:0 
     - transpiler net.pardeike.rimworld.lib.harmony: IEnumerable`1 VisualExceptions.RunloopExceptionHandler:Transpiler(IEnumerable`1 instructions)"

     - And pawns tasked with Entertaining will go permanently idle unable to find jobs even if you un-assign Entertain.

3. The pawn idle bug can be fixed by adding guest beds in a room. Pawns will work normally again.
4. I was able to reproduce the issue again by deleting the guest beds, I haven't had guests try to enter yet though. I'll check if adding guest beds, receiving guests, then deleting beds reproduces the issue.

**Console log**
https://gist.github.com/f22cddfae0ca350198cc3d172b21f397

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.MissingMethodException: Verse.Room Verse.GridsUtility.GetRoom(Verse.IntVec3,Verse.Map,Verse.RegionType)
  at (wrapper dynamic-method) RimWorld.JobGiver_Work.RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1(RimWorld.JobGiver_Work,Verse.Pawn,Verse.AI.JobIssueParams)
  at (wrapper dynamic-method) Verse.AI.ThinkNode_PrioritySorter.Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage_Patch0(Verse.AI.ThinkNode_PrioritySorter,Verse.Pawn,Verse.AI.JobIssueParams)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch0 (string)
(wrapper dynamic-method) Verse.AI.ThinkNode_PrioritySorter:Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage_Patch0 (Verse.AI.ThinkNode_PrioritySorter,Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) Verse.AI.ThinkNode_Priority:Verse.AI.ThinkNode_Priority.TryIssueJobPackage_Patch0 (Verse.AI.ThinkNode_Priority,Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) Verse.AI.ThinkNode_Priority:Verse.AI.ThinkNode_Priority.TryIssueJobPackage_Patch0 (Verse.AI.ThinkNode_Priority,Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) Verse.AI.ThinkNode_Priority:Verse.AI.ThinkNode_Priority.TryIssueJobPackage_Patch0 (Verse.AI.ThinkNode_Priority,Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch3 (Verse.AI.Pawn_JobTracker,Verse.ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch3 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0 (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch3 (Verse.Pawn)
(wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch0 (Verse.TickList)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch3 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch0 (Verse.Root_Play)

```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by undeadbanana** [comment]
Actually, it doesn't matter if they're assigned to Entertain or not. Pawns will just start becoming Idle.

**Comment by OrionFive** [comment]
Thanks for the thorough report. But neither Hospitality, nor RimWorld vanilla are accessing the GetRoom method from TryIssueJobPackage. This only leaves VisualExceptions, which also messes with the TryIssueJobPackage method.

It's weird that the GetRoom method is not found to begin with. So I would start with other problems you're having. 
For example, MOARANDROIDS is failing a patch. And something is breaking the vanilla guest tracker. 

Sorry that I can't do more for you. I don't think this has to do with Hospitality.
