### ISSUE TITLE
More Mechanoids: Conflict with the mod Windows

### ISSUE THREAD

**Issue by Owlchemist** [OrionFive/Hospitality#567]
**Describe the bug**
The repair job throws endless red errors when a pawn attempts to repair a while + this mod being active.

**To Reproduce**
Damage a wall, right click and force a pawn to try and repair it.

**Console log**
https://gist.github.com/HugsLibRecordKeeper/04b811dd3532712dfebd4f4ce1e0e251

Secondarily, there may also be errors when viewing a placed blueprint of a window's info card (less information is available on this atm).

**Comment by OrionFive** [comment]
It looks like it would be very unlikely for the code to fail, but in either case, I've made it more defensive now. You can download the latest version here for testing: https://github.com/OrionFive/MoreMechanoids
Can you tell me if that solves the problem?

**Comment by Owlchemist** [comment]
Just tested. Totally error-free now! Nice.

**Comment by OrionFive** [comment]
Excellent.
