### ISSUE TITLE
Hospitality: Every visit a disappointing visit

### ISSUE THREAD

**Issue by Destriel** [OrionFive/Hospitality#571]
I have a large room with 20 legendary gold beds, gold legendary tables with gold legendary chairs. 
Food, Rest, Recreation, Beauty, Comfort, Outdoors and Mood  bars are maxed and yet at the end of their stay I get the "Had a disappointing visit" -22 debuff, I don't know what else to do.
Also I have all my colonists kept in the same zone as the guests so all guests are recruitable with 3/3 after a day or 2 of socialising.

![2021-08-13 13_12_52-RimWorld by Ludeon Studios](https://user-images.githubusercontent.com/88943941/129456467-2c23da1b-4d38-4214-88ee-8cab9468df8d.jpg)

Are there any other settings, stats or Defs that govern the outcome of a visit?

**Comment by OrionFive** [comment]
Hmm. What scores do you get from them? If the score is lower than their opinion of your faction, it will be a disappointing visit.
The score is determined by their mood at the time they leave, compared to the mood they arrived with.

**Comment by Destriel** [comment]
That's really good to know, thank you, there's a possibility that the large distance between the guest area and the spot where they exit the map could mean they become tired and hungry on that journey.

![2021-08-14 -RimWorld](https://user-images.githubusercontent.com/88943941/129458740-c39fd50c-8d3b-42f6-abfb-447f243012d9.jpg)

The last score I received was something like -2 or -3, is there a chance that all the bars are maxed most of the time, but just before they were about to eat or sleep their time is up and they leave unhappy? Not sure how to resolve that.

**Comment by Destriel** [comment]
I'm going to reinstall the mod, see if that helps, just had a score of -13 and at the time pretty much all of the guests had all bars maxed, I think my install is a bit wonky.
I do love your mod by the way, if I can get past this wobble I'll be having a great time. :)

**Comment by OrionFive** [comment]
How odd. Maybe I broke something in the latest version.

The score is determined the moment they leave. So the way off the map is not relevant.

**Comment by Destriel** [comment]
Hi there, just had my first 100% score, now that I know how the scoring works, it seems because the period between them leaving and returning was so short, certain positive mood events hadn't decayed, so the guests were arriving with very high mood bars with very little to improve upon,
Not only that, I've tweaked a few of the core defs so this problem is down to me, I just didn't know how the scoring system worked up until now, the score being based upon them arriving miserable and leaving happy is a good one and makes sense, I'll just have to tweak a few defs in order to make sure they arrive more miserable. :D
Thanks for taking the time to read and respond, but most of all, thanks for creating a wonderful mod.

**Comment by OrionFive** [comment]
Thanks! I'm glad you could work it out.

Yeah, this is the most straightforward way to measure their stay while taking into account the myriad of possible ways it could be good or bad.
An alternative would be to take frequent snapshots of their mood and average that over their stay. But it's more complicated.
