### ISSUE TITLE
Hospitality: Guest with little money takes everything for free

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#572]
Apparently, if a guest can't afford more than 1 of an item, he just takes it for free.

**Comment by christophkogler** [comment]
I believe this is specifically for purchasing single items that would cost less than 1 silver each, for pawns with 1 silver.

JobDriver_BuyItem line 75, and 82 are what I believe to be important to this
75:            var maxAffordable = itemCost <= 0 ? 5 : Mathf.FloorToInt(silver.stackCount/itemCost); 
when itemcost is less than one but not zero (as this is a float), the pawn may have only one silver and afford one (or more, for very cheap things), which is fine.
82:            var price = Mathf.FloorToInt(count*itemCost);
I believe this is the problem, as anything less than 1 silver with a purchase count of 1 (or any other combination that is less than one total) now costs 0. For very cheap things, like raw meat, eggs, kibble, they may take MULTIPLE and still add up to less than 1 silver, making it so they take them for free. Pemmican has a 0.77 itemCost, and thus they can 'afford' one and so take one, for free, repeatedly.

I think CeilToInt instead, on line 82, fixes this issue, although I don't know what that could break. It would make pretty much everything 'cost' 1 silver more to purchase for visitors. 

Another option that might be better is checking if (count*itemcost) is less than 1 and simply setting it to 1 if so.

**Comment by OrionFive** [comment]
I can't reproduce this myself. 
I'm gonna go for CeilToInt for price, because if I set the minimum to 1, there can't be free items anymore, which is actually a feature.

**Comment by OrionFive** [comment]
Okay, I managed to reproduce it once now. I'm pretty sure CeilToInt will fix it. I'm gonna close this for now.
Should the issue resurface with the next version, feel free to open it again.
