### ISSUE TITLE
Hospitality & Non Uno Pinata

### ISSUE THREAD

**Issue by RayvenFeather** [OrionFive/Hospitality#585]
**Describe the bug**
Came here to make this posty post after your reply on steam wkshp.

Non Uno Pinata is an inventory overhaul mod, Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=1778821244

The main features that Hospitality seems to interfere with are the inventory spill settings. As long as NUP is loaded after hospitality the special corpse inventory options work, just not the drop behavior options. NUP affects inventory behavior in 3 different scenarios: cremation, downed, and killed. My current playthru has been with supremacists that just leave corpses out in the field to decay and intimidate enemies so I'm not 100% sure about the cremation setting compatibility but I'm mostly concerned with the other two. Downed and killed allow you to toggle whether or not colonists and outsiders drop their equipment or inventory on down/death. I currently have it set so that colonists will only drop their equipment and inventory on death, not down. I have outsiders set to do it on both. However my colonists are still dropping all of their stuff on both death and down. The main side-effect of this is i become supremely triggered when i draft colonists only to find when they're already in combat that they dropped their weapon earlier because they were downed for some reason or another. "sorry sir, i dont have my sword because bob punched me in the face earlier and it really hurt so i dropped it! owie!" - colonist about to be ripped to shreds by bugs  

thanks a ton for looking into this!

**Comment by OrionFive** [comment]
I've changed the code to not affect colonists, slaves, or prisoners.
However, it depends on how NUP patched it, if that will make a difference.

You can download the new version [here](https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip). I'm also gonna roll it out with the next update, but I don't know when that will be.
