### ISSUE TITLE
Hospitality Mod name: Smoothed walls by quests needed to be claim, when damaged I lose relations with them.

### ISSUE THREAD

**Issue by SamuraiKenshi** [OrionFive/Hospitality#586]
**Describe the bug**
So my quests helped me smoothing walls but infestation happend. I threw some grenades at insects but some of them hit my smoothed walls. Rimworld says that my relations with Drow faction fall because I attack theirs building which should be not. I clicked the wall and it needs to be claimed again because my quests smoothed them.

**To Reproduce**
1. Have quests
2. Let them help you smooth walls
3. Attak walls that they smoothed
4. This happens

**Console log**
https://gist.github.com/064eafaf00512eb46cb31f63feebb1b1

**Error stacktrace**
No error

**Screenshots**
Not needed

**Comment by OrionFive** [comment]
This has been fixed in the June update. So probably you still have some walls of other factions from before then.
