### ISSUE TITLE
Hospitality: Mod does not work.

### ISSUE THREAD

**Issue by DesmitX** [OrionFive/Hospitality#587]
**Describe the bug**
Everytime I play with the mod, I get message that guests want to come, but they can't, because colony doesn't have guest beds. Even if I press button promise to provide them safety - nothing happens. Also, when I have the guest beds, everything is the same, after 10-20 hours of the game, guests never came.

**Console log**
https://gist.github.com/8915eac7b548601579cffde77dc76c2c

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
I'm pretty sure that's the Trading Control mod that breaks finding the location where guests arrive.

**Comment by DesmitX** [comment]
Thanks!
