### ISSUE TITLE
Hospitality: Non-guest pawn tried to optimize apparel error with CE

### ISSUE THREAD

**Issue by Glucocorticoid** [OrionFive/Hospitality#590]
**Describe the bug**
Colonists can not optimize their apparel because Combat Extended mod can found Hospitality.JobGiver_OptimizeApparel_Guest job for non-guest pawns.

**To Reproduce**
1. Update all mods.
2. Start new colony.
3. Make loadouts for pawns.
4. Do incident on map -> VisitourGroup.
5. Wait some time

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Non-guest Iris tried to optimize apparel.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.Log:ErrorOnce (string,int) (at Verse/Log.cs:123)
Hospitality.JobGiver_OptimizeApparel_Guest:TryGiveJob (Verse.Pawn)
CombatExtended.JobGiver_UpdateLoadout:GetUpdateLoadoutJob (Verse.Pawn)
CombatExtended.JobGiver_UpdateLoadout:TryGiveJob (Verse.Pawn)
...
```

There is DutyDef "Relax" in Hospitality mod which contains Hospitality.JobGiver_OptimizeApparel_Guest.
When Rimworld resolve a pawn think tree, it can find think node with class ThinkNode_Duty.
This class collect all DutyDefs from all mods and add Duty nodes to pawn think tree.
```
		protected override void ResolveSubnodes()
		{
			foreach (DutyDef allDef in DefDatabase<DutyDef>.AllDefs)
			{
				allDef.thinkNode.ResolveSubnodesAndRecur();
				this.subNodes.Add(allDef.thinkNode.DeepCopy(true));
			}
		}
```
Due to that any colonist have 2 separate nodes for apparel optimization in Humanlike think tree.

Combat Extended mod to update pawn inventory calls vanilla method to return Optimize Apparel job.
```return pawn.thinker?.TryGetMainTreeThinkNode<JobGiver_OptimizeApparel>()?.TryGiveJob(pawn);```
https://github.com/CombatExtended-Continued/CombatExtended/blob/ca3d1dd9ae70c3b7ed3870e7787c99c822371b66/Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs#L327

```
		public T TryGetMainTreeThinkNode<T>() where T : ThinkNode
		{
			foreach (ThinkNode thinkNode in this.MainThinkNodeRoot.ChildrenRecursive)
			{
				T val = thinkNode as T;
				if (val != null)
				{
					return val;
				}
			}
			return default(T);
		}
```
Because of Hospitality.JobGiver_OptimizeApparel_Guest is subclass of Rimworld.JobGiver_OptimizeApparel, in some cases this code will return Hospitality.JobGiver_OptimizeApparel_Guest as valid node (cast to parent type is always valid).

But Hospitality.JobGiver_OptimizeApparel_Guest will abort with error, because of pawn is not guest and optimize apparel job for colonist will be never done.

In 885405d optimize apparel job was renamed, but CE still call it because of valid class inheritance.

Maybe there is another way to add Relax think tree to guest pawns?

**Comment by christophkogler** [comment]
I can barely even understand what is happening in the Pawn_Thinker and ThinkNode code, but this seems like a good explanation of what's causing the error. Easiest fix might be a check for if the pawn is a colonist before checking that they are a guest in OptimizeApparel_Guest, and simply running vanilla optimize apparel if so. It seems like it would fix this problem, and should catch any potential errors caused by other mods trying to run the guest version on colonists. Don't _think_ that could break anything, and should make it so only non-guest, non-colonist pawns attempting to optimize their apparel can throw errors.

**Comment by OrionFive** [comment]
@SomeoneCrazy, thanks for the tip. I've implemented it like this now.

I'll roll out the fix with the next update on Steam. For the time being it can be downloaded [here](https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip).
