### ISSUE TITLE
Hospitality: Humanoid Alien Races friends dissapear?

### ISSUE THREAD

**Issue by Euphoric** [OrionFive/Hospitality#592]
I'm playing a Moyo-only colony and I was hoping to use Hospitality and friend-making to recruit more Moyos.

But every time Moyo guests re-visit, their friend list is gone. Interestingly, human that comes with them seems to keep his friends.

I did manage to recruit one once, but that seemed to be fluke.

I'm wondering if there isn't some kind of incompatiblity between Hospitality and Humanoid Alien Races. Or maybe Moyos.

**Comment by OrionFive** [comment]
It's possible. Do note that thoughts causing friendships expire after some amount of time. So it could be a coincidence.Please reopen this when you have more information.

**Comment by Euphoric** [comment]
Do you have any suggestions on how to debug this problem? I feel that I can't do much if I don't have detailed logs or insight into the code.

**Comment by OrionFive** [comment]
You and me both. 
I've looked into the memory - the endorsement effect of the recruiter lasts 45 days. You can use dev tools and trigger visitor events until they show up again. This way you can check if it truly resets or if it has expired. It could also be that the faction doesn't have a lot of names in their name generator and it's not actually the same pawn the second time around.
