### ISSUE TITLE
Trader Fromm Caravan Can't Trade

### ISSUE THREAD

**Issue by StarlightSovereign** [OrionFive/Hospitality#594]
I'm getting an error where if a trade caravan enters the map, it starts ticking endless errors and they can not be traded with.

Only mods loaded are
Harmony
Core
Royalty
Ideology
HugsLib
Mod Manager
Hospitality

The trader has no yellow question marker and can't be traded with manually anyway.
I have this mod running on one computer and on the other it won't work and does this on a clean install with no configs.
Everything is cleared.
Please help.
Thank you.

**Comment by OrionFive** [comment]
I still need a proper report. Log, stacktrace, everything.

**Comment by StarlightSovereign** [comment]
Dude, I had it copied to paste and somehow forgot. ADHD in action. Here ya go. 
https://gist.github.com/33e8fd29911004eec5054d88bd3a477b

Exception drawing ThingOverlay for Stumpy: System.MissingMethodException: bool RimWorld.PawnUtility.CanCasuallyInteractNow(Verse.Pawn,bool)
  at (wrapper dynamic-method) RimWorld.Pawn_TraderTracker.RimWorld.Pawn_TraderTracker.get_CanTradeNow_Patch1(RimWorld.Pawn_TraderTracker)
  at Verse.Pawn.get_CanTradeNow () [0x00008] in <d243303f714d4dc48680ccaecd2f594e>:0 
  at (wrapper dynamic-method) Verse.PawnUIOverlay.Verse.PawnUIOverlay.DrawPawnGUIOverlay_Patch3(Verse.PawnUIOverlay)
  at Verse.Pawn.DrawGUIOverlay () [0x00006] in <d243303f714d4dc48680ccaecd2f594e>:0 
  at Verse.ThingOverlays.ThingOverlaysOnGUI () [0x0005e] in <d243303f714d4dc48680ccaecd2f594e>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.ThingOverlays:ThingOverlaysOnGUI ()
(wrapper dynamic-method) RimWorld.MapInterface:RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs_Patch2 (RimWorld.MapInterface)
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch2 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)

**Comment by OrionFive** [comment]
The problem here is that Hospitality doesn't even load correctly. Either the version doesn't match RimWorld or it's a broken install. Maybe unsubscribe it, clear out the mod folder and resubscribe.

**Comment by StarlightSovereign** [comment]
I did a clean install of it. Unsubbed it, backed up my workshop folder, renamed it so Steam would generate an entirely new workshop folder, subbed, got a clean copy of Hospitality, and that's the result. 

Rimworld is 1.3, latest update. 

What else can I try?

**Comment by OrionFive** [comment]
Do you maybe run a local copy from your RimWorld mods folder?

The process sounds correct. But according to your previous log it fails horribly trying to load Hospitality. Are you running on Linux or something?

**Comment by StarlightSovereign** [comment]
Nope, Win10. And I was not loading a local copy. 

I'm going to load a copy from my PC that has this working and see if that works. 
I don't know why Steam isn't giving me a correct copy otherwise. I'll let you know if this works.
