### ISSUE TITLE
Hospitality: Guests don't buy non-food

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#597]
Apparently, when no food is available, guests keep browsing.

Verify that this happens and fix it.

**Comment by christophkogler** [comment]
I think this has the same source as issue #574, a different endless browsing ticket. Browse Items toil is set to never complete, and checks for overrides.

JobDriver_BrowseItems lines 20-28:
yield return new Toil {
tickAction = delegate {
 pawn.rotationTracker.FaceCell(job.GetTarget(TargetIndex.B).Cell);
 pawn.GainComfortFromCellIfPossible();
  if (pawn.IsHashIntervalTick(100))
  { pawn.jobs.CheckForJobOverride(); }
},
defaultCompleteMode = ToilCompleteMode.Never};

**Comment by OrionFive** [comment]
Technically, CheckForJobOverride does end the job if something better comes up. But I suppose some kind of timeout wouldn't hurt.

**Comment by OrionFive** [comment]
I've set a random timeout (30 minutes to 2 hours). I'm not sure if this is the problem, though, or just treating the symptom.
