### ISSUE TITLE
Hospitality: Different grading for beds

### ISSUE THREAD

**Issue by adamkad1** [OrionFive/Hospitality#599]
**What problem does your suggestion solve**
I feel like attractiveness of a room is a bit bland, since a lot of it comes from the quality of the bed, other factors are somewhat low

**Describe the solution you propose**
Make a bed contribute to room attractiveness based on its sleep efficiency and perhaps comfort value too
1 point per 1% sleep effectiveness maybe? Not too sure about comfort though, since it operates in small numbers. Perhaps some situational extra ideology-dependent attractiveness, although I think you are working on it already?

**Describe alternatives you've considered**
Dunno tbh

**Comment by OrionFive** [comment]
This is also #565.
