### ISSUE TITLE
Visitor groups seem to show up more rarely in A16

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#6]
Please confirm that this is the case.

**Comment by CallMeOzz** [comment]
Orion, was this a question about the frequency of this incident with RimWorld core?  Or, did you want help testing something specific to Hospitality A16?  It sounded like a Core question, but I didn't want to skip it, if it was mod-specific...

**Comment by OrionFive** [comment]
Well, since A16 it seemed to me that visitors appear less often. A16 splits up incidents into different categories, of one AllySupport or so is for these kinds of incidents. Increasing the odds of the visitor group incident will only make it more likely within this category.

The chance for the category itself seems to be determined by the storyteller. I'm not sure this mod should mess with that, as it means overriding the storyteller.

I'd like to have some input from others if you experience the same and if you think the storyteller should be messed with.

**Comment by OrionFive** [comment]
One way to fix this would be to queue an event when visitors leave satisfied, for the next time they come by.

**Comment by OrionFive** [comment]
I've implemented recurring visits to counter the lowered frequency.
