### ISSUE TITLE
Hospitality: Error when selecting nutrient dispenser

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#604]
Achtung detected the following error after I right-clicked on a Nutrient Paste Dispenser with a pawn selected:

https://pastebin.com/mdeEn4qD

Is this the right place to investigate? Sorry if this isn't enough/the correct info or format.

**Comment by OrionFive** [comment]
Apparently someone is using the non-release version, which generally isn't such a good idea. 
But it should actually work in this case, so this may be useful.

**Comment by RealTelefonmast** [comment]
That is a strange issue, ShouldEmpty can only error like that if silverContainer is null. Did you load an older save before this update? That would explain it, and I know how to fix it then. I will provide an attempt for a fix in a moment.

**Comment by OrionFive** [comment]
People can update from any version to this one, so it should be indefinitely backward compatible (I do draw the line at 1.1, though).
I didn't experience this myself. It's from a user who downloaded the latest code directly. I did point out that that's not a good idea. But people really want their CE fix, and I still haven't made this live, since I don't have time to test it.

**Comment by OrionFive** [comment]
I've merged it. Should be fine now.
