### ISSUE TITLE
Hospitality: Combat Extended still not working

### ISSUE THREAD

**Issue by GreatKingCody** [OrionFive/Hospitality#606]
**Describe the bug**
After downloading and installing the latest version of Hospitality from GitHub, for some reason I am still getting the "Ambiguous match found" error. I am new to GitHub Rimworld mods, so I suppose there is a chance I didn't install it properly, but I doubt that is the case. Old files are possibly being loaded, I still am subscribed to the Steam version, but it is tuned off. 

**To Reproduce**
1. Load both mods
2. Wait for guests to try to arrive

**Console log**
https://gist.github.com/ebc7d80a9fc9a24918ffa1475515d333

**Error stacktrace**
Hospitality: Something failed when setting up visitors from faction Dodos Kingdom (civil kingdom):
System.Reflection.AmbiguousMatchException: Ambiguous match found.
  at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00059] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) [0x0000e] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Hospitality.ItemUtility.GetInventorySpaceFor (Verse.Pawn pawn, Verse.Thing current) [0x0003d] in <908b0104ebb3469797903b8ee6664172>:0 
  at Hospitality.IncidentWorker_VisitorGroup.GiveItems (System.Collections.Generic.IEnumerable`1[T] visitors) [0x000c6] in <908b0104ebb3469797903b8ee6664172>:0 
  at Hospitality.IncidentWorker_VisitorGroup.SpawnGroup (RimWorld.IncidentParms parms, Verse.Map map) [0x000a5] in <908b0104ebb3469797903b8ee6664172>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Hospitality.IncidentWorker_VisitorGroup:SpawnGroup (RimWorld.IncidentParms,Verse.Map)
Hospitality.IncidentWorker_VisitorGroup:TryExecuteWorker (RimWorld.IncidentParms)
(wrapper dynamic-method) RimWorld.IncidentWorker:RimWorld.IncidentWorker.TryExecute_Patch1 (RimWorld.IncidentWorker,RimWorld.IncidentParms)
(wrapper dynamic-method) RimWorld.Storyteller:RimWorld.Storyteller.TryFire_Patch1 (RimWorld.Storyteller,RimWorld.FiringIncident)
RimWorld.IncidentQueue:IncidentQueueTick ()
Hospitality.Hospitality_MapComponent:MapComponentTick ()
Verse.MapComponentUtility:MapComponentTick (Verse.Map)
Verse.Map:MapPostTick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
For testing you can trigger guests via the dev events menu.I can't confirm if you're loading the mod correctly, and I can't really help you right now until I find the time to do more testing.It sounds indeed like you're either loading the wrong version, or it's still broken.If you need a quick solution, you could load the older combat extended version from their github, before they broke it.

**Comment by GreatKingCody** [comment]
@OrionFive 

Should I try stripping Hospitality to see if I can get rid of older versions. I am going to uninstall the steam version completely, my game is acting like it wants to load an older version. Damnit CE devs stop fucking with my mods.

**Comment by OrionFive** [comment]
The important bit is to clear out the workshop folder where the mods are downloaded to. Sometimes a mod folder doesn't update correctly.

By the way, the new Hospitality version that addresses this issue is now on Steam.

I'm gonna close this for now. So respond if the issue persists.
