### ISSUE TITLE
Hospitality: Guest room error

### ISSUE THREAD

**Issue by MinhQuan-Tran** [OrionFive/Hospitality#616]
**Description**
The guest cannot pay for the bed even though they have enough silver. They can still pay for food and weapons. I only have those guest rooms in the images below. This happened after I updated this mod to 1.3.0.8 and 1.3.0.9.

**Console log**
https://gist.github.com/41c352a90468af06302f1b92ff2fea4a

**Debug log**
https://shrib.com/#Louie6bBAmn1

**Screenshots**
![image](https://user-images.githubusercontent.com/62203526/133925115-9eae4a02-5acb-4096-9399-d5e27d8f085c.png)
![image](https://user-images.githubusercontent.com/62203526/133925172-2f3c4f04-3f65-4853-8eb2-69f2698aa750.png)

**Comment by OrionFive** [comment]
This is a conflict with Vanilla Interactions Expanded. I've tried to create a fix ([get it here](https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip)), but I'm afraid it's probably on their end. I don't see how version 1.3.0.9 would cause this.

Please let me know if this solves the issue or it persists.

**Comment by MinhQuan-Tran** [comment]
The file you gave me works!

**Comment by OrionFive** [comment]
Great, then I'll roll it out with the next Steam update, whenever they will be.
