### ISSUE TITLE
Hospitality: Issue with Geth HAR Race

### ISSUE THREAD

**Issue by brucethemoose** [OrionFive/Hospitality#617]
**Describe the bug**
Error in log when a guest from this mod attempts to buy something: https://steamcommunity.com/sharedfiles/filedetails/?id=1819987395

I am 99% sure this bug is related to the fact that Geth cant eat or consume drugs. I've gotten various other errors related to this, in caravan selection and just in general with unrestricted policies, hence this should be a low priority fix. Nevertheless, it seems to be Hospitality erroring out here.

**To Reproduce**

1. Run HAR, the Geth mod and Hospitalitry, get a Geth guest to attempt to buy food or drugs.

**Console log**
See attachment, though its not really necessary.

**Error stacktrace**
https://paste.ee/

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development
[Player.log](https://github.com/OrionFive/Hospitality/files/7200069/Player.log)
.

**Comment by OrionFive** [comment]
The link to the stacktrace isn't valid. Also you got tons of other errors, so it's practically impossible to tell what actually causes the issue.

**Comment by brucethemoose** [comment]
Yeah, I'll try to repro and post an isolated test case log. Just gonna take some time.

**Comment by brucethemoose** [comment]
@OrionFive Sorry for the wait, here's a much more concise log:

https://gist.github.com/HugsLibRecordKeeper/6e3ed36a5da18f66a13b58b88195f36b#file-output_log-txt-L346-L352

Repro steps: make a colony with the geth mod and hospitality loaded, make a shopping area with some food, spawn in a geth visitor group. 

I attached a zip of the save that produced that log.

[Hospitality+Geth.zip](https://github.com/OrionFive/Hospitality/files/7255136/Hospitality%2BGeth.zip)

**Comment by OrionFive** [comment]
Thanks. I've made an attempt at a fix, which you can download here: https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip
It goes into your RimWorld/mods folder, and you have to make sure that you load this version and not the Steam version.

Let me know if that solves the issue or if it persists.

**Comment by brucethemoose** [comment]
Seems to be fixed, thanks! 👍 

I coincidentally ran into another error I've never seen. I see hospitality in the stack trace, but I'm not sure if its actually involved:

https://gist.github.com/HugsLibRecordKeeper/efd90a9a3eb08352806c323b4f9b1c3c#file-output_log-txt-L328-L332

`Geth has no rest need
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Log:ErrorOnce (string,int)
Hospitality.JobGiver_Sleep:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Hospitality.ThinkNode_FilterGuestRooms:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
RimWorld.ThinkNode_Duty:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
RimWorld.ThinkNode_JoinVoluntarilyJoinableLord:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob (Verse.ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()`


Same save as above.

**Comment by OrionFive** [comment]
Yeah, I kind of figured this was just the tip of the iceberg. I didn't know they also don't sleep, though.
I'll make a new fix when I find the time.

**Comment by brucethemoose** [comment]
Appreciate it. 

They don't eat, sleep, take drugs, get sick or wear anything. They *can* lay down to get medical care, and they can socialize, but many regular thoughts are disabled... I think that about covers it as far as Hospitality is concerned?

Those are all XML options in the HAR race def I think, so theoretically other races could run into a similar issue.

**Comment by OrionFive** [comment]
That's a lot. I wonder if they should even be potential guests then. I'll guess we'll have to take it one by one, because I think this will break at every possible corner.

**Comment by brucethemoose** [comment]
Yeah, automatic (or even manual) blacklisting would be tricky if that's what your talking about? There are other (often xml-only) HAR races that can't take drugs, or don't sleep and so on, the Geth just happen to be a race with all those switches flipped at once. Sometimes those races are mixed in with other factions, or spawn in via allied support, which means they can still end up as visitors even if you blacklist the faction AND the race from spawning visitor groups.

Logically, Geth guests make sense to me. They're a potentially friendly faction, they work around the base and socialize, they just don't need beds or food. But technically I'm sure that throws many of Hospitality's assumptions out the window.

**Comment by OrionFive** [comment]
Hmm... Yeah. Well, I don't have the time to test it myself until it's good, but I'm willing to patch the stacktraces you submit here one by one when I get around to it.

**Comment by brucethemoose** [comment]
Yep, I'll test any fixes you push to the develop branch and post new stacktraces as they come up.

**Comment by OrionFive** [comment]
Alright, here's a new version: https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip
I've checked for other needs, but most cases seem to be covered nicely.
