### ISSUE TITLE
Hospitality:Guest has nothing to eat

### ISSUE THREAD

**Issue by mumusomem** [OrionFive/Hospitality#618]
**Describe the bug**
When androids from android tiers comes as a guests some will be unable to eat, despite food and charging stations being available, I believe it may be an issue with the charging stations.

**To Reproduce**
1. Select '...'
3. Open '....'
4. This happens

**Console log**
https://gist.github.com/dd8e4a43e9d098fdbe304c16dbc9ede3

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Ah yes. The damn androids. Thanks for reminding me.

**Comment by OrionFive** [comment]
I've looked through the log but I can't find anything I can do about it. It does look very broken, though. So you may have more than one conflict. Sorry, I don't think I can fix this from my end.
