### ISSUE TITLE
mod caused De-sync on Multiplayer+Mpc 

### ISSUE THREAD

**Issue by deltaforcestron** [OrionFive/Hospitality#623]
from discord posted by Xanth1Man 

Why: Visitor events will trigger a desync loop shortly after arriving to a player-owned colony. It is believed the cause for the desync is because of how guests are interacting with the colonists or the environment, or due to not being able to eat. The desync tick has consistently involved guest pawns from the mod. Below is the trace when it happened. This was tested with the mod + MP + MP compat alone in a brand new save and still caused issues.

please take time and look into it 
my gf cant play this game without your mod btw haha keep up good work sir.

**Comment by OrionFive** [comment]
Hmm... I'd need that stacktrace too.

**Comment by deltaforcestron** [comment]
alright i will get it for ya

**Comment by deltaforcestron** [comment]
Trace of first desynced map random state:
1125 Tick:33117 Hash:-1963625680 'Human98998 Xanth1Man's faction 31 3539123 '
at Multiplayer.Client.Desyncs.DeferredStackTracing.Postfix () <0xffffffff>
at (wrapper dynamic-method) Verse.Rand.Verse.Rand.get_Value_Patch1 () <0xffffffff>
at RimWorld.PreceptComp_UnwillingToDo_Chance.MemberWillingToDo (RimWorld.HistoryEvent) <0xffffffff>
at RimWorld.Ideo.MemberWillingToDo (RimWorld.HistoryEvent) <0xffffffff>
at RimWorld.IdeoUtility.DoerWillingToDo (RimWorld.HistoryEvent) <0xffffffff>
at RimWorld.PawnUtility.IsTeetotaler (Verse.Pawn) <0xffffffff>
at (wrapper dynamic-method) RimWorld.FoodUtility.RimWorld.FoodUtility.TryFindBestFoodSourceFor_Patch2 (Verse.Pawn,Verse.Pawn,bool,Verse.Thing&,Verse.ThingDef&,bool,bool,bool,bool,bool,bool,bool,bool,bool,RimWorld.FoodPreferability) <0xffffffff>
at Hospitality.Utilities.FoodUtility.GuestCanSatisfyFoodNeed (Verse.Pawn) <0xffffffff>
at Hospitality.ThoughtWorker_HasNoFood.GetStateToCache (Verse.Pawn) <0xffffffff>
at Hospitality.ThoughtWorkerCached.CurrentStateInternal (Verse.Pawn) <0xffffffff>

is this what you wanted ?

**Comment by deltaforcestron** [comment]
and this is console log
https://gist.github.com/a6761e377d9a6cf32f458d0f9edd9e5b

what i did is i opened the game from 2 pc (different network) 
played time is like 2 mins (i already set up the scene where guest about to eat the meal)

what happens everytime(almost) is when guest sit down and eating after he finished his meal game instantly desync 
why i said almost
there are sometimes like 1 out of 10 times that they can finished their meal
and will desync at sometimes later

and also i tried rollback to older version of your mod 2-3 versions older it still happens

**Comment by deltaforcestron** [comment]
i uploaded host_trace , local_trace aswell in case u needed it 
https://justpaste.it/4mskt
https://justpaste.it/1yhsh

**Comment by OrionFive** [comment]
I'm not sure how to fix it. I'm gonna see if I can find help for this one.

**Comment by deltaforcestron** [comment]
hey wanted u to know  , thank you very much man really 
there are many people in multiplayer community that really cant live without your mod 
and they are dying for it haha me included especially my gf 

thanks for taking your time on this have a good day

**Comment by notfood** [comment]
Please, test with Hospitality alone. The hugslib log is full of errors from Dubs Bad Higiene that break the AI and consequently the tracking of the MP ticks. The host_trace and local_trace contain no Hospitality and seem different from the snip shared earlier. Get us a save/traces that can be reproduced that only has Multiplayer+Hospitality.

**Comment by deltaforcestron** [comment]
here u go just only your mod , and mp compatibility 
took a while before desync tho not instantly after finish a meal
i am not sure what caused it i tried to look for something strange when guest doing activities but i didnt catch one

host
https://justpaste.it/7eqmu
local
https://justpaste.it/6ziax

and thank you so much for trying to help man. sorry about lately reply

more details
i started up a new save with only your mod and compa
i used debug for create a base and spawn some 10 visitors , 5 visitors per time
the base has 4 simple bed , 1 double bed 
4 beds need to pay , 1 for free
i tried to mimic my old base such as have a place for grow some crops
dinner room and dinning table outside the house  for guests as well
and a farm with horses , muffalo
then i made the zone for guest to allowed them to walk through all these area i mentioned
it went well for the first group they came , ate , slept , bought some meals , ate inside , outside and gone 
the second group tho
i didnt watch i just left the game opened
for about 8 mins i think and game just desync
this is all i have wish i can be helpful more

**Comment by notfood** [comment]
Thanks, it's very clear now.

**Comment by OrionFive** [comment]
@notfood Have you had the chance to look into this yet?

**Comment by deltaforcestron** [comment]
any updates  ? : )

**Comment by notfood** [comment]
I have experimented some, I can't pin point the source of the issue yet. I hope Zetrith notices :eyes:

**Comment by OrionFive** [comment]
> I hope Zetrith notices 👀

Have you notified him? If not, I can do that.

**Comment by deltaforcestron** [comment]
thanks for helping guys

**Comment by deltaforcestron** [comment]
hey any progress ? 
btw me and my gf stopped playing the game ever since mod stopped working
so i might not be here anymore sorry about this 
thank again have a nice day

**Comment by OrionFive** [comment]
@deltaforcestron, I've released a new version with a fix that addresses this issue. Unfortunately, it's a shot in the dark. Would you test it and let us know if it resolves the issue?
Do make sure to restart Steam so it's properly updated.

**Comment by deltaforcestron** [comment]
hi i just redownloaded the game updated to the latest version and tested it for you
so with only Hospitality mod installed my game has no issues so far as i can tell been going for many days now
while testing it i spawned in many different siturations as such , generating quest , caravan , trading , visitors and so on

btw can you please take a look at your other mod

when i tried with your other mod (Gastronomy Latest Version + mp Compat) with or without Hospitality 
the game Desync everytime when pawn go to wait for guest at Cash Table 
hope u can look into it it was working fine back then but now something broken it

Host,Local Trace  , logs here
https://paste-bin.xyz/11494
https://paste-bin.xyz/11495
https://paste-bin.xyz/11496

**Comment by OrionFive** [comment]
That's good to hear. Then this case is finally resolved. 

Gastronomy is not multiplayer compatible and I'm not planning to make it so.
