### ISSUE TITLE
Can't Interact with Merchant Caravans

### ISSUE THREAD

**Issue by phoenix559** [OrionFive/Hospitality#624]
For some the merchant in the caravan doesn't get the yellow "?" over it's head. I'm assuming other npc's that have a "?" may also be affected. It's one of four mods (the other two being a mod manager, Harmony and Hugslib) I tried unsubbing and resubbing and it didn't fix the issue. Here's the log:

https://gist.github.com/c840ed741de73a22b61d6a82dae12ee9

**Comment by OrionFive** [comment]
Somehow you're loading an outdated version of Hospitality. Maybe unsubscribe it, delete the Hospitality folder in Steam\SteamApps\workshop\content\294100 (no idea what the number is, you'll have to search), and subscribe to it again.

**Comment by phoenix559** [comment]
how odd. Thanks, for the quick reply.
