### ISSUE TITLE
Hospitality - 

### ISSUE THREAD

**Issue by docssy** [OrionFive/Hospitality#625]
Well.. i borked the title, but it's a bug report!

On loading:

> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at Hospitality.DefsUtility+<>c.<CheckFactionDefs>b__2_1 (RimWorld.PawnGroupMaker pgm) [0x00000] in <30fe676ee2134c1abfb8c0f3d3d81b66>:0 
>   at System.Collections.Generic.List`1[T].FindIndex (System.Int32 startIndex, System.Int32 count, System.Predicate`1[T] match) [0x0003b] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.Collections.Generic.List`1[T].FindIndex (System.Predicate`1[T] match) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at Verse.GenCollection.Any[T] (System.Collections.Generic.List`1[T] list, System.Predicate`1[T] predicate) [0x00000] in <3f8399aa16fa418f9dff5e3ec4ac6fc6>:0 
>   at Hospitality.DefsUtility.CheckFactionDefs () [0x00042] in <30fe676ee2134c1abfb8c0f3d3d81b66>:0 
>   at Hospitality.DefsUtility.CheckForInvalidDefs () [0x00005] in <30fe676ee2134c1abfb8c0f3d3d81b66>:0 

 

During gameplay, hundreds of these lines **_with or without_** guests on the map:

> SOYUZ:[NOTSOYUZ] Soyuz caught an error while a pawn is ticking. Soyuz probably didn't cause it since this is just used to catch the exception and reset the state. Unless Soyuz is in the StackTrace it's not it. with error System.ArgumentNullException: Value cannot be null.
> Parameter name: type
>   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00003] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.Activator.CreateInstance (System.Type type) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at RimWorld.InteractionDef.get_Worker () [0x00008] in <3f8399aa16fa418f9dff5e3ec4ac6fc6>:0 
>   at Hospitality.Patches.Pawn_InteractionsTracker_Patch+TryInteractRandomly+<>c__DisplayClass0_1.<Replacement>b__0 (RimWorld.InteractionDef x) [0x00019] in <30fe676ee2134c1abfb8c0f3d3d81b66>:0 
>   at Verse.GenCollection.TryRandomElementByWeight[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] weightSelector, T& result) [0x0001f] in <3f8399aa16fa418f9dff5e3ec4ac6fc6>:0 
>   at Hospitality.Patches.Pawn_InteractionsTracker_Patch+TryInteractRandomly.Replacement (RimWorld.Pawn_InteractionsTracker __instance, System.Boolean& __result, Verse.Pawn ___pawn, System.Collections.Generic.List`1[T] ___workingList, System.Int32 ___lastInteractionTime) [0x0010e] in <30fe676ee2134c1abfb8c0f3d3d81b66>:0 
>   at (wrapper dynamic-method) RimWorld.Pawn_InteractionsTracker.RimWorld.Pawn_InteractionsTracker.TryInteractRandomly_Patch2(RimWorld.Pawn_InteractionsTracker)
>   at (wrapper dynamic-method) RimWorld.Pawn_InteractionsTracker.RimWorld.Pawn_InteractionsTracker.InteractionsTrackerTick_Patch1(RimWorld.Pawn_InteractionsTracker)
>   at (wrapper dynamic-method) Verse.Pawn.Verse.Pawn.Tick_Patch6(Verse.Pawn)
> UnityEngine.StackTraceUtility:ExtractStackTrace ()
> (wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
> RocketMan.Logger:Debug (string,System.Exception,string)
> Soyuz.Patches.Pawn_Tick_Patch:Finalizer (Verse.Pawn,System.Exception)
> (wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch6 (Verse.Pawn)
> Verse.TickList:Tick ()
> (wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch6 (Verse.TickManager)
> Verse.TickManager:TickManagerUpdate ()
> (wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
> Verse.Root_Play:Update ()

You're going to love me, mod list:
`
  - brrainz.harmony
  - me.samboycoding.betterloading
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - UnlimitedHugs.HugsLib
  - imranfish.xmlextensions
  - firefoxpdm.ResearchableStatUpgrades
  - com.yayo.harfix_yayoAni
  - automatic.gunplay
  - com.yayo.combat3
  - erdelf.HumanoidAlienRaces
  - Roskii.Astoriel
  - Heymyteamrules.BeastManTribes
  - automatic.bionicicons
  - OskarPotocki.VanillaFactionsExpanded.Core
  - Bichang.Kyulen
  - Bichang.WhiteFox
  - latta.fsharp.core
  - neronix17.toolbox
  - roolo.giddyupcore
  - roolo.giddyupbattlemounts
  - roolo.giddyupcaravan
  - roolo.giddyuprideandroll
  - Spino.Megafauna
  - spincrus.dinosauria
  - Dubwise.DubsBadHygiene
  - GT.Sam.GlitterTech
  - akairo.LetsHaveaCat
  - Rooboid.Accessoryhair
  - Rooboid.Royalhair
  - Usgiyi.SlaveOutfits
  - Nandonalt.SnowyTrees
  - dismarzero.VGP.VGPVegetableGarden
  - Kyrrisayo.WeaponsPlus
  - won2.hair
  - Orion.XevaRimhair
  - rimfridge.kv.rw
  - LWM.DeepStorage
  - JangoDsoul.SimpleStorage
  - Mlie.MoreFactionInteraction
  - Orion.Hospitality
  - Albion.SparklingWorlds.Full
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFESpacer
  - JPT.SoftWarmBeds
  - AIRetexture.Mods
  - vanillaexpanded.achievements
  - VanillaExpanded.VWE
  - Absolute.Legends.Gunz
  - Absolute.Legends.Hair
  - Alias.DegeneralizeWork
  - syrchalis.traitvalue
  - Gewen.AdditionalTraits
  - Rihlsul.AlbinoFluffies
  - roolo.AlmostThere
  - Mlie.AlphaMuffalo
  - Ameiro.Animehairs
  - ACPteam.ACPVanillaStyle
  - Fluffy.AnimalTab
  - AIRetexture.Plants
  - VanillaExpanded.VTEXE
  - cucumpear.azrael.varietycoats
  - Oblitus.AnimalsLogic
  - Revolus.AnimalsAreFun
  - DimonSever000.ApparelTab.Specific
  - Inglix.ApparelTaintedOnCorpseRot
  - Shinzy.Apparello
  - Fluffy.AreaUnlocker
  - sirrandoo.armoredimplants
  - Mlie.ArrowPlease
  - Vazrua.Attuned
  - automatic.autolinks
  - pointfeev.bedassign
  - falconne.AFF
  - Alex.BIRDUP.Budgerigar
  - Alex.BIRDUP.Cockatiel
  - Alex.BIRDUP.Macaw
  - Alex.BIRDUP.Peregrine
  - Alex.BIRDUP.Raven
  - Alex.BIRDUP.Vulture
  - Baby.Muffalump
  - DimonSever000.BackstoriesPlus.Specific
  - neceros.balancedeclipseandsolarflare
  - Mlie.BargainTweaks
  - dey.Beasts.of.the.Rim
  - Meltup.BeautifulOutdoors
  - ToddEStan.BeaversEverywhere
  - lbmaian.begonemessage
  - Mlie.BestMix
  - CaptainMuscles.Coolandgoodambush
  - Lizard.BetterAnesthetic
  - nephlite.advexplosions
  - BetterHearingMatters.Choosechee
  - madarauchiha.custommapsizes
  - Mlie.BetterRecordsTab
  - BetterTalkingMatters.Choosechee
  - co.uk.epicguru.bettertranshumanists
  - Owlchemist.BetterVanillaMasking
  - sirrandoo.bettersliders
  - Rihlsul.BigFluffies
  - Mlie.XNDNocturnalAnimals
  - Zeitloser.BirdsBeyond.TF
  - Vanya.Tools.BlightedAlert
  - izzimon.blooddries
  - goudaquiche.BloodAndStains
  - me.lubar.BlueprintMaterialDebt
  - zylle.BoomalopesBleedChemfuel
  - Techmago.BootsnStuff
  - rtp.bordercollies
  - deon.borderlandsstorytellers
  - brat.greenthumb
  - Anon.VanillaEmbrasures
  - calamabanana.breachableembrasures
  - Mlie.BrrandPhew
  - nercury.BugCracks
  - Uuugggg.BuildFromInventory
  - Mlie.CamouflageandStealth
  - Mlie.CASCataphractArmour
  - Mlie.CASReconArmour
  - CarnySenpai.EnableOversizedWeapons
  - rimofmadness.callofcthulhu.factions
  - CaptainMuscles.Callouts
  - Nowano.CalloutExtension
  - brrainz.cameraplus
  - bustedbunny.capturethem
  - brrainz.carefulraids
  - Mlie.CaridionArsenal
  - CaptainMuscles.CategorizedBills
  - ChargedWeaponsForPirates.velcroboy333
  - 5katz.CommsChat
  - Owlchemist.CleanPathfinding
  - Mlie.ClearTheStockpiles
  - SinaKpaa.CloseQuartersCombatBrutality
  - iemanddieabeheet.colonistsdeco
  - Fluffy.ColonyManager
  - VanillaExpanded.VAECD
  - purpleyam.colorfulcoats.vaecatsdogs
  - VanillaExpanded.VCEF
  - ReGrowth.BOTR.Core
  - ReGrowth.BOTR.ExtinctAnimalsPack
  - purpleyam.colorfulcoats.hlxdodo
  - purpleyam.colorfulcoats.spinomegafauna
  - purpleyam.colorfulcoats.vaewildlife
  - Odeum.BiomesKit
  - ComigoGames.Biomes.GreaterSwamps
  - ComigoGames.Traders.Grim
  - SpessCarp.CommercialServer
  - Mlie.CommonAilments
  - miyamiya.compressedraid.latest
  - SteveZero.ConditionMatters
  - lc.cookietraitsnocheat
  - azomittle.corners
  - Jewsader.Cossacks.Rimworld_copy
  - costlywalls
  - JangoDsoul.EFT.Apparel
  - Mawy.craftable.eft
  - phomor.CraftingQualityRebalanced
  - jelly.craftsmanship
  - Katavrik.CrashLanding
  - BDew.CremateAutoStrip
  - LegendaryMinuteman.CrikeyItsACroc
  - iexist.crossbows
  - SK.CrudeBionics
  - Doomsday343.traitsplus
  - Proxyer.DESurgeries.DESurgeriesColor
  - CaesarV6.DamageIndicators
  - com.RimWorld.Nales.DampeningBelts
  - deon.darkestrim
  - WiseClock.AC.DaysMatter
  - DeadGoatWeapons.velcroboy333
  - Mlie.DeafnessBlindness
  - Avibotz.DedicatedRecipesBC
  - Mlie.DeepStoragePlus
  - UnlimitedHugs.DefensivePositions
  - Merthsoft.DesignatorShapes
  - Fluffy.DesirePaths
  - CaptainMuscles.DesperateHunger
  - AveryTheKitty.DevilstrandAnimals
  - Mlie.DingOnGameLoaded
  - pyrce.dire.raids
  - forestfey.DireWolf
  - DimonSever000.DiseasesPlus.Specific
  - Mlie.DismissTrader
  - Mlie.DisplayCases
  - brat.diversitydiscrimination
  - gguake.ai.dsfi
  - Lucifer.Dormitories
  - telardo.DragSelect
  - CaptainMuscles.DropInventory
  - Adda.DropOnWaterRevived
  - Mlie.DrugPolicyFix
  - Mlie.DrugResponse
  - Dubwise.DubsApparelTweaks
  - avilmask.CommonSense
  - Dubwise.DubsBreakMod
  - UnlimitedHugs.AllowTool
  - Dubwise.DubsMintMenus
  - Dubwise.DubsPerformanceAnalyzer
  - zylle.Ducks
  - Dumbs.Dumbs'Dachshunds
  - nilchei.dynamicdiplomacy
  - Flyingstar.EelementalChargeBlaster
  - zylle.Elephants
  - TaosChagic.EmergencyFire
  - Mlie.Emporium
  - Murmur.EnemySelfPreservation
  - Erin.Chocobos
  - Erin.Foxsquirrel
  - Erin.Ferret
  - Erin.Hairredux
  - Erin.HotDrink
  - Erin.LizzardDoggo
  - Erin.Mountain
  - Erin.Palamutes
  - Erin.Wildlife
  - falconne.BWM
  - Uuugggg.EverybodyGetsOne
  - mcminox.EXOHEAD_copy
  - xedos.arsenalexotic
  - TheGoofyOne.ExoticJoy
  - OskarPotocki.VFE.Mechanoid
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - VanillaExpanded.VWEC
  - VanillaExpanded.VWEHW
  - VanillaExpanded.VWEL
  - VanillaExpanded.VWEQ
  - VanillaExpanded.VWEFT
  - Argon.VMEu
  - GamingTesh.EMP
  - Orion.MoreMechanoids
  - Hauvega.Misc.ExplodingMechanoids
  - erdelf.ExportAgency
  - Rick.FCPLaserWeapons
  - Rick.FCPMKSR
  - Rick.FCPFNVPlasmaWeapons
  - Verniy709.FaceDown
  - Qux.factionmafia
  - SineSwiper.FactionBlender
  - Murmur.FactionRaidCooldown
  - Denneisk.FactorialRange
  - Ishill.Fallen_Stars
  - DerekBickley.FalloutShelterVanillaWeaponRetexture
  - Alfinalightmagefalling.fancyrats
  - ilyvion.FarmingHysteresis
  - Bichang.FerianRace
  - MaxJamon.bichang.Ferian.Faction
  - Mlie.FillBackstories
  - Mlie.FindAGunDamnIt
  - Scurvyez.Fireflies
  - warlocksforge.fishtraps
  - Mlie.Flowers
  - Twokay.Plushies.Specific
  - Rihlsul.FluffiesPlushies
  - theeyeofbrows.fluffybreakdowns
  - lockdownx7.forbidblueprints
  - gguake.fdd
  - VanillaExpanded.VFEPropsandDecor
  - Mlie.FunctionalVanillaExpandedProps
  - Arcangel.WinterHats
  - zylle.Gemstones
  - kikohi.jewelry
  - bg.gfj
  - sarg.giddyupsaddles
  - Certainty.GlitterTech.PolyNerf
  - Albion.GoExplore
  - spoonshortage.gourimet
  - CaptainMuscles.GrabYourTool
  - automatic.gradienthair
  - void.gradientpack1
  - Meltup.GrandRivers.Reborn
  - Telefonmast.GraphicsSettings
  - Mlie.GrenadesExpanded
  - Mlie.GreyerMorals
  - Delusionist.Grimworld
  - DimonSever000.GunTab.Specific
  - ABC.GunlinkPatch
  - HC.Animal.1
  - HC.Animal.2
  - HC.Animal.3
  - HC.Animal.4
  - HC.Creatures.1
  - HackerLaastad.Moretraits
  - Butterfish.HairModdingPlus
  - sumghai.hamefura
  - MamaHorseteeth.HaresOfTheRim
  - Ogliss.Ykara.HarvestEverything
  - Smuffle.HarvestOrgansPostMortem
  - Mlie.HarvestingIsPlantCutting
  - thesepeople.RitualAttachableOutcomes
  - arvalaan.HealingRituals
  - GarbageDayIsHereToStay.HeatstrokeCanCauseBraindamage
  - PitchStone.HeavyMeleeWeapons
  - pleccymm.hedgehogs
  - Mlie.HighTechLaboratoryFacilities
  - Arquebus.Hotseat
  - elkyelky.Houseplants
  - Mlie.HuntingRestriction
  - shakeyourbunny.hyena
  - me.lubar.IHaveMaterials
  - RimEffect.Core
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - VanillaExpanded.VFEPower
  - VanillaExpanded.VWENL
  - BTTP.Sergkart
  - Meru.Implants
  - santakat.improvedqualityscaling
  - Mlie.IncreasedDodgeChance
  - yy_Industrial_Defense_Turrets
  - iexist.industrial.melee.weaponry
  - notfood.Infused
  - latta.infusion
  - Haecriver.InjuredCarry
  - catachat.inspirationtweaks
  - V1024.EBFramework
  - vat.epoeforked
  - 004GP.InternalArmorPlatesEPOE
  - Energistics.ItemTemperature
  - InsertKey.ItemListSelector
  - Fuglypump.JobSplitter
  - nestofmoon.jobslimittweak
  - SalmonToastie.JointBattles
  - Mlie.JurassicRimworldDinosaursOnly
  - Dorely.EmergencySurgery
  - Mlie.KilledEnemyAutoAllowed
  - kahdeg.Killfeed
  - KIT.IndustrialWeapons
  - OskarPotocki.VFE.Insectoid
  - OskarPotocki.VFE.Vikings
  - KIT.VFEWeapons
  - LWM.FuelFilter
  - LWM.MinorChanges
  - newcolonist.largefactionbases
  - Kushiyaki.LastVisited
  - Mlie.LegacyArk
  - zhrocks11.letstrade
  - Buggy.RimWorld.LetterPermanentInjury
  - Troopersmith1.DeathRattle
  - Troopersmith1.LifeSupport
  - juanlopez2008.LightsOut
  - lanilor.lootboxes
  - MrKociak.LootBoxNoCraft
  - D4egon.MagicWand
  - MakeButcherTablesFromStone.velcroboy333
  - dismarzero.VGP.Mamuffalo
  - riprusse.manhair
  - RaZim.ZGFMartens
  - Onkelflo.MaxGainCapRemoval
  - leion247138.MedicalHIV
  - sarg.alphaanimals
  - MSE2.Core
  - Fluffy.MedicalTab
  - Uuugggg.MelaninMatters
  - ThePatchWorkHoax.MeleePsycasts
  - ac.mw.sad
  - BigVeech.MetalsTrader
  - avilmask.MicroDesignations
  - Haplo.Miscellaneous.Training
  - Haplo.Miscellaneous.WeaponRepair
  - antaioz.modmedicinepatch
  - name.krypt.rimworld.moddiff
  - modsyncrw.kv.rw
  - Mlie.MoloyTraits
  - Owlchemist.Moonlight
  - Stolij.MoreBatteries
  - OskarPotocki.VanillaExpanded.RoyaltyPatches
  - Mlie.MoreFurniture
  - Mlie.MoreGraphs
  - RelaxedOtter.MoreInspirationTypes
  - Kas.FrenzyTime
  - Gunmar.MoreJackets
  - 4loris4.MoreLinkables
  - Techmago.MoreMedications
  - Gunmar.MoreMeleeWeapons
  - Mlie.MoreMentalBreaks
  - noodlesking.MorePsycasts
  - Jaxe.MoreRandomSeeds
  - JEMLPro.MoreRealisticTraits.Specific
  - Sinnamon.MoreRitualRewards
  - overblaze.morescars
  - Bichang.MoreSculpture
  - SGC.moreutilitypacks
  - Jiopaba.Fences
  - Jiopaba.FenceTab
  - Glacial.CowVarity
  - Mlie.MultipleRaids
  - Oblitus.MyLittlePlanet
  - Mlie.MyRoomIWantThat
  - NackbladInc.Rimhair
  - wit.namesgalore
  - AmCh.needBarOverflow
  - brrainz.achtung
  - netrve.dsgui
  - Mlie.NewJoySourcePlayMusic
  - Mlie.NewLimbsNeedsTraining
  - nilchei.personalitytrait
  - ordpus.noexplosiononslaughter
  - Doug.NoJobAuthors
  - JBloodthorn.NoLazyDoctors
  - CaptainMuscles.NoPawnLeftBehind
  - CarbonTNT.noselftame
  - AlexisPopcorn.NoSpouses
  - Mlie.NoVersionWarning
  - Ogre.OgreStack
  - VanillaExpanded.VCookE
  - seohyeon.OptimizationMeats
  - com.bymarcin.ArchitectIcons
  - proxyer.optionalicons4ai
  - gguake.optionalnamedisplay
  - ApatheticSlug.OrbitalBionicsTrader
  - notfood.Outfitted
  - com.RimWorld.Nales.OvercappedAccuracy
  - zylle.Parrots
  - fed1sPlay.PawnTargetFix
  - pointfeev.fireextinguisher
  - 123nick.PawnsAreDrowning
  - Cozarkian.PawnsChooseResearch
  - battlemage64.PeopleCanChange
  - dninemfive.pepinyourstep
  - Mlie.PermanentEnemiesNeverFlee
  - Owlchemist.PerspectiveDoors
  - Owlchemist.PerspectiveTrees
  - Mlie.Pirates
  - usagirei.pocketsand
  - Mlie.PonytailIsKawaii
  - bg.PIIMP
  - Simmin.PowerTools
  - Zezz.PandM
  - falconelaris.preceptsplusplus
  - bustedbunny.PrisonersAreNotSwines
  - Mlie.PrisonersDontHaveKeys
  - Mlie.PrisonersShouldFearTurrets
  - Kyrrisayo.ProjectArmoryUnofficial
  - itzal.fortuna.base
  - itzal.fortuna.heavy
  - itzal.fortuna.laser
  - itzal.fortuna.pack
  - K.PsiTech
  - DimonSever000.PsionicPlus.Specific
  - avilmask.PsychicHarmonizerLagFix
  - psychicshipscanaffectfemales.1trickPonyta
  - RebelRabbit.QualityBionics
  - legodude17.qualcolor
  - SteveZero.QualityDoors
  - Phlivan.QualityMatters
  - SGC.quests
  - Sandy.RPGStyleInventory.avilmask.Revamped
  - Rah.HardcoreArmors
  - Rah.RVTE
  - Yoann.RaidingWorthwhile
  - Uuugggg.RandomResearch
  - hatena.RangeAnimalFramework
  - Mlie.Rats
  - n7huntsman.razorwire
  - mosi.RGWeatherRebalanced
  - Woolstrand.RealRuins
  - Mlie.RealisticHumanSounds
  - Verniy709.RealisticHumanSounds.HARPatch
  - VanillaExpanded.VBrewE
  - VanillaExpanded.VBrewECandT
  - ReGrowth.BOTR.AspenForest
  - VanillaExpanded.VPlantsE
  - RealPlantCycles.velcroboy333
  - Yoann.RealisticProstheticsExpansion
  - Lucifer.RealisticRooms
  - Mlie.Rebound
  - Jaxe.RimHUD
  - automatic.recipeicons
  - Bichang.RedDragon
  - pausbrak.redwolves
  - AveryTheKitty.RefinedFloors
  - overblaze.reikarabidstorytellercont
  - cousinnic.reinforcedstructures
  - Mlie.ReleaseWhenHealthy
  - BEKKITT.ReliableUshanka
  - weilbyte.renamecolony
  - Imranfish.ResearchForDeepStorage
  - VinaLx.ResearchPalForked
  - Vakaria.RespectScars
  - rtp.rhodesianridgebacks
  - RimEffect.ExtendedCut
  - RimEffect.N7
  - rimeffect.themistraders
  - GhostRolly.Rim73
  - Aoba.GeryKnights
  - sumghai.RimNGE
  - RadZerp.neoRimNauts
  - aRandomKiwi.RimSaves
  - Sierra.RT.GeneralTraits
  - Sierra.RT.MedievalTalents
  - Mlie.RimUniverseCoreModule
  - Mlie.RimUniverseBiomes
  - Velcroboy333.Rimmunizations
  - Mlie.Rimperion
  - rimsenal.EVP
  - Vocado.RitualTab.Rimworld
  - ArmoredAmpharos.RodentPack
  - Mal.RodentsOfUnusualSize
  - Mlie.Roofminer
  - OrionTHGOPNITHMilSuUpZaTHSpoonshortageTHRooboidTHJIUWonTHrooki1149.RudiOsHHairHPiracy
  - Mlie.RuinedIsUnfertilized
  - Mlie.RunAndHide
  - roolo.RunAndGun
  - trinity.RuntimeGCupdated
  - Uuugggg.SafelyHiddenAway
  - brrainz.samespot
  - Revolus.Compressor
  - Mlie.Scarification
  - Owlchemist.ScatteredStones
  - thisisaprofilename.SearchOnOpen
  - roolo.SearchAndDestroy
  - Mlie.SeasonalWeather
  - Supes.SelectedReconnector
  - dninemfive.settlementdescription
  - Uuugggg.ShareTheLoad
  - Mlie.ShelfRenamer
  - Fluffy.ShitRimWorldSays
  - Mlie.ShowMeYourHands
  - Mlie.SiltsRadio
  - automatic.traderships
  - Owlchemist.SimpleFX.Smoke2
  - tostov.simpleindustrialfactions
  - Mlie.SimpleRacesDwarfs
  - Owlchemist.WallUtilities
  - Mlie.SimplyMoreBridges
  - isorex.communityframework
  - turnovus.morebionicimplants
  - bustedbunny.SlaveRebellionsImproved
  - Beast.SlowStarvation
  - Uuugggg.SmartMedicine
  - dhultgren.smarterconstruction
  - weilbyte.snapout
  - ArmoredAmpharos.SnowRats
  - Cozarkian.SoftWarmBedsRebalanced
  - sirrandoo.msf
  - marvinkosh.sometimesraidsgowrong
  - Mlie.SpidercampsDogPack
  - KasmexForever.SpookyScarySkeletons
  - spoonshortage.spoonshairmod
  - Mlie.SquadUITweaks
  - Linkolas.Stabilize
  - zylle.StandYourGround
  - StatsMatter.velcroboy333
  - tammybee.statueofcolonist
  - neceros.stopinsultingus
  - Mlie.StorytellerEnhanced
  - strangerinblack.1trickPonyta
  - Simmin.StuffonTables
  - Mlie.Suppression
  - Mlie.SupremeMelee
  - RSev.SynergisticTraits
  - Cev.TIIWeapons
  - Mlie.TabSorting
  - antaioz.tdiner
  - Karvinen390.TablesS
  - ucp.TabletopDecorations
  - balistafreak.TacticalExtremityProtection
  - GwinnBleidd.ResearchTweaks
  - Revolus.TextileStats
  - Mlie.TheyreInTheTrees
  - Uuugggg.ThickArmor
  - Mlie.Thingamajigs
  - bustedbunny.throwthem
  - bob.ticksPerSecond
  - Jaxe.ToggleHarvest
  - reiquard.tooltippedlongnames
  - TimmyLiang.TradeHelper
  - CarnySenpai.TraitRarityColors
  - DanielCoffey.TraitsCorpseHandling
  - Isuzuki.TraitsExcel
  - 1234wsx.traitsexpanded
  - Side1iner.TraitsPlus
  - TreeChoppingSpeed.velcroboy333
  - Two.NoWooshDoors
  - marvinkosh.ughyougotme
  - syrchalis.harvestyieldpatch
  - Grimm.Unlimited
  - Owlchemist.UndergroundPowerConduits
  - madarauchiha.undraftaftertucking
  - Uuugggg.UseBedrolls
  - dhultgren.useminifiedbuildings
  - Mlie.MedicalSupplements
  - Mlie.UtilitySupplements
  - VAEBootsandGloves.OnSkinPatch
  - isorex.mechanoidsaddon
  - seos.vfe.mechanoids.drones
  - Hol.VFESterile
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAECaves
  - VanillaExpanded.VAED
  - VanillaExpanded.VAEEndAndExt
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAETF
  - VanillaExpanded.VAETR
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAET
  - VanillaExpanded.VBooksE
  - VanillaExpanded.VCookEStews
  - VanillaExpanded.VCookESushi
  - VanillaExpanded.VEE
  - OskarPotocki.VanillaExpanded.IdeologyPatches
  - qux.factionexpanded.bettertexturesandpawnkinds
  - VanillaExpanded.VCEFAddon
  - VanillaExpanded.VFEArchitect
  - VanillaExpanded.VHE
  - VanillaExpanded.VHE.Beards
  - VanillaExpanded.VIEHAR
  - VanillaExpanded.Ideo.IconsandSymbols
  - VanillaExpanded.Ideo.RelicsAndArtifacts
  - VanillaExpanded.VIESAS
  - VanillaExpanded.VPlantsESucculents
  - zodgilla.vanillarangedretexture
  - VanillaExpanded.VanillaSocialInteractionsExpanded
  - VSE.DiegoIndustrial
  - VSE.EmpressEvil
  - VSE.FreyaFierce
  - VSE.IgorInvader
  - VSE.MaynardMedieval
  - VSE.NeronNeolithic
  - VSE.OskarObnoxious
  - VSE.PerryPersistent
  - VanillaExpanded.VWEG
  - VanillaExpanded.VWEMS
  - Mlie.VanillaFriendlyTraitExpansion
  - Cozarkian.VanillaTraitsRebalanced
  - Edge.VarietyHair
  - Mlie.VarietyMattersImproved
  - Mlie.VegetableGardenLite
  - Mlie.WaSkeleton
  - bustedbunny.wakeup
  - CarnySenpai.WeaponQualityIndicators
  - bodlosh.WeaponStats
  - Lakuna.WellMet
  - FluffyKittens.WhatThePatch
  - co.uk.epicguru.whatsthatmod
  - Mehni.PickUpAndHaul
  - CodeOptimist.JobsOfOpportunity
  - CaptainMuscles.WhoNext
  - jelly.WildCultivation
  - WildPokemon.velcroboy333
  - 2563745334
  - Fluffy.WorkTab
  - zylle.MoreVanillaBiomes
  - Odeum.WMBP
  - Carolusclen.DLC.WMBP.mvb
  - WindowsXP.RealisticPlanets
  - Carolusclen.DLC.WMBP.rp
  - laast.WorldMapEnhanced
  - forestfey.SpiritWolf
  - poinl.xtratraits
  - com.yayo.yayoAni
  - sjaak31367.ZoologicalOrbitalTraders
  - sjaak31367.ZoologicalTraderCaravans
  - 04.23.2020
  - lp.levelthisForked
  - varisha.extendedinspectdata
  - walkingproblem.friendliesfightfire
  - 1.3.Odz.Hairs
  - 1.3.Odz.Suits
  - AcidCancer.UpgradeVanillaWeapon
  - CM.SpotsTabMod
  - CZK.DeepStorage.patch
  - VanillaExpanded.VanillaTraitsExpanded
  - dani.moreTraits
  - FrozenSnowFox.BetterAncientComplexLoot
  - FrozenSnowFox.EncounterMapResources
  - Fuu.AutoStripOnHaul
  - VanillaExpanded.VAEAccessories
  - VanillaExpanded.VWETB
  - Fuu.UncompromisingTribalFaction
  - HH.MaterialsForToolCabinet
  - Harkon.GunNut.CORE
  - Harkon.GunNut.GaussRifle
  - Harkon.GunNut.AACHoneyBadger
  - Harkon.GunNut.Chapter1
  - Harkon.GunNut.Chapter2
  - Harkon.GunNut.ColtAnaconda
  - Harkon.GunNut.Community
  - Harkon.GunNut.DTMDRX
  - Harkon.GunNut.FNSCAR
  - Harkon.GunNut.KRISSVector
  - Harkon.GunNut.KSGShotgun
  - Harkon.GunNut.RugerMini
  - Harkon.GunNut.SIGSauerNGSW
  - Harkon.GunNut.SovietSMGs
  - Harkon.GunNut.M97TrenchGun
  - Inoshishi3.CombatSoundsSE
  - JPT.CleanButtons
  - ketaros.textureurns
  - consolidatedtraits.kv.rw
  - factioncontrol.kv.rw
  - moretraitslots.kv.rw
  - supplyanddemand.rw
  - tradingspot.kv.rw
  - DerekBickley.LegacyTerrainOverhaulFinal
  - Nals.RollOver
  - neronix17.ancient.decon
  - neronix17.celestials
  - Mlie.RFTribalPawnNames
  - Mlie.RFTribalRaiders
  - RH2.HandToHand
  - CP.RimmuNation.2.Weapons
  - Ryflamer.Misc.Drawabead
  - Ryflamer.Rimcraft.Animals
  - SR.ModRimworld.FactionalWar
  - SR.ModRimworld.RaidExtension
  - RabiSquare.RealisticOreGeneration
  - BJIS.LovelyHairStyle
  - jelly.syrchalis.bulletcasings
  - TrahsPanda.RaccoonOverhaul
  - TrahsPanda.CBT.CleanButcherTable
  - Telkir.TMods.ExpandedCrops
  - Telkir.TMods.MoreFloors
  - Wemd.PartiallyPassableWindTurbines
  - Wemd.ReinforcedDoors
  - Wemd.SoilContrast
  - Mlie.XNDAdrenaline
  - Mlie.XNDMemorableAuroras
  - jelly.ProperShotguns
  - Poet.DDExpandedCollection
  - Poet.ATHelixenGas
  - nookii.psyplus
  - Krkr.RocketMan`

**Comment by OrionFive** [comment]
This is a pretty sorry excuse for a bug report. I still need your log.

**Comment by docssy** [comment]
Sorry =)

[Player.log](https://github.com/OrionFive/Hospitality/files/7316644/Player.log)

**Comment by OrionFive** [comment]
This is not a Hospitality issue... Normally I would say this is a lost cause. I wouldn't even know where to start. 

Clear your mod list and start fresh.
And stop adding stuff as soon as you get errors.

Alternatively, start by removing outdated or broken mods. For example, whatever mod adds the artillery, and every mod that is not using a valid package ID anymore. Do that and start a new game, until you don't get errors in the menu or when the game is created.

Good luck!

**Comment by docssy** [comment]
I'm sorry. But I did find the conflicting mod for you. Thank goodness there's a mod button called whats that patch, to dump harmony patches.

Boolean RimWorld.Pawn_InteractionsTracker::TryInteractRandomly()
        (pre)  OskarPotocki.VanillaSocialInteractionsExpanded
        (pre)  Orion.Hospitality

**Comment by OrionFive** [comment]
Hmm.. From the looks of it this has to be fixed on their end.
