### ISSUE TITLE
Hospitality: Can't trade/GUI Window Resized/No Buttons/Error "Exception Filling Window"

### ISSUE THREAD

**Issue by VCMedic** [OrionFive/Hospitality#627]
Hello! First, thanks for your hard work on this mod! I ran into this error today:

**Describe the bug**
- After installing Hospitality, I'm now getting an error when attempting to trade with a visiting caravan
- I think there may be an issue with the sizing of the trade window
- If I click the "i" info button on items in the trade window most of it is cutoff making it unreadable
- There is no button to accept trades (possibly being cutoff at the edge?)
- I get spammed with "Exception filling window for RimWorld.Dialog_Trade..."
- Error mentions something about a plant? Maybe a broken reference to an item/object causing the trader gui to freak out?
- I'm guessing probably a mod conflict
- If I start a new game and force a trader event using the debug menu, I don't get the error. Unsure if this is because it's a fresh game or if it's because that particular trader isn't looking for a corrupt object reference.
- Of note, I have no guest beds or anything else from the hospitality mod set up on the map, this happened 5 minutes after adding the mod
- To my knowledge my load order should be fine and hospitality is last
- Can confirm that removing hospitality resolves the issue

**To Reproduce**
1. Installed hospitality, other mods I have are noted in logs
2. Hospitality is last in load order
3. Right clicked to trade with visiting trader pawn
4. Trader window comes up janky
5. "Exception filling window for RimWorld.Dialog_Trade..." error occurs simultaneously in log

**Console log**
- For simplicity, I pulled out the error I get spammed with (full log is all the way at the bottom)

> Exception filling window for RimWorld.Dialog_Trade: System.NullReferenceException: Object reference not set to an instance of an object
>   at TKKN_NPS.PatchGraphicPlant.Postfix (RimWorld.Plant __instance, Verse.Graphic& __result) [0x00043] in <072b52ac48474986a77eb1b6e616338c>:0 
>   at (wrapper dynamic-method) RimWorld.Plant.RimWorld.Plant.get_Graphic_Patch1(RimWorld.Plant)
>   at Verse.Widgets.ThingIcon (UnityEngine.Rect rect, Verse.Thing thing, System.Single alpha, System.Nullable`1[T] rot) [0x00244] in <b64badbf3c3d41018b3ca5d3e8c77771>:0 
>   at RimWorld.TransferableUIUtility.DrawTransferableInfo (RimWorld.Transferable trad, UnityEngine.Rect idRect, UnityEngine.Color labelColor) [0x00049] in <b64badbf3c3d41018b3ca5d3e8c77771>:0 
>   at RimWorld.TradeUI.DrawTradeableRow (UnityEngine.Rect rect, RimWorld.Tradeable trad, System.Int32 index) [0x00318] in <b64badbf3c3d41018b3ca5d3e8c77771>:0 
>   at RimWorld.Dialog_Trade.FillMainRect (UnityEngine.Rect mainRect) [0x000c2] in <b64badbf3c3d41018b3ca5d3e8c77771>:0 
>   at RimWorld.Dialog_Trade.DoWindowContents (UnityEngine.Rect inRect) [0x003d3] in <b64badbf3c3d41018b3ca5d3e8c77771>:0 
>   at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x001ce] in <b64badbf3c3d41018b3ca5d3e8c77771>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
> 
> GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced. 
> (Filename:  Line: 580)
> 
> Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing. 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Screenshots**

![image](https://user-images.githubusercontent.com/92397673/137014338-0d6f3d60-f03d-4350-9dbe-f986caef0835.png)

Full Log:

https://gist.github.com/37aaf347bda6d892afd5b4376e3a3e46

Thanks for the assistance! Please let me know if you need any more information :)

**Comment by OrionFive** [comment]
I can't see how Hospitality is involved here, but it's pretty clear that another mod is at the root of the issue.
The only reference to it I can find is the namespace, which is "TKKN_NPS".  I have no idea which mod brings it, though. You might be able to find it by searching your downloaded mods folder for that term.

Usually, namespaces are identical to the names of loaded libraries, but here it isn't, so I can't tell you more than that, I'm afraid.
