### ISSUE TITLE
Hospitality: Hunting party Event from VEE creates guests

### ISSUE THREAD

**Issue by Danimineiro** [OrionFive/Hospitality#637]
**Describe the bug**
When a hunting party event gets triggered, there is a high chance that any pawns involved will become guests. 

**To Reproduce**
1. Enable required mods: Harmony, Core, HugsLib, Vanilla Expanded Framework, Vanilla Events Expanded (VEE), Hospitality
2. Using the Debug Menu: Do Incident (Map)...
3. Select VEE_HuntingParty
4. Wait (sometimes it happens instantly, other times some of them already leave, I suppose there is a chance the event finishes before they become guests)

**Console log**
[](https://gist.github.com/57693a5450c709cd7e3705665a92c7ef)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
(There was no error, but this message got spawned for each hunting party pawn)

```
Creating a temporary lord for Maria, Barkeep of faction The Exodus Empire.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Hospitality.Utilities.GuestUtility:CreateLordForPawn (Verse.Pawn)
Hospitality.Utilities.GuestUtility:CheckForRoguePawn (Verse.Pawn,Verse.Map)
Hospitality.Utilities.GuestUtility:CheckForRogueGuests (Verse.Map)
Hospitality.Hospitality_MapComponent:MapComponentTick ()
Verse.MapComponentUtility:MapComponentTick (Verse.Map)
Verse.Map:MapPostTick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26352135/141462879-6f8e875d-7bef-427e-8e21-b23ad977b64d.png)

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
This issue should be fixed now. Thanks for reporting. The fix will be included with the next update on Steam. In the meantime you can use this version: https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip
