### ISSUE TITLE
Hospitality:  The game cannot recognize the nutritional cream dispenser in prison barracks

### ISSUE THREAD

**Issue by xyq565861** [OrionFive/Hospitality#640]
Hello, I encounter a bug about the nutrition cream in my save. I have a prison that uses a nutrient cream maker to provide food. But after I updated the mod, the prisoner suddenly stopped getting the nutrient cream from the machine. And the game determined that I did not provide food to the prisoners, so some food was forced to be stored in it. This may be a conflict or bug, I have other mods also, but this I try to disable this mod, it works again.
log:
https://gist.github.com/HugsLibRecordKeeper/385a799966c729d1d5205d16a8cf61dd
screenshot:
https://ibb.co/2c448Vy

**Comment by OrionFive** [comment]
Thanks, I'll look into it.

**Comment by OrionFive** [comment]
I'm sorry, but I can't reproduce this. It works fine here:
![image](https://user-images.githubusercontent.com/13980562/141684052-239d64bb-7fd2-4730-839e-b7e31223aae8.png)

Your log also doesn't contain anything that would hint towards an error.

**Comment by OrionFive** [comment]
It looks like "Common Sense" and "Torann Magic" also mess with food-related code. So it could be a conflict with one of these.

**Comment by OrionFive** [comment]
I've tried with Common Sense, but it still works.
So it must be circumstantial, or your save game is somehow broken, or something else that I can't find.
