### ISSUE TITLE
Hospitality: Terrain issues on start up.

### ISSUE THREAD

**Issue by Sierra0001** [OrionFive/Hospitality#644]
**Describe the bug**
Loaded up the game and got a whole bunch of yellow warnings related to missing Terrain thingClass showed up. #troubleshooting cannot resolve this, and the stack track trace mentions Hospitality by name

**To Reproduce**
Loading the game with the mod list.

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.](https://gist.github.com/HugsLibRecordKeeper/691eb9f9b97f64fb802138b3bbac17ee)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
ThingDef FromTerrain_Granite_Smooth has no thingClass. This is a misconfiguration in another mod, but the mod name could not be identified (likely a generated def).
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Hospitality.DefsUtility:LogMisconfiguration (Verse.Def,string)
Hospitality.DefsUtility:CheckBedDefs ()
Hospitality.DefsUtility:CheckForInvalidDefs ()
Hospitality.HospitalityModBase:DefsLoaded ()
HugsLib.HugsLibController:OnDefsLoaded ()
HugsLib.HugsLibController:LoadReloadInitialize ()
(wrapper dynamic-method) Verse.LongEventHandler:Verse.LongEventHandler.RunEventFromAnotherThread_Patch0 (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.
![Screenshot 2021-11-22 131115](https://user-images.githubusercontent.com/57948195/142795517-dacc2cf1-dbfe-4b05-92e8-0c567d475372.png)

**Comment by OrionFive** [comment]
In RimWorld every object has a class assigned to it. It is possible for mods to break with this assumption, but this can cause issues with other mods.

Because of this, Hospitality is issuing warnings if such objects are found, so the maker of mod that does it can fix it.

So whichever mod is adding those terrain types is ignoring the convention.
