### ISSUE TITLE
Hospitality: Option to disable Guest danger Warning

### ISSUE THREAD

**Issue by VanGuardner** [OrionFive/Hospitality#648]
**What problem does your suggestion solve**
playing on a cold/hot map and having the game pause everytime a guest tries to enter because of bad temperature gets kinda annoying.

**Describe the solution you propose**
adds an option to disable warning and just automatically let the guest enter the map without ensuring safety

**Describe alternatives you've considered**
maybe an options to only disable certain danger so people that dont want guest to die from enemy raids and stuff can just turn off bad temperature warning instead of all warning.

**Comment by OrionFive** [comment]
Sounds like a good idea. Maybe I'll get around to it one day.

**Comment by OrionFive** [comment]
Done.
