### ISSUE TITLE
Hospitality 

### ISSUE THREAD

**Issue by akkariacher** [OrionFive/Hospitality#652]
**Describe the bug**
Every time a guest comes to visit I get the error "<Pawn Name> did not have work settings initialized 

**To Reproduce**
1. Select "Add Guest" in debug actions menu (or have guest spawn randomly)

**Console log**
https://gist.github.com/6f591d10a9e8ec654d4262e9bf476f23

**Error stacktrace**
Davidson did not have work settings initialized.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
RimWorld.Pawn_WorkSettings:ConfirmInitializedDebug ()
RimWorld.Pawn_WorkSettings:WorkIsActive (Verse.WorkTypeDef)
Blackboard.ITab_BlackboardSchedule:IsTeachingDisabledForPawn (Verse.Pawn,string&,bool)
Blackboard.ITab_BlackboardSchedule:IsTeachingDisabledForPawn (Verse.Pawn)
RimWorld.Area_School:GetPawnHourSchoolCache (Verse.Pawn)
Children.ChildrenHarmony/Pawn_PlayerSettings_EffectiveAreaRestrictionInPawnCurrentMap_Patch:EffectiveAreaRestrictionInPawnCurrentMap_Pre (RimWorld.Pawn_PlayerSettings,Verse.Pawn,Verse.Area&)
(wrapper dynamic-method) RimWorld.Pawn_PlayerSettings:RimWorld.Pawn_PlayerSettings.get_EffectiveAreaRestrictionInPawnCurrentMap_Patch1 (RimWorld.Pawn_PlayerSettings)
(wrapper dynamic-method) Verse.AI.PathFinder:Verse.AI.PathFinder.GetAllowedArea_Patch1 (Verse.AI.PathFinder,Verse.Pawn)
(wrapper dynamic-method) Verse.AI.PathFinder:Verse.AI.PathFinder.FindPath_Patch1 (Verse.AI.PathFinder,Verse.IntVec3,Verse.LocalTargetInfo,Verse.TraverseParms,Verse.AI.PathEndMode,Verse.AI.PathFinderCostTuning)
Verse.AI.PathFinder:FindPath (Verse.IntVec3,Verse.LocalTargetInfo,Verse.Pawn,Verse.AI.PathEndMode,Verse.AI.PathFinderCostTuning)
(wrapper dynamic-method) Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.GenerateNewPath_Patch1 (Verse.AI.Pawn_PathFollower)
Verse.AI.Pawn_PathFollower:TrySetNewPath ()
(wrapper dynamic-method) Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.TryEnterNextPathCell_Patch1 (Verse.AI.Pawn_PathFollower)
(wrapper dynamic-method) Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.PatherTick_Patch3 (Verse.AI.Pawn_PathFollower)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch1 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch2 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
Verse.Root_Play:Update ()

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Looks like a conflict with the Children mod. Not much I can do about it, I think.

**Comment by OrionFive** [comment]
I think I found the particular issue:
Hospitality only uses work settings when it lets guests work. Before that happens, it makes sure they're initialized.
Children, however, uses work settings all the time, even if pawns just walk around, but never initializes them, it just expects them to be there. 
I'll move the initialization to when guests are spawned for the next version. Maybe it'll resolve the problem.
