### ISSUE TITLE
[Core+Hospitality Only] I can't assign a bed to a guest bed

### ISSUE THREAD

**Issue by NFSNOOB** [OrionFive/Hospitality#653]
Problem: I cant assaign a bed to a guest bed after creating a fresh colony.

Overview:
Rimworld Version: 1.3.3200
Harmony: 2.1.1.0

Video:
https://youtu.be/oK0JxiXlGgk

Log
https://gist.github.com/HugsLibRecordKeeper/4e628ad2ce5c4269e2d5e7f65d4db140

Hope it helps (:

**Comment by OrionFive** [comment]
It does. Your Hospitality installation is corrupted.
I recommend clearing out the Hospitality folder and restarting Steam.

Maybe clear out all your downloaded mods and redownload them, if you're at it. Restarting Steam does that automatically if you delete their folders.

If that doesn't help, let me know.
