### ISSUE TITLE
UI Gone

### ISSUE THREAD

**Issue by ghost** [OrionFive/Hospitality#655]
Hospitality seems to break the UI for some reason, I've tried resubscribing to harmony, hugslib and hospitality to no avail. https://gist.github.com/4c9f25fcfea92f99783d943937f775c9

**Comment by ghost** [comment]
I've now reinstalled the game, reset configs and the problem is still occuring. The game works fine without hospitality.

**Comment by OrionFive** [comment]
Does this also happen with a new / different save game? This looks like a broken game state to me. Have you maybe removed a mod mid-game?

**Comment by ghost** [comment]
This also happens when starting a new game, removing Hospitality and only using Harmony & HugsLib works perfectly fine, this only occurs when adding hospitality. It would seem to be related to some kind of name color patch: Hospitality.Patches.PawnNameColorUtility_Patch+PawnNameColorOf.Prefix

**Comment by OrionFive** [comment]
Very odd. I've checked the patch and the only way it can cause an issue is if the game state is broken (a pawn is created missing some reference).

Also, you seem to be the only one so far. So it must be on your end...

**Comment by ghost** [comment]
Odd, I completely deleted the game along with all the configuration files, reinstalled it, downloaded hospitality again and the issue persists. Thanks anyways

**Comment by OrionFive** [comment]
Well, there are plenty of other things that can cause problems. Disabled mods, for example, or junk leftovers in the downloaded mods folder. Or something like running RimWorld on Linux.
