### ISSUE TITLE
Only allowing guests certain foods for free 

### ISSUE THREAD

**Issue by kwesting4** [OrionFive/Hospitality#658]
**What problem does your suggestion solve**
I sometimes have guests with no money and when I turn on free food they take the food I don't allow my pawns to eat (survival meals, pemican, etc. for travel)

**Describe the solution you propose**
An option to allow certain food types for free and mark others as not allowed.

**Describe alternatives you've considered**
I have a prison started (no inmates yet) but have a paste dispenser that i fill with insect and human meat for inmates only, I set it as vending and set price to zero and they won't touch it. Ironically my pawns keep going in and eating it and then getting upset (go figure.)  

PS I do understand I am years late to this game and it's mods and if this has been asked and answered I apologize I was unable to find ref to it. Thnx for any assist and great mod! I'm gonna be forced to buy Royalty just to add a spaceport, I aim to have the best resort on the Rim! 

Adding features takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Probably the prison causes the nutrient dispenser to become forbidden to guests. Or the guest area doesn't entirely include it.

About selecting what guests take: They will only take food inside their area. So make sure food you don't want them to have are outside that area.

For more control, I recommend my other mod, "Gastronomy".
