### ISSUE TITLE
Hospitality: Refuse visitors until beds built fails to unlock

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#659]
Apparently, for some players, it doesn't spawn groups even when beds are built, until the option is disabled again.

**Comment by OrionFive** [comment]
Can't reproduce. Probably other mods are interfering.

**Comment by ThatEngineeringGuy** [comment]
Just started having this problem.  
Had selected to block visitors until I had guest beds.  
When I finally built beds, the "guest" button was not responding.
Debug Error message
Failed to find Verse.ThingDef named SleepingSpotGuest. There are 1866 defs of this type loaded. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Log file. 
https://gist.github.com/598a9106367c3a2b7a4b6edb6dea5c27
-----------------
Log uploaded on Thursday, April 14, 2022, 10:49:08 PM
Loaded mods:
Harmony(brrainz.harmony)[mv:1.1.1.0]: 0Harmony(2.1.1), HarmonyMod(1.1.1)
Core(Ludeon.RimWorld): (no assemblies)
Royalty(Ludeon.RimWorld.Royalty): (no assemblies)
Ideology(Ludeon.RimWorld.Ideology): (no assemblies)
HugsLib(UnlimitedHugs.HugsLib)[ov:9.0.1]: 0Harmony(av:2.1.1,fv:1.2.0.1), HugsLib(av:1.0.0,fv:9.0.1)
Achtung!(brrainz.achtung)[mv:3.3.9.0]: 0Harmony(av:2.1.1,fv:1.2.0.1), 0MultiplayerAPI(av:0.3.0,fv:0.3.0), AchtungMod(3.3.9)
Mad Skills(ratys.madskills)[mv:2.5.0.0]: 0Harmony(av:2.1.1,fv:1.2.0.1), MadSkills(1.0.0)
Prison Labor(avius.prisonlabor): 0MultiplayerAPI(av:0.3.0,fv:0.3.0), PrisonLabor(0.10.8013.41829)
Simple Loom(Techmago.SimpleLoom): (no assemblies)
Shale - from oil to plastic(Techmago.Shale): (no assemblies)
Hospitality(Orion.Hospitality)[mv:1.3.1.4]: 0MultiplayerAPI(av:0.3.0,fv:0.3.0), Hospitality(av:1.0.0,fv:1.3.1.4)
Simple sidearms(PeteTimesSix.SimpleSidearms): SimpleSidearms(1.4.6)
[KV] Trading Spot(tradingspot.kv.rw)[ov:1.3.0.2]: TradingSpot(1.0.0)
Change Caravan Loadout(dhultgren.changecaravanloadout): (no assemblies)
EdB Prepare Carefully(EdB.PrepareCarefully)[mv:1.3.8]: 0Harmony(av:2.1.1,fv:2.0.2), EdBPrepareCarefully(av:1.1.1,fv:1.3.8)
Caravan Adventures(iforgotmysocks.CaravanAdventures): CaravanAdventures(1.0.1)
LightsOut(juanlopez2008.LightsOut): 0Harmony(2.1.1), LightsOut(1.0.0)
Stack XXL(Indeed.StackXXL)[ov:1.0.0]: StackXXL(1.0.0)
RimDungeon Traps, Poisons and Gases(miki4920.RimDungeonTraps): Rimdungeon_Traps(1.0.0)

**Comment by ThatEngineeringGuy** [comment]
Disabled all mods except Harmony, HugsLib, and Hospitality.
Seems to be working.  (30 seconds in game)
Sleeping spot could be selected and changed to guest.

**Comment by ThatEngineeringGuy** [comment]
Re-enabled all of original list EXCEPT
Achtung!(brrainz.achtung)[mv:3.3.9.0]: 0Harmony(av:2.1.1,fv:1.2.0.1), 0MultiplayerAPI(av:0.3.0,fv:0.3.0), AchtungMod(3.3.9)
Change Caravan Loadout(dhultgren.changecaravanloadout): (no assemblies)
Things seem to be working now. 
Achtung and Change Caravan Loadout, both these mods were having debug errors prior to this.

**Comment by OrionFive** [comment]
Hm. What sticks out to me is that it's not the latest version of Hospitality, so it doesn't match the latest RimWorld version. I recommend starting there.

Last time I checked, a week ago or so, Achtung indeed wasn't fixed yet for the latest RimWorld version and caused problems down the chain.

**Comment by ThatEngineeringGuy** [comment]
Thanks.  Upgrading Achtung seemed to do the trick.  Must have been an update issue,
-------- Original message --------From: OrionFive ***@***.***> Date: 2022-04-15  2:26 AM  (GMT-06:00) To: OrionFive/Hospitality ***@***.***> Cc: "Dr. Roncin" ***@***.***>, Comment ***@***.***> Subject: Re: [OrionFive/Hospitality] Hospitality: Refuse visitors until beds built fails to unlock (Issue #659) 
Hm. What sticks out to me is that it's not the latest version of Hospitality, so it doesn't match the latest RimWorld version. I recommend starting there.
Last time I checked, a week ago or so, Achtung indeed wasn't fixed yet for the latest RimWorld version and caused problems down the chain.

**Comment by OrionFive** [comment]
Isn't it always...
