### ISSUE TITLE
Hospitality: Every time a guest does a new action the game gets a 3-5 seconds lagspike

### ISSUE THREAD

**Issue by Bowek** [OrionFive/Hospitality#662]
As I said, every time a guest makes a new action the game lags, making it really anoying to play. This isn't a problem from my computer itself, since it happens only with guests, not even with traders or random npcs. I can't seem to find anything in the logs but anyway: https://gist.github.com/aa900a3acb6c0601b0d93c47e0d59b2a (idk how to add it as code, sorry).

List of mods: 

Harmony(brrainz.harmony)[mv:1.2.0.0]: 0Harmony(2.2.0), HarmonyMod(1.2.0)
Core(Ludeon.RimWorld): (no assemblies)
Royalty(Ludeon.RimWorld.Royalty): (no assemblies)
Ideology(Ludeon.RimWorld.Ideology): (no assemblies)
Ceiling Lights(neceros.ceilinglights): 0Harmony(av:2.2.0,fv:2.0.2), CeilingLights(1.0.0)
HugsLib(UnlimitedHugs.HugsLib)[ov:9.0.1]: 0Harmony(av:2.2.0,fv:1.2.0.1), HugsLib(av:1.0.0,fv:9.0.1)
EdB Prepare Carefully(EdB.PrepareCarefully)[mv:1.3.12]: 0Harmony(av:2.2.0,fv:2.0.2), EdBPrepareCarefully(av:1.1.1,fv:1.3.12)
Realistic Planets Continued(WindowsXP.RealisticPlanets): Realistic_Planets_Continued(1.0.7992.26516)
Save Our Ship 2(kentington.saveourship2): ShipsHaveInsides(0.0.0)
Interaction Bubbles(Jaxe.Bubbles): Bubbles(1.8.0)
Replace Stuff(Uuugggg.ReplaceStuff): Replace_Stuff(1.0.0)
Vanilla Furniture Expanded - Spacer Module(VanillaExpanded.VFESpacer): MFSpacer(av:1.1.3,fv:1.0.0)
Vanilla Expanded Framework(OskarPotocki.VanillaFactionsExpanded.Core): CompOversizedWeapon(1.0.0), ExplosiveTrailsEffect(1.0.7140.31563), HeavyWeapons(1.0.0), KCSG(1.1.1.3), MVCF(1.0.0), NoCamShakeExplosions(1.0.0), OPToxic(1.0.0), Outposts(1.0.0), RecipeInheritance(1.0.0), Reloading(1.1.0), RRO(1.0.0), SmokingGun(1.0.0), VanillaStorytellersExpanded(1.0.0), VanillaWeaponsExpandedLaser(1.0.0), VFECore(av:1.1.7,fv:1.1.9), VWEMakeshift(1.0.0)
Vanilla Furniture Expanded(VanillaExpanded.VFECore)[mv:1.1.0]: AOMoreFurniture(1.0.0), VFEProduction(1.0.0)
Combat Extended(CETeam.CombatExtended)[mv:1.3.4.4]: CombatExtended(0.0.0)
Giddy-up! Core(roolo.giddyupcore)[ov:4.1.3]: 0Harmony(av:2.2.0,fv:2.1.1), 0MultiplayerAPI(av:0.3.0,fv:0.1.0), GiddyUpCore(av:0.0.0,fv:0.0.0)
Giddy-up! Battle Mounts(roolo.giddyupbattlemounts)[ov:4.0.0]: DependencyChecker(1.0.0), 0Harmony(av:2.2.0,fv:2.1.0), 0MultiplayerAPI(av:0.3.0,fv:0.1.0), Battlemounts(av:1.2.0,fv:1.2.0)
Dubs Bad Hygiene(Dubwise.DubsBadHygiene): 0DubCore(1.0.0), 0Harmony(av:2.2.0,fv:2.1.1), 0MultiplayerAPI(av:0.3.0,fv:0.3.0), BadHygiene(av:2.7.7273.33335,fv:1.0.0)
CM Color Coded Mood Bar [1.1+](CrashM.ColorCodedMoodBar.11): 0Harmony(av:2.2.0,fv:2.1.1), 1SettingsHelper(av:0.19.1.38272,fv:0.19.1), CMColoredMoodBar(1.3.3136.1)
Where is my weapon?(tammybee.whereismyweapon): 0Harmony(av:2.2.0,fv:1.1.0), WhereIsMyWeapon(1.0.0)
RunAndGun(roolo.RunAndGun)[ov:4.0.0]: 0Harmony(av:2.2.0,fv:2.0.4), RunAndGun(1.0.0)
Almost There!(roolo.AlmostThere): AlmostThere(1.0.0)
Vanilla Fishing Expanded(VanillaExpanded.VCEF): AchievementsExpanded(1.3.7862.41411), VCE-Fishing(1.0.0)
Vanilla Brewing Expanded(VanillaExpanded.VBrewE): VanillaBrewingExpanded(1.0.0)
Vanilla Cooking Expanded(VanillaExpanded.VCookE): AchievementsExpanded(1.3.7862.41411), VanillaCookingExpanded(1.0.0)
Vanilla Cooking Expanded - Stews(VanillaExpanded.VCookEStews): (no assemblies)
Vanilla Cooking Expanded - Sushi(VanillaExpanded.VCookESushi): VanillaSushiExpanded(1.0.0)
Vanilla Furniture Expanded - Medical Module(VanillaExpanded.VFEMedical)[mv:1.1.0]: AOMoreMedical(1.0.0)
Vanilla Furniture Expanded - Security(VanillaExpanded.VFESecurity)[mv:1.1.1.0]: VFESecurity(1.1.2.2)
Vanilla Furniture Expanded - Farming(VanillaExpanded.VFEFarming)[mv:1.0.1.0]: VFEF(1.0.0)
Vanilla Furniture Expanded - Art(VanillaExpanded.VFEArt)[mv:1.0.3]: (no assemblies)
Vanilla Furniture Expanded - Production(VanillaExpanded.VFEProduction)[mv:1.0.3.0]: VFEProduction(1.0.0)
Vanilla Animals Expanded — Cats and Dogs(VanillaExpanded.VAECD)[mv:1.0.1]: (no assemblies)
Vanilla Furniture Expanded - Power(VanillaExpanded.VFEPower): VanillaPowerExpanded(1.0.0)
Vanilla Events Expanded(VanillaExpanded.VEE)[mv:1.1.0]: VEE(1.0.0)
Vanilla Expanded - Royalty Patches(OskarPotocki.VanillaExpanded.RoyaltyPatches)[mv:1.1.2.0]: (no assemblies)
Vanilla Furniture Expanded - Props and Decor(VanillaExpanded.VFEPropsandDecor): (no assemblies)
Vanilla Plants Expanded(VanillaExpanded.VPlantsE): VanillaPlantsExpanded(1.0.0)
Vanilla Social Interactions Expanded(VanillaExpanded.VanillaSocialInteractionsExpanded): VanillaSocialInteractionsExpanded(1.0.0.1)
Vanilla Outposts Expanded(vanillaexpanded.outposts): VOE(1.0.0), FishingOutpost(1.0.0)
Ugh You Got Me(marvinkosh.ughyougotme): UghYouGotMe(1.0.7468.14677)
Rimsential - Spaceports(SomewhereOutInSpace.Spaceports): SharpUtils(1.0.0), Spaceports(1.0.0)
Hospitality(Orion.Hospitality)[mv:1.3.1.4]: 0MultiplayerAPI(av:0.3.0,fv:0.3.0), Hospitality(av:1.0.0,fv:1.3.1.4)

**Comment by Bowek** [comment]
I just noticed it only happens when I select a specific area for guests to be into. If I leave it as no restrictions it doesn't happens. Sorry to add it now, didn't notice before.

**Comment by OrionFive** [comment]
Hm. It's not a problem of Hospitality either, because no one else is having this issue.Can you try it without space ports?My best guess is that another mod patches Hospitality and slows it down. And space ports patches Hospitality a lot.

**Comment by Bowek** [comment]
I tried it without spaceports and the same thing happened. It seems like the problem happens when I assign a shopping area that has no items or shelves to buy from. It's really weird and to be honest I got zero clue if it has to be with other mod or it's a bug.

**Comment by OrionFive** [comment]
It could be either. I'll see if I can reproduce the issue.

**Comment by skyarkhangel** [comment]
Specify a no-large trade zone for guest and check again. This could relate to this issue : https://github.com/OrionFive/Hospitality/issues/639

**Comment by OrionFive** [comment]
I still can't reproduce this. So there must be interference by some other mod that slows down the operation.
