### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by crustybatteryacid** [OrionFive/Hospitality#668]
Yo! This might be some random mod compatibility issue - I have 3128347 mods so this might not be Hospitality's fault, but this debug log (which I cannot read, I'm no modding man) says Hospitality a buncha times so I figured I'd shoot it to you guys.

This occurs when I try to rescue one of my colonists and put him into a medical bed. If it's not the your guys's fault, could you point me in a direction so I can fix it? Thanks.

![image](https://user-images.githubusercontent.com/65634918/159099045-456fed71-f554-4555-9d8d-830cd03472de.png)

**Comment by crustybatteryacid** [comment]
turning off Hospitality fixes the issue, btw.

**Comment by OrionFive** [comment]
There's either a conflict with a common mod going on, or there's been a RimWorld update that messes things up.
Or it's a rare issue with the latest Hospitality version.
Can you please share your full log (as a link)?

**Comment by crustybatteryacid** [comment]
It went away shortly after I posted this, but it is a reoccurring thing so I'll post the full log as soon as I can replicate it. Shouldn't take too long.

**Comment by crustybatteryacid** [comment]
My pawns will sometimes randomly randomly get out of bed, stand around for a second and then go back to sleep. I assume this is the same issue as the log entries look the same. It happened multiple times in the last 100 or so lines.
 
[hospitality log.txt](https://github.com/OrionFive/Hospitality/files/8309573/hospitality.log.txt)

**Comment by crustybatteryacid** [comment]
`Exception in JobDriver tick for pawn DonClive driver=JobDriver_LayDown (toilIndex=2) driver.job=(LayDown (Job_395874) A=Thing_SleepingSpot1800506)
System.TypeLoadException: Could not resolve type with token 01000043 (from typeref, class/assembly Hospitality.DefOf, Hospitality, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
  at (wrapper dynamic-method) Hospitality.Patches.Toils_LayDown_Patch+ApplyBedThoughts.Hospitality.Patches.Toils_LayDown_Patch+ApplyBedThoughts.Replacement_Patch1(Verse.Pawn)
  at (wrapper dynamic-method) RimWorld.Toils_LayDown.RimWorld.Toils_LayDown.ApplyBedThoughts_Patch5(Verse.Pawn)
  at RimWorld.Toils_LayDown+<>c__DisplayClass3_0.<LayDown>b__1 () [0x00155] in <360933dd75ad47e8a6d2a631ae77b5d8>:0 
  at (wrapper dynamic-method) Verse.AI.JobDriver.Verse.AI.JobDriver.DriverTick_Patch0(Verse.AI.JobDriver)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch1 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch4 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
`

Here is my colonist trying to put another colonist into a bed and immediatly "falling out" again.

**Comment by OrionFive** [comment]
Thanks for these. For the log, can you please use the "Share logs" button and upload the log and give me the link? The text file is not useful for me.

**Comment by OrionFive** [comment]
For more context, [here's the log](https://gist.github.com/HugsLibRecordKeeper/84bd866ea5917978ff827881edab2c38) of someone with the same issue. Possibly, it can be used later to cross-reference mods.

**Comment by OrionFive** [comment]
Could you please try out this version for when you create the log?
[Hospitality Test.zip](https://github.com/OrionFive/Hospitality/files/8311203/Hospitality.Test.zip)

**Comment by crustybatteryacid** [comment]
Alright, sorry for the useless logs. I'm only very surface-level familiar with anything code. (Again, this is me rescuing a downed pawn and putting him to bed.) I hope these help more!

Here's a log with the steam version:
https://gist.github.com/767a1f79bfae0a73211c092dd2a477b4

Here's one with your new version:
https://gist.github.com/c6cad51ba9036246f44bc75d72437161

The new version seems to have fixed it for now, I'll keep playing some throughout the day and I'll hit you when something occurs.

**Comment by crustybatteryacid** [comment]
that said, the new version you provided to me does not seem to work at all, actually

**Comment by crustybatteryacid** [comment]
I put it in the Mods folder in my RimWorld directory, and loaded the game with it active - I hope that was the right way to do it.

**Comment by OrionFive** [comment]
That does sound correct, yeah. So what's not working?

**Comment by OrionFive** [comment]
Hm, looking at the log, it seems the content of the mod folder is, wrong or something.
Are you sure you've extracted it right?

**Comment by crustybatteryacid** [comment]
Yeah, sorry I just fucked up the install. I played some more with your new version working properly, and I encountered the issue again. Here's a log: https://gist.github.com/0342e99c691e181938efd8ba32fa9673

**Comment by OrionFive** [comment]
Glad you figured it out. This definitely gives new insights.Apparently, some other mod is referring Hospitality wrong, causing the issue. I can't tell which one, but I can fix it from my end.

**Comment by OrionFive** [comment]
I found the mod in question: It's Dormitories.

I've uploaded a new version of Hospitality to Steam that addresses their mistake.
