### ISSUE TITLE
Hospitality: Null pointer exception

### ISSUE THREAD

**Issue by Arokha** [OrionFive/Hospitality#669]
**Describe the bug**
Every few seconds I get a debug message which I've put below in the stack trace section. The trace itself doesn't mention hospitality, but hugslib shows that hospitality is the only mod patching this function, and removing hospitality (and only hospitality) removes the exception.

**To Reproduce**
I'm honestly not sure, sorry. I noted it like 50+ real hours into this colony, and have no idea when it started. It starts as soon as I load any save on this colony and doesn't stop unless I remove hospitality. Admittedly I've added more mods since then, so it's possible something else patches it NOW, but, at the time it was pretty conclusively that. I guess you're stuck with just adding nullsafe dereference operators everywhere. :^)

**Console log**
[Linky](https://gist.github.com/HugsLibRecordKeeper/7908898147ec6b2b0d5ee082baa579ca)

**Error stacktrace**
```
Exception in Verse.AI.ThinkNode_Priority TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) RimWorld.JobGiver_Work.RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1(RimWorld.JobGiver_Work,Verse.Pawn,Verse.AI.JobIssueParams)
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00022] in <360933dd75ad47e8a6d2a631ae77b5d8>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob (Verse.ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0 (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch4 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch4 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch3 (Verse.Game)
Verse.Root_Play:Update ()
```

**Screenshots**
Nothing to screenshot.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
I'm gonna look into it. Might be tricky, though. The exception isn't happening in the patch but in a vanilla function. Not sure if the patch is even related.I'll see if I can somehow reproduce it.

**Comment by OrionFive** [comment]
So, usually, you have to fix mods top-down, since often the first issues cascade down, causing the others.
Looking at your log, you're getting an exception from a Pawn.Tick patch, which is LightsOut or Rocketman (unlikely). 

Also, there's VFEMech.CompPropaganda.CompTick, erroring constantly. 

And there's a failed patch from MOARANDROIDS. Since I have a personal vendetta against all android mods, because they make my modding life a living hell, I'm gonna say that's the prime suspect.

These all happen before the error you've reported. Please fix these first. When they're gone and the issue persists, please reopen this thread.
