### ISSUE TITLE
Hospitality: Steam Deck update fixes

### ISSUE THREAD

**Issue by isonil** [OrionFive/Hospitality#670]
Hi,

I'm one of the RimWorld developers and we're currently trying to implement support for Steam Deck. However, this requires updating Steamworks which is a bit unfortunate as it breaks some mods relying on the older version. We're trying to make the process as smooth as possible and we're open to all suggestions. The bug with Hospitality was reported by Kaen_SG:

<img width="828" alt="Zrzut ekranu 2022-03-21 o 15 44 27" src="https://user-images.githubusercontent.com/8492408/159288116-bf971fd7-ab80-4109-ba38-756209800153.png">

Would it be possible to handle this case somehow? Maybe add some try/catch blocks for now? You can test the new build on the **steam_deck** or **unstable** branch on Steam. (Right-click RimWorld -> Betas). If you need more information let me know. Thanks!

Link to the announcement: https://store.steampowered.com/news/app/294100/view/3128319129435462402

**Comment by OrionFive** [comment]
I've pushed two updates, yesterday and today.
With one of them I've removed all Steam references. So odds are it might just work now.

I'll try the unstable branch later to see if I can reproduce the problem.

**Comment by isonil** [comment]
Awesome, thank you for looking into this.

**Comment by OrionFive** [comment]
Running with the unstable branch, royalty, ideology, harmony, and hugslib, I can't reproduce the issue. 

So I assume it's been resolved during the last round of fixes.
