### ISSUE TITLE
Hospitality: Guests not giving faction reputation gain

### ISSUE THREAD

**Issue by RedWardog** [OrionFive/Hospitality#671]
Issue Solved: Long story short is it took me WAY too long to recognize that the reputation gains aren't shown when the guests leave, its just marked on the faction tab, Orion pulled a sneaky on me lmao.

**Comment by OrionFive** [comment]
Sorry about that. I removed the reputation change from the message years ago.
I had to, because players kept complaining when they didn't agree with how much they gained or lost.
Making it less transparent solved that problem 😑
