### ISSUE TITLE
Hospitality: Error on Game Load

### ISSUE THREAD

**Issue by alicia86** [OrionFive/Hospitality#676]
Error on game load, but before loading a save game. No issues on a different PC with the same mods installed. Have attempted to delete the mods from the folder have them reinstalled.

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.](https://gist.github.com/97d0844b7711c0ec0eba5c9f979fd4d3)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
[HugsLib] initializing Hospitality, DefensivePositions, LWM_DeepStorage
[HugsLib][ERR] Hospitality caused an exception during LoadReloadInitialize: System.TypeLoadException: Could not resolve type with token 01000184 (from typeref, class/assembly Steamworks.SteamUser, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
  at HugsLib.HugsLibController.LoadReloadInitialize () [0x0007c] in <a56dbe2cf5184fe991f5fb736b3081b0>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
The installed version of Hospitality is outdated. This causes the error. Please use the latest version of the mod.
