### ISSUE TITLE
Hospitality: Some guests are stuck meditating/praying even when asked to leave

### ISSUE THREAD

**Issue by LunaticModo** [OrionFive/Hospitality#678]
**Describe the bug**
Guests appeared then they look for a bed and then satisfy their food and rest needs. Some guests after satisfying these needs will satisfy their joy needs thru praying/meditation and are stuck doing it until they are downed

**To Reproduce**
1. Wait for guests to arrive
2. Let them fulfill their needs
3. Some are stuck meditating

**Console log**
Note: No new log in relation to meditating
Link: https://gist.github.com/5d8117e35b6f92d792645f415199d946

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.
![Screenshot (37)](https://user-images.githubusercontent.com/62584084/166121820-eb0f3809-d8e8-4e5a-9af8-8141a0c4c96e.png)

**Comment by OrionFive** [comment]
The issue is caused by Variety Matters' Meal Time Joy, as can be seen from the error you're getting.
