### ISSUE TITLE
Hospitality: Guest will meditate until one vanilla need is zero

### ISSUE THREAD

**Issue by LunaticModo** [OrionFive/Hospitality#679]
**Describe the bug**
Some guests will meditate ignoring modded needs such as Hygiene/Thirst (DBH) until one of the vanilla needs (Rest/Food) is depleted to zero. Once sent a ticket for this particular problem and disabled the mod that causes this.

**To Reproduce**
1. Wait for guests.
2. Everything proceeds as normal until one of them meditates.
3. Watch as it meditates until either need or sleep is zero and then they go satisfy their needs.

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.](https://gist.github.com/377f8b564eaa3aa4bfbc66fe26b72bdc)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.
![Screenshot (38)](https://user-images.githubusercontent.com/62584084/166226205-06cb7084-1197-4a08-bb43-ee701e2e4c38.png)

**Comment by OrionFive** [comment]
Let's see. What I can find:
- Combat Extended is crashing a patch. This can have ripple effects on other mods.
- And the usual suspect: MoarAndroids also crashing an operation, interrupting code flow
- VFE-Mechanoids and Power++ interrupt code flow
- Some mod that affects Peace Talks is breaking it
That's about all I can find among loads and loads of warnings and minor errors.

Hard to tell if this is an issue with Hospitality and whatever adds thirst or if it's one of the hundreds of mods breaking things.
