### ISSUE TITLE
Can't set beds for guests

### ISSUE THREAD

**Issue by Darakudemion** [OrionFive/Hospitality#682]
It won't let me set beds for guests, it just stays with a red X. 
https://gist.github.com/HugsLibRecordKeeper/2ed2aaf4e0690ff21cf4938e57b5afe9

**Comment by Darakudemion** [comment]
![screenshot2](https://user-images.githubusercontent.com/60558966/170851579-3d2f5010-4c95-492b-b7bf-fe9f38408368.png)

**Comment by OrionFive** [comment]
Your Hospitality version is outdated.
