### ISSUE TITLE
Recreation Bar Disappeared

### ISSUE THREAD

**Issue by kcai13565** [OrionFive/Hospitality#683]
**Describe the bug**
The recreation bar for visitors disappeared. Events that had happened very recently were the clearing of an ancient complex quest and a drop pod raid which destroyed a colonist's bed. The visitors arrived normally and had recreation bars, but at some point lost them. I suspect they lost it recently since they still had mood buffs from recreation related things.

EDIT:
Reloading to a save with a previous group of guests, before the original group had arrived, caused the previous group to lose their recreation bar. When the original group then arrived later, they had their recreation bar. Making a save as soon as their recreation bar popped up (once they chose a room), and reloading that save caused the bar to disappear. Possibly issue caused by loading a save with visitors currently at the base?

**To Reproduce**
I don't know how to reproduce it. It has happened once before, immediately after recruitment of a guest. Reloading to a save before the guest was recruited did not fix the issue. Reloading to before visitors had arrived seemingly caused the next visitors to arrive normally, with the recreation bar.

**Console log**
[log
](https://gist.github.com/HugsLibRecordKeeper/b8e0f054b4bb1119c8327746cf539032)
**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
(All other errors in the log had something to do with a tamed muffalo's food processing)
```
Error while notifying ideos of a HistoryEvent: System.InvalidCastException: Specified cast is not valid.
  at RimWorld.ThoughtMaker.MakeThought (RimWorld.ThoughtDef def, System.Int32 forcedStage) [0x0000b] in <99518a644a3e4a7ea3fde566568df84a>:0 
  at AlienRace.HarmonyPatches.TryGainMemoryPrefix (RimWorld.Thought_Memory& newThought, RimWorld.MemoryThoughtHandler __instance) [0x00042] in <0464101ca738476aa42570cab08ce88b>:0 
  at (wrapper dynamic-method) RimWorld.MemoryThoughtHandler.RimWorld.MemoryThoughtHandler.TryGainMemory_Patch1(RimWorld.MemoryThoughtHandler,RimWorld.Thought_Memory,Verse.Pawn)
  at (wrapper dynamic-method) RimWorld.PreceptComp_KnowsMemoryThought.RimWorld.PreceptComp_KnowsMemoryThought.Notify_MemberWitnessedAction_Patch0(RimWorld.PreceptComp_KnowsMemoryThought,RimWorld.HistoryEvent,RimWorld.Precept,Verse.Pawn)
  at RimWorld.Ideo.Notify_MemberKnows (RimWorld.HistoryEvent ev, Verse.Pawn member) [0x00031] in <99518a644a3e4a7ea3fde566568df84a>:0 
  at RimWorld.IdeoUtility.<Notify_HistoryEvent>g__CheckKnows|1_0 (Verse.Pawn p, RimWorld.IdeoUtility+<>c__DisplayClass1_0& ) [0x00017] in <99518a644a3e4a7ea3fde566568df84a>:0 
  at RimWorld.IdeoUtility.Notify_HistoryEvent (RimWorld.HistoryEvent ev, System.Boolean canApplySelfTookThoughts) [0x000c8] in <99518a644a3e4a7ea3fde566568df84a>:0 
  at RimWorld.HistoryEventsManager.RecordEvent (RimWorld.HistoryEvent historyEvent, System.Boolean canApplySelfTookThoughts) [0x00000] in <99518a644a3e4a7ea3fde566568df84a>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
RimWorld.HistoryEventsManager:RecordEvent (RimWorld.HistoryEvent,bool)
(wrapper dynamic-method) Verse.Thing:Verse.Thing.Ingested_Patch1 (Verse.Thing,Verse.Pawn,single)
RimWorld.Toils_Ingest/<>c__DisplayClass12_0:<FinalizeIngest>b__0 ()
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()
```

EDIT: error that appeared after loading a save that was created immediately after visitor chose their room and gained a recreation bar.

```
Could not resolve reference to object with loadID Thing_Human481014 of type Verse.Pawn. Was it compressed away, destroyed, had no ID number, or not saved/loaded right? curParent=RimWorld.DirectPawnRelation curPathRelToParent=
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.LoadedObjectDirectory:ObjectWithLoadID<Verse.Pawn> (string)
Verse.CrossRefHandler:TakeResolvedRef<Verse.Pawn> (string,Verse.IExposable)
Verse.CrossRefHandler:TakeResolvedRef<Verse.Pawn> (string)
Verse.Scribe_References:Look<Verse.Pawn> (Verse.Pawn&,string,bool)
RimWorld.DirectPawnRelation:ExposeData ()
Verse.CrossRefHandler:ResolveAllCrossReferences ()
Verse.ScribeLoader:FinalizeLoading ()
(wrapper dynamic-method) Verse.Game:Verse.Game.LoadGame_Patch1 (Verse.Game)
(wrapper dynamic-method) Verse.SavedGameLoaderNow:Verse.SavedGameLoaderNow.LoadGameFromSaveFileNow_Patch1 (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Hm. From what I can tell this is not a Hospitality issue, but a ripple effect from something that breaks loading/initialization.
Probably you can best try your luck at the Alien Race mod, as it seems to be involved with every error you're having.
Do note that any exception can affect any other mod down the line (the line is not the load order but any random order). So you never want to have any exceptions, ever. Worst case they will corrupt your savegame to a state it can't recover from.
