### ISSUE TITLE
Infinite silver bug

### ISSUE THREAD

**Issue by MakarPro** [OrionFive/Hospitality#685]
I find bag. If you place bed for example 10 silver. Guest has paid after you break and place bed again for 10 silver. And he paid again. You can do it infinite times.
I dont think screenshot  is required. 
I dont know how to fix this maybe if guest pay he dont need to pay again. I think is alredy  idea and not bug report.
(; please Fix it .

**Comment by MakarPro** [comment]
thanks for reading my bad english

**Comment by OrionFive** [comment]
This is by design. The guest will get more unhappy when they have to pay again, just as if you had charged more in the first place.
