### ISSUE TITLE
Hospitality: Guests of same faction share food

### ISSUE THREAD

**Issue by NerdyVampire** [OrionFive/Hospitality#688]
When a guest is visiting and become hungry, have them try to take a meal from a fellow visitor of the same faction after they have checked their own inventory.

For example, I had three guests stay with me. One bought an entire stack of available food, their friend starved because he couldn't afford any. When they left, the first guy still had 7 meals, while the second had malnutrition. I got a bad rating.

Love the mod, it's awesome.

**Comment by OrionFive** [comment]
That sounds useful. Not sure when I'd get around to it, though.

**Comment by OrionFive** [comment]
Done.
