### ISSUE TITLE
Hospitality and Zombieland

### ISSUE THREAD

**Issue by smittythesmith** [OrionFive/Hospitality#689]
Sometimes when a pawn spawns at night via hospitality  (a guest arrives)  Zombieland turns it into a zombie and the tribe chief is angered. (His delegation was never heard from).  I'm not saying "the guest was attacked by a zombie"  I'm saying the guest was a zombie.  Now maybe this interaction is intentional and I shouldn't welcome guests at night. *shrug*

**Comment by OrionFive** [comment]
It's not intentional, but it also never happened in the past. I'm blaming this on zombieland.
