### ISSUE TITLE
Hospitality: Guests aren't eating even tho there is food

### ISSUE THREAD

**Issue by cockerfcuksuckdickfungusshitbitchman** [OrionFive/Hospitality#694]
I have a Nutrient dispenser. it is on. it has vending machine activated for free food. customers still complain. help
**To Reproduce**
1. Guests come. they dont eat
**Console log**
(https://gist.github.com/5f74768813526f3c64bfd0bc1dc1a9e3)

**Error stacktrace**
none
```


**Screenshots**



![sgh](https://user-images.githubusercontent.com/108922715/177941577-b9ca88b2-a712-47ea-baba-0737334b21ec.png)

**Comment by OrionFive** [comment]
Guests will only accept food that they can and want to eat. Also, robots are weird and break everything.

So you'll have to bring this to the robots mod. Sorry.

**Comment by cockerfcuksuckdickfungusshitbitchman** [comment]
but theres 1 that just human..perhaps its because he came with robots that it broke him as well...allright thanks anyway

**Comment by cockerfcuksuckdickfungusshitbitchman** [comment]
anyway to disable androids to be guests?

**Comment by OrionFive** [comment]
Not specifically, no.
