### ISSUE TITLE
Hospitality + Multiplayer +MpC: desync loop when there are guests

### ISSUE THREAD

**Issue by Wolfurus79** [OrionFive/Hospitality#695]
as soon as guests enter our colony, the server will continuously desynchronize at each reconnection making the game impossible but as soon as the guests leave the colony the game becomes possible again

1. Create a new game
2. Place guest beds (no matter the price)
3. spawn guests
4. the game is desync and will continue to do so as long as the guests are in the map

the log are attached below
[Desync-146.zip](https://github.com/OrionFive/Hospitality/files/9176534/Desync-146.zip)

We have around 50 mods, the screenshots of the list is below

![image_2022-07-24_213427413](https://user-images.githubusercontent.com/83947234/180662975-2351c3b1-ef87-4d83-a093-532436cb8c32.png)
![image](https://user-images.githubusercontent.com/83947234/180662981-d511487a-ba6a-45d9-aed9-91eb0ea8e1a9.png)
![image](https://user-images.githubusercontent.com/83947234/180662988-5ff8111e-157a-4162-ac1d-1baa12adca0d.png)
![image](https://user-images.githubusercontent.com/83947234/180662997-64a53cff-d070-461b-9869-76868cdb699c.png)

(screenshots are in the order that the mods load)

I play with only one person and we really like this mods and we would love to make it work
We use the latest versions of each mod as well as rimworld

**Comment by OrionFive** [comment]
Sorry for the dismissiveness, but I'm not doing multiplayer stuff. So you've got to take this issue up with the multiplayer compatibility people.
