### ISSUE TITLE
Hospitality: Guests can join ideology event (new game setting?)

### ISSUE THREAD

**Issue by mikavello** [OrionFive/Hospitality#696]
It would be a neat way of impromptu pawn gathering to increase likelihood of positive event - for those that want to make some kind of "inkeeper build", with small colonist group.

Depending on how Ideology treats pawns (I'm less than capable of checking so), IF there's a way to make them more-than-guests/less-than-colonists, but so that Event will recognize them - it would be neat.

Let's say only Guests attending would suffice, after all they were the ones that came to visit our culture and lifestyle - adding Trader groups I assume would make it a clusterduck.

Also (though through my playthroughs I weren't able to check whether death of guest makes colonists sad akin to colonist death) it would make for realism. "We weren't able to help/protect our guest." "They died on our watch." "Our traveler's haven became hell" (this one might work as negative mood for i.e. depressive trait; and vice-versa - mood boost for bloodlust/psychopath)

On additional note - aside from "rivals" showing and text about being "afraid to arrive", there could be two types of events:
- assasin(s) went to kill your guest (you can help/intervene/ignore; either by choosing option or manually drafting colonist and to command to go either way)
- weary traveller(s) from highly hostile faction shows up, asking for help (especially in more extreme biomes), which could mean warmer relations and possibly a way to achieve peace or cease-fire with nude cannibals or rowdy pirates

**Describe alternatives you've considered**
Going through available mods and looking for some kind of workaround/"patch" for Hospitality+Ideology - to no avail. 
And I'm aware it takes time and will to make something (and code might be finnicky already) - this kind of change (depending on how Ideology recognizes attendees) might require either adding your Guests as Colonists in Ideology box; or making them hidden Colonists - and I think both solutions might not work.

**Comment by OrionFive** [comment]
Those are good ideas. However, the amount of effort that would have to go into making guests work with Ideology events is prohibitive.
It's just not worth it.
The special events sound interesting, but creating specific events with guests is also not exactly trivial and also not really my cup of tea.
Beyond all that, I'm not adding new features anymore. Updating all my mods once or twice per year so they continue working is already an entire summer vacation's worth. So new stuff is just not gonna happen anymore 😐 Sorry.
