### ISSUE TITLE
Gastronomy: No dining tables being prepared

### ISSUE THREAD

**Issue by AColliV** [OrionFive/Hospitality#697]
Hi Orion,

I've set tables and countertop to be dining tables, but waiters don't prepare them. 
Could you see the problem?

https://gist.github.com/8cd04d27fb812eb4113be5b83478da76

**Comment by AColliV** [comment]
Okay, I checked "Room" as "No" in Cash Register, and waiter prepared the tables. Strange...

**Comment by OrionFive** [comment]
When room is enabled, it limits the range to the current room. Maybe something conflicts with the function that retrieves the room 🤔

**Comment by OrionFive** [comment]
You are getting errors from whatever Carousel is. Could be the cause, but also pollutes the log so much I can't see if anything else is wrong.

**Comment by AColliV** [comment]
Thank you. I unsubscribed from Carousel, but this issue occured again; switching from Yes/No in Cash Register makes pawn making the dining spot, but only on half tables, on the angles (despite having 3x3, 3x4 tables).
This is another run, so I don't know if there is noise from other mods

Could you help me?

https://gist.github.com/HugsLibRecordKeeper/c332f1758a7357677a52460f050c4755

https://ibb.co/W0KTdSM

**Comment by OrionFive** [comment]
It's more readable now. There's still a mod spamming everything, but I can tell there are I related errors.
There are errors related to groups which indicate a broken savegame which may or may not be related (likely not).
Personally, I think it's probably just a case of too many mods. You have several thousand active patches which is asking for trouble and somewhere something will break.
Or it's some weird type of table or chair. I have no idea. Sorry.
