### ISSUE TITLE
and if a mod adds more beds?

### ISSUE THREAD

**Issue by eninyelalexander** [OrionFive/Hospitality#699]
Well, I think the title explains it but... what if a mod adds more beds? I have the apinis mod, a mod with very cute overdeveloped bees that adds a bed of honey and when I press the button to assign it to visitors nothing happens and for some reason I have the impression that those beds could have something to do with it, by the way, what you do is appreciated, finally giving meaning to the visits.

**Comment by OrionFive** [comment]
Custom beds are supported as long as they're reasonably normal. Sounds like these aren't normal enough.
Does it not work for any bed or only these?

**Comment by eninyelalexander** [comment]
![Sin título](https://user-images.githubusercontent.com/110853593/183779506-5358f322-46e5-409d-9e75-96f0e3c15df7.png)

**Comment by eninyelalexander** [comment]
I was checking why I use the honey beds as standard (they are rotten) and it seems that both the normal ones and the sleeping areas don't work either, but there is an issue that I have to comment on, I modified the configuration files so that the game runs in resolution 0.8, and my screen resolution is 1024x600 (that's why I modified it) maybe it has something to do with it and my mods are loaded in the image... what do you think?

**Comment by OrionFive** [comment]
It's unlikely that your config change had that effect. It's more likely that by loading the apini mod at all (no matter the beds you use), Hospitality's beds get broken.
You'll have to create an error log to find out more.

**Comment by eninyelalexander** [comment]
https://gist.github.com/6f445b4c52d5a01e110f56972e17f15d
is this true?

**Comment by OrionFive** [comment]
You're running an outdated version of Hospitality that is not compatible with your RimWorld version...
Make sure to update it to the latest and see if that helps.

**Comment by eninyelalexander** [comment]
really...? Now I feel like an idiot, I downloaded it from here recently, maybe you updated it right after but, anyway, thanks I'll look for it on steam.
https://rimworldbase.com/orion-hospitality-mod/

**Comment by OrionFive** [comment]
I really wish people would stop downloading mods from other sites. They're bound to be outdated and cause issues.
Anyway, I think this should solve the problem. Have fun!
