### ISSUE TITLE
Multiple Visitors choosing same floor cell to sleep, when not enough beds present

### ISSUE THREAD

**Issue by CallMeOzz** [OrionFive/Hospitality#7]
LOW PRIORITY-

Not sure if this is a RimWorld issue with choosing a random close walk cell, while another pawn has targeted it (but not yet reached it), or if a cell reference is being reused accidentally, etc.... or, maybe just dumb luck

I had 8 visitors in my group, but only 5 beds.  Once the 5 beds were claimed the 6th and 7th pawns both chose the same floor cell for sleeping, and stacked in that cell.   The 8th didn't sleep at the same time, but chose a different cell when it did sleep later.

Both pawns selected the floor cell within 5 seconds of one another, so the cell itself was not yet occupied by visitor 6 when visitor 7 made its selection.  

Within JobGiver_Sleep, would RimWorld's CellFinder.RandomClosewalkCellNear() method be expected to exclude occupied and/or targeted cells, or is this something that needs to be accounted for within the ThinkResult?

**Comment by OrionFive** [comment]
I'll check how vanilla does it. Probably their code has changed. Good catch!

**Comment by OrionFive** [comment]
This should be fixed now.
