### ISSUE TITLE
Traders are getting attacked but do not respond fire and die

### ISSUE THREAD

**Issue by Narlindir** [OrionFive/Hospitality#702]
**Describe the bug**
Traders are getting attacked but do not respond and die

in this case it was the sacriledge hunters from Caravan adventures (could be an error on their side, but I lack the proficiency to assess)
https://steamcommunity.com/sharedfiles/filedetails/?id=2558957509

I traded with them and took their talking quest, I got raided and they did not open fire after getting shot, neiterhdid they react to enemy proximity.
Maybe important is that I have prison labour and Real fog of war installed

prisoners were not working
probaly unrelated

**To Reproduce**

unknown, happens randomly

**Console log**
https://gist.github.com/HugsLibRecordKeeper/96527f3f3e084c499c4bd76a0062a32e

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```
I dont know if its this but:

exception in GetVersionFromManifestFile line
System.NullReferenceException: Object reference not set to an instance of an object
  at Madeline.ModMismatchFormatter.MetaHeaderUtility.GetVersionFromManifestFile (Verse.ModContentPack pack) [0x00046] in <bdbdeeef26de47f7aa21d4110df0853f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.Log:Error (string,bool)
Madeline.ModMismatchFormatter.MetaHeaderUtility:GetVersionFromManifestFile (Verse.ModContentPack)
Madeline.ModMismatchFormatter.MetaHeaderUtility:UpdateModVersionMetaHeader ()
ModMisMatchWindowPatch.HarmonyPatches:Postfix_SaveGame ()
(wrapper dynamic-method) Verse.GameDataSaveLoader:Verse.GameDataSaveLoader.SaveGame_Patch5 (string)
RimWorld.Autosaver:DoAutosave ()
(wrapper dynamic-method) Verse.LongEventHandler:Verse.LongEventHandler.UpdateCurrentSynchronousEvent_Patch2 (bool&)
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch2 (Verse.Root)
Verse.Root_Play:Update ()
-----
Cannot play Pawn_Human_Wounded (subSound UnnamedSubSoundDef_: No resolved grains.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.Sound.SubSoundDef:TryPlay (Verse.Sound.SoundInfo)
Verse.Sound.SoundStarter:PlayOneShot (Verse.SoundDef,Verse.Sound.SoundInfo)
Verse.LifeStageUtility:PlayNearestLifestageSound (Verse.Pawn,System.Func`2<Verse.LifeStageAge, Verse.SoundDef>,single)
rjw.SexUtility:Aftersex (rjw.SexProps)
rjw.SexUtility:ProcessSex (rjw.SexProps)
rjw.JobDriver_Rape/<>c__DisplayClass1_0:<MakeNewToils>b__9 ()
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
rjw.JobDriver_Rape/<>c__DisplayClass1_0:<MakeNewToils>b__7 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0 (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch13 (Verse.Pawn)
(wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch0 (Verse.TickList)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
-----------
Could not resolve arrival mode for raid. Defaulting to EdgeWalkIn. parms=target=Map-0-PlayerHome, points=26.93133, raidStrategy=CentreDropAttack
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
RimWorld.IncidentWorker_Raid:ResolveRaidArriveMode (RimWorld.IncidentParms)
(wrapper dynamic-method) RimWorld.IncidentWorker_Raid:RimWorld.IncidentWorker_Raid.TryGenerateRaidInfo_Patch1 (RimWorld.IncidentWorker_Raid,RimWorld.IncidentParms,System.Collections.Generic.List`1<Verse.Pawn>&,bool)
(wrapper dynamic-method) RimWorld.IncidentWorker_Raid:RimWorld.IncidentWorker_Raid.TryExecuteWorker_Patch3 (RimWorld.IncidentWorker_Raid,RimWorld.IncidentParms)
(wrapper dynamic-method) RimWorld.IncidentWorker_RaidEnemy:RimWorld.IncidentWorker_RaidEnemy.TryExecuteWorker_Patch2 (RimWorld.IncidentWorker_RaidEnemy,RimWorld.IncidentParms)
(wrapper dynamic-method) RimWorld.IncidentWorker:RimWorld.IncidentWorker.TryExecute_Patch7 (RimWorld.IncidentWorker,RimWorld.IncidentParms)
(wrapper dynamic-method) RimWorld.Storyteller:RimWorld.Storyteller.TryFire_Patch1 (RimWorld.Storyteller,RimWorld.FiringIncident)
(wrapper dynamic-method) RimWorld.Storyteller:RimWorld.Storyteller.StorytellerTick_Patch1 (RimWorld.Storyteller)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
-----
Cannot play Pawn_Human_Wounded (subSound UnnamedSubSoundDef_: No resolved grains.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.Sound.SubSoundDef:TryPlay (Verse.Sound.SoundInfo)
Verse.Sound.SoundStarter:PlayOneShot (Verse.SoundDef,Verse.Sound.SoundInfo)
Verse.LifeStageUtility:PlayNearestLifestageSound (Verse.Pawn,System.Func`2<Verse.LifeStageAge, Verse.SoundDef>,single)
Verse.DamageWorker_AddInjury:PlayWoundedVoiceSound (Verse.DamageInfo,Verse.Pawn)
(wrapper dynamic-method) Verse.DamageWorker_AddInjury:Verse.DamageWorker_AddInjury.ApplyToPawn_Patch1 (Verse.DamageWorker_AddInjury,Verse.DamageInfo,Verse.Pawn)
(wrapper dynamic-method) Verse.DamageWorker_AddInjury:Verse.DamageWorker_AddInjury.Apply_Patch1 (Verse.DamageWorker_AddInjury,Verse.DamageInfo,Verse.Thing)
(wrapper dynamic-method) Verse.Thing:Verse.Thing.TakeDamage_Patch10 (Verse.Thing,Verse.DamageInfo)
(wrapper dynamic-method) RimWorld.Bullet:RimWorld.Bullet.Impact_Patch1 (RimWorld.Bullet,Verse.Thing)
(wrapper dynamic-method) Verse.Projectile:Verse.Projectile.ImpactSomething_Patch2 (Verse.Projectile)
(wrapper dynamic-method) Verse.Projectile:Verse.Projectile.Tick_Patch3 (Verse.Projectile)
(wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch0 (Verse.TickList)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()

**Screenshots**
![grafik](https://user-images.githubusercontent.com/88289802/189465721-8bca94d7-b96d-4a08-931f-1c0d122873dd.png)
![grafik](https://user-images.githubusercontent.com/88289802/189465964-fe398a5a-7725-422a-a6af-69e9f396c1be.png)

Fixing bugs takes a lot of time. 
So Please take your time :)

**Comment by OrionFive** [comment]
As a rule of thumb, if there are any exceptions in your log, things will not work properly. And usually the first exceptions are the culprit and may have caused the others.
Do note that if you have saved your game after getting an exception it may be "baked in" and have corrupted the save game. So after loading you might not get the exception that indicates the actual problem.
That said, the first exception in your log is from VFEF Pirates. So I'd start there. As long as that is happening, everything else could be collateral damage.

**Comment by Narlindir** [comment]
thanks for the advice
I appreciate it, ill do some recajiggering and see what comes out!
You can put this report on ice for the time beeing if you prefer

**Comment by OrionFive** [comment]
I have :)
Feel free to reopen it should it turn out to be a genuine Hospitality issue.

**Comment by OrionFive** [comment]
This is likely caused by Variety Matters of Vanilla Factions Expanded Pirates, which both fail to load and likely cause other issues as collateral.

**Comment by OrionFive** [comment]
Your first error looks like a conflict between adeptus and VE pirates. Everything after that is collateral damage. 
Nothing to do with my mods most likely. I hope you didn't save with all these errors going on, because then your savegame might be borked now.
Nothing I can do for you there 🤷🏽‍♂️

**Comment by OrionFive** [comment]
Somethings wrong with my browser. It keeps showing me this issue without my responses and I reply to it daily. Something wrong with my memory too 🤔
