### ISSUE TITLE
Dubs Bad Hygiene: Guest can't use facilities

### ISSUE THREAD

**Issue by scarlytte** [OrionFive/Hospitality#708]
When guests arrive, they can't use dubs stuff like the shower and toilet. they also can't go outside to just do their business, so their bladder and cleanliness just keep going down, which makes them miserable so I can't build faction relations. please help, I've checked and unchecked the guest box option for the facilities. I also checked to make sure the guests are allowed in those areas.

**To Reproduce**
1. Select '...'
3. Open '....'
4. This happens

**Console log**
Mono path[0] = 'D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed'
Mono config path = 'D:/SteamLibrary/steamapps/common/RimWorld/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.30f1 (e8c891080a1f)
[Subsystems] Discovering subsystems at path D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon RX 5700 XT (ID=0x731f)
    Vendor:   
    VRAM:     8151 MB
    Driver:   31.0.12002.92
Begin MonoManager ReloadAssembly
- Completed reload, in  2.182 seconds
<RI> Initializing input.
<RI> Input initialized.
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initialized touch support.
UnloadTime: 0.497200 ms
RimWorld 1.4.3542 rev627
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B07E8B0080.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B078B93050.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B078FDBC80.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B078FD1010.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B079128EF0.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B0791AD010.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B07EA78620.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B053EDC000.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B078F450F0.dll
[HugsLib] version 10.0.1
Fallback handler could not load library D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Mono/data-000001B078C97710.dll
dubwise.dubsbadhygiene 3.0.2225
[HugsLib] initializing Hospitality
Loaded file (Scenario) is from version 1.2.2753 rev712, we are running version 1.4.3542 rev627. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 5 Unused Serialized files (Serialized files now loaded: 3)

Unloading 39 unused Assets to reduce memory usage. Loaded Objects now: 20714.
Total: 196.999800 ms (FindLiveObjects: 0.866200 ms CreateObjectMapping: 0.574500 ms MarkObjects: 195.393800 ms  DeleteObjects: 0.164800 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 3)
UnloadTime: 0.209300 ms

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 21032.
Total: 201.680000 ms (FindLiveObjects: 0.891800 ms CreateObjectMapping: 0.280200 ms MarkObjects: 200.371200 ms  DeleteObjects: 0.135800 ms)

Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Biotech
  - UnlimitedHugs.HugsLib
  - Orion.Hospitality
  - Dubwise.DubsBadHygiene
Unloading 0 Unused Serialized files (Serialized files now loaded: 3)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 28598.
Total: 254.597000 ms (FindLiveObjects: 1.106800 ms CreateObjectMapping: 0.989900 ms MarkObjects: 252.426000 ms  DeleteObjects: 0.074200 ms)

The Red Imperium are coming after 14.25365 days.
Covenant of Borba are coming after 31.20406 days.
Trying to spawn guests...
Parms.points = 58
Trying to spawn visitor group from Covenant of Borba.
Created 1 new pawns for Covenant of Borba.
Created 1 new pawns for Covenant of Borba.
Created 1 new pawns for Covenant of Borba.
[HugsLib][warn] Exception during log publishing (gist creation): System.Exception: HTTP/1.1 400 Bad Request
  at HugsLib.Utils.HugsLibUtility+<>c__DisplayClass22_0.<AwaitUnityWebResponse>b__0 () [0x000a6] in <4a46802aeab646ab99159f7eecb6b57e>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

loading 2 unused Assets to reduce memory usage. Loaded Objects now: 21930.
Total: 302.285600 ms (FindLiveObjects: 0.982500 ms CreateObjectMapping: 0.357100 ms MarkObjects: 300.856700 ms  DeleteObjects: 0.088700 ms)

Setting up 12 worker threads for Enlighten.
  Thread -> id: 3b88 -> priority: 1 
  Thread -> id: 4b54 -> priority: 1 
  Thread -> id: 2e40 -> priority: 1 
  Thread -> id: 2084 -> priority: 1 
  Thread -> id: 75e4 -> priority: 1 
  Thread -> id: 769c -> priority: 1 
  Thread -> id: 1f70 -> priority: 1 
  Thread -> id: 3e70 -> priority: 1 
  Thread -> id: 5de0 -> priority: 1 
  Thread -> id: 4e70 -> priority: 1 
  Thread -> id: 2fd0 -> priority: 1 
  Thread -> id: 10c4 -> priority: 1 

**Error stacktrace**
[The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
(https://gist.github.com/724f6bf844ca4da87c2121b392f2a732)
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
This has to be fixed in Dubs Bad Hygiene. Read the Steam comments if you want to fix it yourself.
