### ISSUE TITLE
I can't convert a normal bed into a guest bed.

### ISSUE THREAD

**Issue by Elecatorio20** [OrionFive/Hospitality#709]
I try to click the button where it says hospitality but does not put the red cross in a green tick.
the link:
https://gist.github.com/702c484ec3e6f9e6cdf834df71536cd9

**Comment by OrionFive** [comment]
This is not a Hospitality issue. Do note, though, that you're running an outdated version of Hospitality.

But also, apparently, everything is broken in your game.
For example:
- rjw conflicts with AlienRaces
- tons of VPE stuff doesn't load (looks like you removed the mod, but try to load a savegame where you've had it)
- similar for VSE and other Vanilla Expanded stuff (missing the mods)

You can't just remove mods and then load a savegame that needs them. But do try to use the latest Hospitality version.
