### ISSUE TITLE
Age lock Entertain job for kids

### ISSUE THREAD

**Issue by BBLKepling** [OrionFive/Hospitality#715]
**What problem does your suggestion solve**
Children can perform the entertain job at any age, Warden is locked at 10.

**Describe the solution you propose**
```
  <Operation Class="PatchOperationAdd">
    <xpath>Defs/ThingDef[defName="Human"]/race/lifeStageWorkSettings</xpath>
    <value>
      <Diplomat>10</Diplomat>
    </value>
  </Operation>

```
**Describe alternatives you've considered**
I guess kids can entertain at earlier ages.

**Comment by OrionFive** [comment]
Sounds good. Thanks for setting up the patch already.

**Comment by OrionFive** [comment]
Added to next version.
