### ISSUE TITLE
Gastronomy: Guests no longer make orders

### ISSUE THREAD

**Issue by RibbooonDev** [OrionFive/Hospitality#722]
**Describe the bug**
What happened?
----- Copied from the Steam comments -----
When my guests go hungry and instead of buying food from my restaurant, they keep scrounging food from my colonists instead. I'm not sure what I'm doing wrong. Got a cash register, hired waiters, got plenty of tables, defined shopping areas, and my food is fully stocked. I even tried a new game with just gastronomy and hospitality (along with other dependencies such as hugslib) installed to see if any of my other mods are not conflicting with each other but got still the same issue.

**To Reproduce**
1. Start any save or a new run
2. Build the restaurant, stocked all meals, assign tables for dining, etc...
3. Wait and see if they whether become patrons or not
4. Becomes a charity instead

**Console log**
Doing ctrl+F12 didn't do anything, I tried publishing the logs manually but got an error about failing to collect info. I'll put this into a pastebin as an alternative.

https://pastebin.com/JB3a8Fqg

**Error stacktrace** (Didn't seem to be an error but this was the latest stacktrace I got)
```
Gastronomy checking reservation...
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Gastronomy.Waiting.JobDriver_MakeTable:TryMakePreToilReservations (bool)
Verse.AI.Pawn_JobTracker:StartJob (Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool,System.Nullable`1<bool>,bool,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()
```

**Screenshots**
![yeah](https://user-images.githubusercontent.com/22406189/206029982-8345393c-7898-453d-a247-e992f244cbb1.png)
![yeah-2](https://user-images.githubusercontent.com/22406189/206029986-d83aec4c-6138-4e9f-8f82-8643b906aa8d.png)
![wow](https://user-images.githubusercontent.com/22406189/206029989-5ea96e43-4e2b-4dd4-abe2-c7eca02b43de.png)

**Comment by LeonTheNeedledRiolu** [comment]
1. Do the Guests have any Silver on them? (Check their Gear)

2. Is the food affordable? (I.e. can the Guests buy food with the Silver they have? Cross reference their Gear and the menu prices)

If the Guests don't have the proper Silver to afford food, they'll attempt to scrounge. At least, I think that's what's causing this.
If not, well, at least we know.

**Comment by RibbooonDev** [comment]
> 1. Do the Guests have any Silver on them? (Check their Gear)
> 2. Is the food affordable? (I.e. can the Guests buy food with the Silver they have? Cross reference their Gear and the menu prices)
> 
> If the Guests don't have the proper Silver to afford food, they'll attempt to scrounge. At least, I think that's what's causing this. If not, well, at least we know.

I didn't included that part but yes, I spawned silver for them but they still refuse to take a seat, even if I scroll the pricing bar in the cash register menu to free. Still doesn't work.

**Comment by OrionFive** [comment]
Fixed in next version.
