### ISSUE TITLE
Hospitality: Better control over visitor groups

### ISSUE THREAD

**Issue by Kalmorph** [OrionFive/Hospitality#731]
I have this experience that I think it's somewhat annoying. I had no guest beds, so everytime a guest appeared, it would ask if I would accept or refuse them, which was **nice**. Once I built my **first and only** guest bed, a group of 5 visitors automatically came in. I couldn't house all of them properly, so I had to send them away because of the lack of control over this situation.

There's two possible alternatives I think it would enhance the mod with this:
- Prompt the player to accept or refuse guests if the whole group surpass the guest beds available.
OR
- Force groups to never surpass the amount of guest beds available.

**Comment by OrionFive** [comment]
I don't have much time for new features. Also, many players dislike popups, so I'd have to make those toggleable as well. I could force groups to stay within capacity, but where's the fun in that.
Also, you can just send groups away when they appear on the map at no cost. So there's that.
