### ISSUE TITLE
Hospitality: Old people cause bad ratings

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#735]
Due to wounds, illnesses, etc. that become worse during their stay.

Just filter out 65+ guests.

**Comment by tomvd** [comment]
You can use the pawns marketvalue as a better marker of "health"?. Base value is 1750. Really crappy pawns can go as low as 175, and good pawns go up to 3000+ . I think a filter of below 1000 is perhaps a good middleground to start from.

**Comment by OrionFive** [comment]
Good solution. That would work as well.

**Comment by OrionFive** [comment]
Fixed by @tomvd by giving older guests more silver.
