### ISSUE TITLE
Gastronomy: Can't see earned money today, only earned money yesterday

### ISSUE THREAD

**Issue by Sourceoflife** [OrionFive/Hospitality#741]
**Describe the bug**
The text for "earned silver today" and "earned silver yesterday" is scrolled too far down I think due to the meal icons? Not sure how / what?

**To Reproduce**
1. Add many many different types of meals in your stock. (Fridge in the same room as the restaurant).
2. click on the cash register, create a new restaurant (press on yellow +).
3. Register has limited checkmarks for meal types, all texts about silver and earned stuff OK.
4. Select ALL meals, many icons appear.
6. Can't see silver earned today. (See attached photos)

**Console log**
No related errors I think? but here: https://gist.github.com/d496dfced0cd439d74670d070c5b5429

**Screenshots**
If you think it helps, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/14991543/223483038-b5884cf0-6504-46a7-82fc-5ee5c7c994b4.png)
![image](https://user-images.githubusercontent.com/14991543/223483081-dea9a250-3652-4f2c-8565-188bd46ba0c0.png)

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Thanks for making the issue clear. It's gonna be fixed in the next version.
