### ISSUE TITLE
Hospitality: Guests can claim an occupied bed, causing the current owner to not sleep in it

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#747]
If a guest has a Free Lovin Ideology, they can join the bed of another guest. If that other guest had as stricter Ideology, they will now refuse to sleep in their own bed.

So the fix is when claiming a bed to check if every existing owner is okay with this.

**Comment by Sourceoflife** [comment]
Maybe this is the problem I'm experiencing xD

Guests claiming beds, but just falling asleep on chairs etc. ?

[https://gist.github.com/56c70eee9ef62f92ce618caeba9386fa]

Screenshot:
[https://i.ibb.co/fNqVNQ6/Screenshot-2023-03-19-115433.png]

Guests are just standing there after eating, until they fall asleep on the chairs 🤣🤣 Wth is going on?

**Comment by OrionFive** [comment]
Yeah, it definitely is. I need to add a check so guests can't claim a bed if someone already claimed it and won't be happy with it.

**Comment by OrionFive** [comment]
It should be fixed now. Please test.
