### ISSUE TITLE
Hospitality guests loose recreation need after saving/loading

### ISSUE THREAD

**Issue by tomvd** [OrionFive/Hospitality#748]
I tried to investigate myself, but could not find the reason yet, so I am creating a ticket here, in case someone else wants to have a look.

Steps are easy to reproduce:
Core, Harmony, Hugslib and Hospitality in your modlist
Start dev quicktest
Do incident Visitorgroup Max
Let the visitors arrive and inspect their needs: they have recreation
Now save the game and load it again
Inspect the needs of the guests: they don't have recreation

**Comment by OrionFive** [comment]
Hmm. I've seen and fixed this issue before in the past. I believe I fixed it with a patch then. Maybe the patch doesn't work anymore.

There is code in Hospitality somewhere that is supposed to ensure the recreation need is present.

**Comment by tomvd** [comment]
Added logging in Pawn_NeedsTracker_Patch : reloaded a save and noticed the ___pawn.IsGuest() is always false. This causes their needs not to be set. Next step is to check why IsGuest is always false, while the pawns are marked as guest in the savegame

**Comment by OrionFive** [comment]
Fixed next version.
