### ISSUE TITLE
Price incorrect for goods

### ISSUE THREAD

**Issue by nathangur** [OrionFive/Hospitality#754]
I have Hospitality and Combat Extended installed, and my guests buy a lot of stuff from me, but the prices are completely off. 11 silver for 4 unrefined magicite (actual price would be 20) or 213 ammo for 11 silver again which should again be 20 silver. Is this correct or am I crazy?

**Comment by OrionFive** [comment]
Sounds about right. They pay about 50% of the market value, just like what you'd get if you sold to them with an unskilled colonist.

For better prices, you could give Storefront a shot.
