### ISSUE TITLE
Mod name: Cash Register

### ISSUE THREAD

**Issue by TenebruceFogoster** [OrionFive/Hospitality#756]
**Describe the bug**
What happened?
When I tried to change the hour planning of the employees on the cash register, only the numbers remained on the "employes" window.

**To Reproduce**
1. Select 'Cash register'
2. Click on the 'employes' tab
3. Clic on adding an employee or somewhere on the hours.
4. everything in the window besides the numbes is gone.

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.](https://gist.github.com/HugsLibRecordKeeper/ddec113470781827ed2a266030c6ce2d)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.
![image](https://github.com/OrionFive/Hospitality/assets/115006498/9b504b2c-d4a0-460d-bcc2-4b41b888c30a)
![image](https://github.com/OrionFive/Hospitality/assets/115006498/a1554618-a7b4-42d4-b26c-1a100ef416e0)

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
So for some reason the function for getting time and date is erroring out.

Why that happens is unclear, but odds are that something happened earlier and this is collateral damage.

It looks like MPCompat is choking on Vanilla Races Expanded. But it also chokes on Gastronomy right after. And then there's an error in Area Unlocker, but I think it's likely collateral as well.

Sorry, that's all I can tell you.

**Comment by TenebruceFogoster** [comment]
Thanks. I tryied to dsable MPCompat ("Multiplayer compatibility" by Charlotte on the steam workshop) and it worked.
If someone ask again you can tell them that it might be an incompatibility with this mod.

I wish you a nice dans and thank you again.
