### ISSUE TITLE
Hospitality: No raids (from storyteller or dev mode)

### ISSUE THREAD

**Issue by alejandro-esquivel** [OrionFive/Hospitality#765]
**Describe the bug**
I started a new game and used the storyteller that spawns raids constantly with a 3-day interval. Raids didn't spawn, I tried to use the dev mode to spawn raids but they didn't. The issue got fixed when I disabled Hospitality and its related mods (casino, storefront, vending machines & spa).

**Console log**
Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.
https://gist.github.com/HugsLibRecordKeeper/435dc9c9a32754f42dc32614bc3da2d5 with Hospitality enabled

**Mod list**
https://rentry.co/a4qon

**Comment by OrionFive** [comment]
Thanks for the log. Unfortunately, I can't use it. There are too many errors from "Gagarin" in there, so it's cut off.

Get rid of those, then we can look further.

It's pretty clear we're looking at a mod conflict here, by the way. There are close to 4000 patches to your game. The odds that one mod breaks another are massive.

**Comment by OrionFive** [comment]
This is likely related to #760.

**Comment by alejandro-esquivel** [comment]
> Thanks for the log. Unfortunately, I can't use it. There are too many errors from "Gagarin" in there, so it's cut off. Get rid of those, then we can look further. It's pretty clear we're looking at a mod conflict here, by the way. There are close to 4000 patches to your game. The odds that one mod breaks another are massive.

Is there a compatibility list that states which mods are incompatible or have issues with Hospitality?

**Comment by OrionFive** [comment]
Your best bet is to use rimpy, it has some tools and lists that may give you an incompatibility hint.
