### ISSUE TITLE
Hospitality: unable to set beds for guests

### ISSUE THREAD

**Issue by lyramaddy** [OrionFive/Hospitality#766]
https://gist.github.com/HugsLibRecordKeeper/73bb0c6632135c4e267d1f5131f7b698
the button to set the bed for guests doesn't appear when i click on a bed. i've already tried reinstalling hospitality (and every other mod) so i'm assuming it's a compatibility issue

**Comment by OrionFive** [comment]
Hmm. The only thing that really sticks out in your log is the FileNotFoundException. That's not supposed to happen. But it doesn't say what causes it. Could be anything.

Sorry, can't help you there. Maybe your savegame is borked. 🤷‍♂️
