### ISSUE TITLE
Gastronomy:  wardrobe from Uncle Boris used furniture shows dining spot gizmo. Wardrobes aren't tables ??

### ISSUE THREAD

**Issue by Chunnyluny** [OrionFive/Hospitality#769]
**Describe the bug**
What happened?

> I have tried in dev quick test, and it doesnt show any error at all but I will sent the hugslib because it will show my modlist and maybe we find out why it behaves like this. I haven't noticed it with any other furniture mods but this bug isn't game breaking. It happens only with the wardrobe from Uncle Boris used furniture, I mean the dining spots also works on the countertops of more furniture. I have no error in rimpy or rimsort. so I have no clue why the gizmo shows up when selecting wardrobe, also it displays dining spot items, so I assumed that the wardrobe was considered table because gastronomy only adds gizmo button if building is a table where you can eat at?
<https://steamcommunity.com/sharedfiles/filedetails/?id=2563508405> both in existing save game and dev quick tests. Also, my rentry link mod list with Rimsort. <https://rentry.co/7azyk>

**To Reproduce**
1. Select '...'
3. Open '....'
4. This happens

> - Open dev quick test, use command to finish all research, (the wardrobe is put in the bedroom tab because I use tab sorting mod, but it won't change showing up the diner gizmo)
> - Place the wardrobe and see that it shows a dining spot gizmo? 
> - I already asked chicken plucker if there is somewhere in the code any incorrect configuring of the wardrobe, but he said that it was not considered as table. So I was confused about the fact that the diner gizmo was showing up when selecting the wardrobe.

**Console log**
Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here. https://gist.github.com/HugsLibRecordKeeper/c558f0d850c9739ff1f3319caa0b0fb8

**Error stack trace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

![image](https://github.com/OrionFive/Hospitality/assets/102756485/ba778ef5-e52e-41aa-a78a-4e779ba73cfe)
![image](https://github.com/OrionFive/Hospitality/assets/102756485/6c6260ac-5a5e-456c-b485-d3548d7fbc3e)
![image](https://github.com/OrionFive/Hospitality/assets/102756485/31b64323-7136-49ee-80d1-e90d6a48c607)

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
I'm gonna check how it determines what a table is. Probably the dresser is using some property it rather shouldn't.

**Comment by Chunnyluny** [comment]
> I'm gonna check how it determines what a table is. Probably the dresser is using some property it rather shouldn't. 

- Thank you for your reply, hope you can find something if not can I provide anything more? Please let me know and I will share it! Btw ik ben Nederlands :)

**Comment by OrionFive** [comment]
Okay, so the key is if the def file contains `<surfaceType>Eat</surfaceType>` or inherits something that has that, like for example `TableBase`. From what I can tell that's the only criteria.

Troubleshooting werkt voor mij in het Engels wat beter :D

**Comment by Chunnyluny** [comment]
![image](https://github.com/OrionFive/Hospitality/assets/102756485/8814c987-90fa-460c-9494-1d545a5c0bea)

The same applies for the end table, but that is not meant to eat from, I think ? But the wardrobe has no function to store apparel into!

**Comment by OrionFive** [comment]
You can see at the top they used TableBase as parent. That makes it a table!

**Comment by Chunnyluny** [comment]
> You can see at the top they used TableBase as parent. That makes it a table!

fun thing if you see the comment above chicken plucker doesnt think I'm telling the truth, but I have clear evidence that is has table base, so I guess wardrobe should be more like "shelfbase" even it doesn't act like shelf/storage? Btw I provided him with the screenshot and he admitted that he had missed it and is very happy that I have given him the insigtht !

**Comment by OrionFive** [comment]
Ah, good to hear you could resolve it with him.
