### ISSUE TITLE
Hospitality: Guests don't leave, they wander without purpose

### ISSUE THREAD

**Issue by strusik** [OrionFive/Hospitality#782]
**Describe the bug**
Hi, for some reason every now and then when guests are about to leave, they are unable to do so. The game shows me a notification that they are leaving, but they just start wandering around the map without purpose doing nothing until they collapse from hunger. To fix this in game, I use the console and damage them to knock them unconscious and save them, then after saving them they rejoin me as guests and then they leave normally

**Screenshots**
Here's what it looks like in the game
![image](https://github.com/OrionFive/Hospitality/assets/136077309/9799a179-549f-4e2e-982f-7052ffe19c84)

**Console log**
https://gist.githubusercontent.com/strusik/22e99d7f97d12e13c193806b8dbea5d7/raw/d367fe2f68535879b8cf81d6b118fb8287d2bd3c/gistfile1.txt

**Comment by OrionFive** [comment]
Sorry to say, but it's not a Hospitality problem. If you look at your log, there are only errors. I can't tell what's causing it, but it looks like everything is broken.

There's a good chance you're using some mods that don't play well together. Once you only have Hospitality errors left, I can help you (maybe).

Make sure to get HugsLib working first, so you can upload logs with it (Ctrl F12).

**Comment by strusik** [comment]
> Sorry to say, but it's not a Hospitality problem. If you look at your log, there are only errors. I can't tell what's causing it, but it looks like everything is broken.
> 
> There's a good chance you're using some mods that don't play well together. Once you only have Hospitality errors left, I can help you (maybe).
> 
> Make sure to get HugsLib working first, so you can upload logs with it (Ctrl F12).

Yes, there are a lot of errors in the logs, but they are not really critical, I think you'd be surprised to know that this is the only in-game bug I've encountered 😅 So I thought maybe you could suggest what might be causing this error. And it doesn't happen all the time when guests arrive, but only occasionally, and it starts working fine after I make the buggy guests fall unconscious

By the way, when I tried to use ctrl+f12, I got an error sending the log, so I had to copy it to the clipboard and upload it to my github

**Comment by OrionFive** [comment]
They certainly are critical - every exception means that code doesn't get run that should run.
What's causing this bug? All the exceptions are causing it (well, likely one of them).
That HugsLib log sharing doesn't work correctly is another sign that you've got too many broken mods...

**Comment by strusik** [comment]
> They certainly are critical - every exception means that code doesn't get run that should run. What's causing this bug? All the exceptions are causing it (well, likely one of them). That HugsLib log sharing doesn't work correctly is another sign that you've got too many broken mods...

Well, I've just double-checked and analyzed my entire mod list and I want to say that it all works in the game and everything is loaded. I'm not trying to argue with you and I fully accept your point of view, moreover I don't know much about the technical part, I just want to state the funny fact that despite all your horror at what you've seen, it all works and during the whole game I only encountered this bug, which I wrote about here 😅😅😅

Now, as for the case, I tried to look through the logs, as far as I understand it, and noticed that in quite a few cases the Combat Extended mod is mentioned, which I don't have, and maybe these errors appear because the mods just can't find CE. But definitely one of the mods is breaking your mod and unfortunately I have no idea how to determine which one, at least because I don't know how to reproduce this bug, as it seems to me to happen randomly

**Comment by OrionFive** [comment]
You're lucky then, that none of the crashes that happen constantly in the background while you're playing are affecting your game.

I've seen and analysed hundreds of logs, and this is one of the worst cases I've seen.

Note that most of these aren't errors, but exceptions. Exceptions mean that the code is interrupted and whatever should be running after doesn't - like maybe a function that is essential for Hospitality.

Until you find the right one, assume that all of them are breaking Hospitality. A healthy game should not have a single exception, from start to end.

What can also cause exceptions is a broken game state / save game. Game state can be broken by removing mods, poorly written mods, mod conflicts, and most of all, exceptions. So it's also quite possible that with a new game the exceptions will not happen.

So I would start there: Create a new game. Focus on exceptions you get then. Fix those. Repeat.

And by fix I mean toss out mods until you get no exceptions with a new game. Then add them back one by one until you know all the culprits.

**Comment by strusik** [comment]
> You're lucky then, that none of the crashes that happen constantly in the background while you're playing are affecting your game.
> 
> I've seen and analysed hundreds of logs, and this is one of the worst cases I've seen.
> 
> Note that most of these aren't errors, but exceptions. Exceptions mean that the code is interrupted and whatever should be running after doesn't - like maybe a function that is essential for Hospitality.
> 
> Until you find the right one, assume that all of them are breaking Hospitality. A healthy game should not have a single exception, from start to end.
> 
> What can also cause exceptions is a broken game state / save game. Game state can be broken by removing mods, poorly written mods, mod conflicts, and most of all, exceptions. So it's also quite possible that with a new game the exceptions will not happen.
> 
> So I would start there: Create a new game. Focus on exceptions you get then. Fix those. Repeat.
> 
> And by fix I mean toss out mods until you get no exceptions with a new game. Then add them back one by one until you know all the culprits.

This is my second playthrough with this mod, which I started quite recently, so it's basically a new game and this problem persisted (it was also in the last playthrough, but just now I decided to post here about this bug)

And as for excluding mods, as I said this bug happens randomly, most guests leave completely normal. So finding such a mod would take forever if you start a new game every time and wait for the very probability at which the bug occurs. I had a theory that this happens with factions that are added by mods, but no, literally just now, members of the faction that had this bug before left the map in a completely normal way. So it looks like I'll just have to play with this and using the console in case of a bug to give the guests anesthesia effects and save them so they leave normally afterwards

P.S. Your reaction to my mod build made me smile, because for me opening a debug window with a bunch of red errors was the order of the day, because everything works like a Swiss watch (except for this bug with guests) 😂😂 This proves that Rimworld, although poorly optimized, is an incredibly stable game, as I'm the kind of person who is a mod fanatic and a collection of 300+ mods is fine for me, but of all the games I've ever modified, I've never managed to kill Rimworld, every time it keeps starting up and running no matter how crazy the mod collection I make is 👀🙈

**Comment by OrionFive** [comment]
You shouldn't take the bug happening as indicator. It's just collateral damage.

You should take the presence of any exceptions and errors in your log as indicator.

RimWorld is most definitely an extremely stable game. Any other game would crash before you even reach the main menu, let alone load the game and play it for hours.
