### ISSUE TITLE
Mod name: Pawn Group Marker cannot detect permanent enemy faction mods( As Void and VFE Pirate...)                            

### ISSUE THREAD

**Issue by Adolf152** [OrionFive/Hospitality#784]
**Describe the bug**
It said bc some mod add faction config or the PawnGroupMarker somehow not detect them cause the visitor cannot visit from those mod faction?(Is it bc pirate and void faction usually permanent enemy?)

**To Reproduce**
Just have VFE Pirate or Void(any mod add faction is or can be permanent enemy)

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.](https://gist.github.com/HugsLibRecordKeeper/d87ae873b93c3faee5e2ef5adf33675b)

**Error stacktrace**
Not it all in the log.
```
Paste it here
```

**Screenshots**
I dont have

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by Adolf152** [comment]
Can search this in the log for easier: FactionDef VFEP_Mercenaries must have at least one pawnGroupMaker

**Comment by OrionFive** [comment]
Permanent enemies can't visit. But also factions without a defined pawn group maker can't visit. This is not a bug in hospitality but in the faction that misses this.
