### ISSUE TITLE
Hospitality: Not yet compatible with 1.5

### ISSUE THREAD

**Issue by Mate119** [OrionFive/Hospitality#787]
So i downloaded the mod and saw that after getting raided the corpses that are being killed just disappear without a trace.I thought it might be my guns because they do a lot of damage but i checked the logs,saw the red errors,tried to remove the mod and suddenly the corpses are back.I dont know what could possibly causing the issues but i am playing on an experimental branch with github version of Hospitality

Just download the mod and try killing a corpse at least thats how it is for me.

**Console log**
(https://gist.github.com/HugsLibRecordKeeper/2d69ac990040d3414c1a4f7d2e1c750b)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Could not do PostLoadInit on Corpse_Human583475: System.InvalidCastException: Specified cast is not valid.
  at Hospitality.CompGuest.PostExposeData () [0x000c7] in <4ee53fb730da4ba78385dd4aeeffc271>:0 
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Verse.ThingWithComps.ExposeData_Patch1(Verse.ThingWithComps)
  at Verse.Corpse.ExposeData () [0x00000] in <8ee6c9f7570646cabb8981ee61cb9b87>:0 
  at Verse.PostLoadIniter.DoAllPostLoadInits () [0x00032] in <8ee6c9f7570646cabb8981ee61cb9b87>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch1 (string)
Verse.PostLoadIniter:DoAllPostLoadInits ()
Verse.ScribeLoader:FinalizeLoading ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.LoadGame_Patch1 (Verse.Game)
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__28_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()


**Screenshots**
![Hospitality](https://github.com/OrionFive/Hospitality/assets/140758871/cbe02ddf-50f8-403c-a86a-9e76bcd0de0b)


Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Pretty simple. You're trying to run Hospitality with RimWorld 1.5. But Hospitality isn't updated to 1.5 yet. It won't work.

**Comment by Mate119** [comment]
> Pretty simple. You're trying to run Hospitality with RimWorld 1.5. But Hospitality isn't updated to 1.5 yet. It won't work.

But i checked the github version of hospitality and it says its 1.5 compatible and Rimpy also doesnt seem to have any issues with it. But in any case thanks for the answer

**Comment by OrionFive** [comment]
Yeah, that's not a release. It's the first test version.

Rimpy can't tell the difference.
