### ISSUE TITLE
Hospitality: Causes pawns to go missing

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#789]
So after saving and loading with Hospitality, pawns go missing:
`Could not resolve reference to object with loadID Thing_Human143294 of type Verse.Pawn. Was it compressed away, destroyed, had no ID number, or not saved/loaded right? curParent=RimWorld.TaleData_Pawn curPathRelToParent=`

Full log:
https://gist.github.com/HugsLibRecordKeeper/e799740765ad7008c869ea8654fabe6f

No idea what exactly causes this.

**Comment by OrionFive** [comment]
@tomvd any ideas?

**Comment by OrionFive** [comment]
It doesn't happen every time. If I go back to a savegame without this issue and save and load, it is fine.

**Comment by tomvd** [comment]
Unfortunately not being able to reproduce this. Do other people encounter the same issue? The log mentions a few other mods too. I tried hospitality on vanilla rimworld (and then 3 more DLCs in another game) to rule out any other mods acting weird.

**Comment by OrionFive** [comment]
You do have a point that it could be one of the other mods. I think the plausible candidates are Portraits of the Rim and One Big Family.

**Comment by OrionFive** [comment]
It happened again with only Hospitality - but I couldn't reproduce it until I added more mods. It seems like a world pawn gets eventually cleaned up, but is referenced by others as spouse and such.

It might be that it's actually a vanilla bug?

**Comment by LrdHamster** [comment]
Hello, Appreciator of Hospitality here. Saw your request for assistance, I've managed to bang out a way to replicate this issue, albiet with one extra mod to make it a bit more possible, and to maybe get more useful logs, Rimsaves. Have an AHK script that waits 20 seconds on 4x speed, quicksaves, then quickloads. Got the could not resolve reference warning twice today while running rimworld on my laptop off to the side.

Hospitality 1.5 from github is named HospitalityDEV

Savegame that I started as a baseline: (Rename to .rws)
[PawnRemovalPotential.txt](https://github.com/OrionFive/Hospitality/files/15003002/PawnRemovalPotential.txt)

Here's a truncated log, as it didn't save to player.txt cause I forgot I had it open in another program like an idiot. Had to copy off the debug log itself. 
[rimworldlog.txt](https://github.com/OrionFive/Hospitality/files/15002808/rimworldlog.txt)

Actions taken that may help:
Debug mode spawn 10x visitors via debug menu

**Comment by tomvd** [comment]
Is there any relation to the "percentage of known pawns" setting?

**Comment by OrionFive** [comment]
> Is there any relation to the "percentage of known pawns" setting?

What's that from? Not Hospitality, I think.

**Comment by OrionFive** [comment]
I give up on this. I can't properly reproduce it.
