### ISSUE TITLE
Hospitality : Wont allow me to open up debug menu to spawn stuff and raiders keep on dissapearing

### ISSUE THREAD

**Issue by Skulldrain64** [OrionFive/Hospitality#790]
https://gist.github.com/HugsLibRecordKeeper/414dc3602e89174e2a61f38cd29d23a6

**Comment by OrionFive** [comment]
Looks like you're trying to run RimWorld 1.5 with Hospitality 1.4.

**Comment by Skulldrain64** [comment]
> Looks like you're trying to run RimWorld 1.5 with Hospitality 1.4.
Ah alright sorry I didn't know it wouldn't be compatible with the new version of rimworld though do you have one that will work with 1.5 if not then thats alright and thank you for your help

**Comment by OrionFive** [comment]
The 1.5 version is uploaded now. Restart Steam to get it.
