### ISSUE TITLE
Hospitality: Cant gain recreation

### ISSUE THREAD

**Issue by SwizzlesJ** [OrionFive/Hospitality#794]
**Describe the bug**
What happened?

**To Reproduce**
Once the rec need drops low enough you start getting this error. 

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.](https://gist.github.com/HugsLibRecordKeeper/a51cee9825d649b04a6aac0db2e2b68c)

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
Exception in RimWorld.ThinkNode_Priority_GetJoy TryIssueJobPackage: System.TypeLoadException: Could not resolve type with token 0100005b (from typeref, class/assembly Hospitality.ItemUtility, Hospitality, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
[Ref 746CA8F1] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob (Verse.ThinkTreeDef&,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch4 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch1 (Verse.AI.Pawn_JobTracker)
Verse.Pawn:Tick ()
DTimeControl.TCTickList:TickThing (Verse.Thing)
DTimeControl.TCTickList:DoTick (double,bool)
DTimeControl.TimeControlBase:TickManagerTick (Verse.TickManager,bool)
DTimeControl.Core_Patches.Patch_DoSingleTick_Prefix:Prefix (Verse.TickManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch3 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

**Comment by OrionFive** [comment]
This error happens if you're using a mod that depends on Hospitality but isn't compiled against the latest version.

Please double-check that you're using the latest mods (maybe restart Steam).

**Comment by SwizzlesJ** [comment]
Ah cheers, looks like its store front causing the issue unfortunately. Once that was removed no more errors :)
