### ISSUE TITLE
Hospitality

### ISSUE THREAD

**Issue by kadem2** [OrionFive/Hospitality#797]
Getting an error log for the following:

**Console log**
[PTG] PawnTableGrouped.HospitalityBridge was activated but failed initialization, integration disabled:
NullReferenceException: Object reference not set to an instance of an object

UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
PawnTableGrouped.LogHelper:Log (string,PawnTableGrouped.MessageType)
PawnTableGrouped.LogHelper:LogException (string,System.Exception)
PawnTableGrouped.ModBridge:Resolve (bool,HarmonyLib.Harmony)
PawnTableGrouped.Mod:DetectMods ()
PawnTableGrouped.ModPostInit:.cctor ()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor (System.RuntimeTypeHandle)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.StaticConstructorOnStartupUtility.CallAll_Patch2 ()
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_4 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

**Comment by OrionFive** [comment]
HospitalityBridge is not from Hospitality. It's from Pawn Table Grouped, whatever that is.

**Comment by kadem2** [comment]
Ah, it’s a conflict between Hospitality and Grouped Pawn Lists. That mod author listed a fix though. Thanks!
