### ISSUE TITLE
Mod name: Name of the problem

### ISSUE THREAD

**Issue by Ruhi666** [OrionFive/Hospitality#806]
**Describe the bug**
I can't set up a visitor bed with module anymore

**To Reproduce**
1. Go on an SRTS Expanded module spaceship and fly to the mecha mission location
2. Found that I couldn't open the UI(Such as God mode,Return to the main menu)
3. Reboot
4. The visitor bed disappears and i can't set up a visitor bed with module anymore

**Console log**
 https://gist.github.com/HugsLibRecordKeeper/0c21e9f8e265c3897b5c3ef4ac5bdb18

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Failed to find Verse.ThingDef named 'RGK_bedDoubleGuest'. DefDatabase<Verse.ThingDef> contains a total of 14784 loaded defs.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
PerformanceFish.Log/Config/<>c:<.cctor>b__12_2 (string)
PerformanceFish.Log:Error (FisheryLib.Pools.PooledStringHandler)
PerformanceFish.Defs.DefDatabasePatches/Replacement`1<Verse.ThingDef>:LogMissingDef (string)
Hospitality.Building_GuestBed:MakeBed (RimWorld.Building_Bed,string)
System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
SoftWarmBeds.Hospitality_Patch:Swap (object,RimWorld.Building_Bed,RimWorld.StorageSettings,SoftWarmBeds.CompMakeableBed)
SoftWarmBeds.Hospitality_Patch:SwapPatch (object,RimWorld.Building_Bed)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Hospitality.Building_GuestBed.Swap_Patch1 (RimWorld.Building_Bed)
Hospitality.Patches.Building_Bed_Patch/GetGizmos/<>c__DisplayClass1_0:<Process>b__0 ()
Verse.Command_Toggle:ProcessInput (UnityEngine.Event)
Verse.GizmoGridDrawer:DrawGizmoGrid (System.Collections.Generic.IEnumerable`1<Verse.Gizmo>,single,Verse.Gizmo&,System.Func`2<Verse.Gizmo, bool>,System.Func`2<Verse.Gizmo, bool>,System.Func`2<Verse.Gizmo, bool>,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0 (System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos ()
RimWorld.InspectPaneUtility:ExtraOnGUI (RimWorld.IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI ()
Verse.WindowStack:WindowStackOnGUI ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.UIRoot_Play.UIRootOnGUI_Patch3 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root.OnGUI_Patch2 (Verse.Root)
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Your ` VSE.SkillsMod` is croaking. `VoiceroidAsAnimal` is failing a patch. Some mod name is too long, causing an exception. 
Finally, hospitality fails to create a bed def for some bed. It's possible this is collateral for any of the previous issues, or you're using a bed from a mod that is not created properly.

This is the first time I see this issue, so it's 99% on your end. I would recommend fixing everything causing exceptions in order of occurrence. 

I hope that helps.
