### ISSUE TITLE
Colonists won't do Recreation/joy

### ISSUE THREAD

**Issue by xxmilkxx** [OrionFive/Hospitality#820]
**Describe the bug**
What happened?
While I was playing my main save, I noticed that none of my colonists were building any recreation/joy unless I manually gave them drugs. I went through all of my mods one by one (I've never dealt with this kind of bug, and I couldn't find anything online to help me) and found with Hugslibs that Hospitality is causing the issue. I took it out, the game worked, put it back in, and recreation stopped working. 

**To Reproduce**
1. Assign recreation
2. Colonists do not recreate, instead cleaning or working, an error pops up

**Console log**
https://gist.github.com/HugsLibRecordKeeper/085c8231d10c974aa9c7b17554af3360

**Error stacktrace**

Exception in RimWorld.ThinkNode_Priority_GetJoy TryIssueJobPackage: System.TypeLoadException: Could not resolve type with token 0100005b (from typeref, class/assembly Hospitality.ItemUtility, Hospitality, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
[Ref C275B9A] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch1 (string)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.ThinkTreeDef&,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Glue:AbiFixup<Verse.AI.ThinkResult Verse.AI.Pawn_JobTracker:DetermineNextJob(Verse.ThinkTreeDef&, System.Boolean),Verse.AI.ThinkResult Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch1(Verse.AI.Pawn_JobTracker, Verse.ThinkTreeDef&, System.Boolean)> (Verse.AI.Pawn_JobTracker,Verse.AI.ThinkResult&,Verse.ThinkTreeDef&,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch2 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

(Sorry if this is poorly done, I've never reported a bug and I don't quite understand how logs work!)

**Comment by OrionFive** [comment]
The bug report is solid. Unfortunately, there are no good leads to what causes the problem. It's looking for a class and can't find it.

You could try resubscribing hospitality (and check if nothing is left behind in the Hospitality folder).

It's not something I can fix. This is a case of one specific setup where it doesn't work as it should (could be a botched download or anything really).

It's also possible that it conflicts with some other mod, but it doesn't *look* like it. It's still possible, though. It could be something innocent, like a poorly made item lying somewhere on the map.

Good luck!

**Comment by OrionFive** [comment]
This has been closed for a while, but by chance, I noticed a post where this particular issue was solved before. So here's for posterity: #794
