### ISSUE TITLE
Hospitality: Blacklist for item gifting

### ISSUE THREAD

**Issue by chief-turkler** [OrionFive/Hospitality#821]
**What problem does your suggestion solve**
There are a lot of items, like ammo from Combat Extended, which add items which really shouldn't appear as gifts. I've gotten reports of this being an issue from users of my mods:

![image](https://github.com/user-attachments/assets/655869c2-4108-48c2-ab49-394687dbdde2)

**Describe the solution you propose**
 An XML tag to blacklist items from gift generation would solve this issue.

**Describe alternatives you've considered**
Hard-coding the blacklisted defs in the assemblies would work too, wouldn't even be that hard.

            string defName = thing.def.defName;
            if (defName.StartsWith("Ammo_") || defName.StartsWith("AVCE_Ammo_"))

This would, however, just kick the bucket down the road. This would start to be a bother as more and more mods ask for their items to be blacklisted as well. An XML tag you can slap onto any def would be far more modular.

Adding features takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Hospitality just uses the built-in RimWorld gift system.

So without Hospitality this can happen just the same. So this is a general issue, not a Hospitality one. I suppose it should be reported to Ludeon instead.
