### ISSUE TITLE
Cash register: Register affects work priority

### ISSUE THREAD

**Issue by r0emek** [OrionFive/Hospitality#824]
**Describe the bug**
When cash register is built (with or without assigned workers) colonists stops executing duties with lower priorities.

Just removing (dev mode) cash registry building (and redraft colonist) allows them to perform duties of lower priority. 

**To Reproduce**
1. Build cash register. 
2. assign lower priority (3) work to colonists

**Console log**
(https://gist.github.com/HugsLibRecordKeeper/f7a59d35ece770c41177d91aedc495f3)

**Error stacktrace**
CashRegister.WorkGiver_EmptyRegister provided target Thing_CashRegister_CashRegister710586 but yielded no actual job for pawn V. The CanGiveJob and JobOnX methods may not be synchronized.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch1 (string)
Verse.Log:ErrorOnce (string,int)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1 (RimWorld.JobGiver_Work,Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Glue:AbiFixup<Verse.AI.ThinkResult RimWorld.JobGiver_Work:TryIssueJobPackage(Verse.Pawn, Verse.AI.JobIssueParams),Verse.AI.ThinkResult RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1(RimWorld.JobGiver_Work, Verse.Pawn, Verse.AI.JobIssueParams)> (RimWorld.JobGiver_Work,Verse.AI.ThinkResult&,Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob (Verse.ThinkTreeDef&,bool)
Verse.AI.Pawn_JobTracker:CheckForJobOverride_NewTemp (single,bool)
Verse.AI.Pawn_JobTracker:CheckForJobOverride (single)
Storefront.Selling.Toils_Selling/<>c__DisplayClass0_0:<WaitForBetterJob>g__TickAction|1 ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch2 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

Error occurs just on game load for random colonist that is assigned as well as not assigned to sell duty.
With colonists with registry schedule as without.

Screen:
![20241021171006_1](https://github.com/user-attachments/assets/8a27bfcd-bdc2-4cfd-a7da-0bad9076654b)

Similar problem: https://www.reddit.com/r/RimWorld/comments/1frvztb/pawns_idling_and_not_doing_low_priority_works/

**Comment by OrionFive** [comment]
This is by design. If you want them to do other tasks as well, you have to disable "standby" on the register (it's one of the gizmo buttons).

I don't know why you're getting the error, though. I don't think it's related, but it might be.
