### ISSUE TITLE
Hospitality: Guests can't spawn

### ISSUE THREAD

**Issue by Yachuk** [OrionFive/Hospitality#825]
**Describe the bug**
Guests cannot appear when the game tries to spawn them
**To Reproduce**
1. Select 'Debug action'
2. Click on 'Do incident (map)'
3. Open 'VisitorGroup'
4. This happens

**Console log**
[Press Ctrl-F12 after the issue has occurred. You will get a link. Put it here.]
https://gist.github.com/HugsLibRecordKeeper/6392054b33e9e618049e41666cf797b6

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
Hospitality: Something failed when setting up visitors from faction Белое Ханство (мирное племя):
System.InvalidOperationException: Sequence contains no matching element
[Ref 9740E2D3]
 at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
 at AlienRace.CachedData.GetApparelFromApparelProps (RimWorld.ApparelProperties props) [0x0002f] in <a85659a3d060459285306e05bfed23d7>:0 
 at AlienRace.HarmonyPatches.PawnCanWearPostfix (RimWorld.ApparelProperties __instance, Verse.Pawn pawn, System.Boolean& __result) [0x00000] in <a85659a3d060459285306e05bfed23d7>:0 
 at RimWorld.ApparelProperties.PawnCanWear (Verse.Pawn pawn, System.Boolean ignoreGender) [0x00039] in <2a40c3593b334f29ac3cb3d32d652351>:0 
     - POSTFIX RedMattis.BetterPrerequisites: Void BigAndSmall.CanEquip:PawnCanWear(ApparelProperties __instance, Boolean& __result, Pawn pawn)
     - POSTFIX rimworld.erdelf.alien_race.main: Void AlienRace.HarmonyPatches:PawnCanWearPostfix(ApparelProperties __instance, Pawn pawn, Boolean& __result)
 at RimWorld.Apparel.PawnCanWear (Verse.Pawn pawn, System.Boolean ignoreGender) [0x0001c] in <2a40c3593b334f29ac3cb3d32d652351>:0 
     - POSTFIX RedMattis.BetterPrerequisites: Void BigAndSmall.CanEquip:RequiredForPawn(Apparel __instance, Boolean& __result, Pawn pawn, Boolean ignoreGender)
     - POSTFIX RJW_Menstruation: Void RJW_Menstruation.PawnCanWear_Patch:Postfix(Boolean& __result, Apparel __instance, Pawn pawn)
 at RimWorld.Pawn_ApparelTracker.Wear (RimWorld.Apparel newApparel, System.Boolean dropReplacedApparel, System.Boolean locked) [0x000dd] in <2a40c3593b334f29ac3cb3d32d652351>:0 
     - TRANSPILER rimworld.erdelf.alien_race.main: IEnumerable`1 AlienRace.HarmonyPatches:BodyReferenceTranspiler(IEnumerable`1 instructions)
     - PREFIX rjw: Boolean rjw.PATCH_Pawn_ApparelTracker_Wear:prevent_wear_by_gear(Pawn_ApparelTracker __instance, Apparel& newApparel)
     - POSTFIX Krkr.RocketMan: Void RocketMan.Patches.Pawn_Notify_Dirty+Pawn_ApparelTracker_Dirty:Postfix(Pawn_ApparelTracker __instance)
     - POSTFIX OskarPotocki.VFECore: Void VanillaApparelExpanded.ApparelTracker_Wear:Postfix(Apparel newApparel, Pawn_ApparelTracker __instance)
     - POSTFIX OskarPotocki.VFECore: Void VFECore.Pawn_ApparelTracker_Wear_Patch:Postfix(Pawn_ApparelTracker __instance, Apparel newApparel, Boolean dropReplacedApparel, Boolean locked)
     - POSTFIX rjw: Void rjw.PATCH_Pawn_ApparelTracker_Wear:on_wear(Pawn_ApparelTracker __instance, Apparel newApparel)
 at Hospitality.Utilities.ItemUtility.TryGiveBackpack (Verse.Pawn p) [0x00072] in <f086b02670a441c7ac199f90ab536abf>:0 
 at Hospitality.IncidentWorker_VisitorGroup.GiveItems (System.Collections.Generic.IEnumerable`1[T] visitors) [0x00025] in <f086b02670a441c7ac199f90ab536abf>:0 
 at Hospitality.IncidentWorker_VisitorGroup.SpawnGroup (RimWorld.IncidentParms parms, Verse.Map map) [0x000a2] in <f086b02670a441c7ac199f90ab536abf>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
Hospitality.IncidentWorker_VisitorGroup:SpawnGroup (RimWorld.IncidentParms,Verse.Map)
Hospitality.IncidentWorker_VisitorGroup:TryExecuteWorker (RimWorld.IncidentParms)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.IncidentWorker.TryExecute_Patch2 (RimWorld.IncidentWorker,RimWorld.IncidentParms)
Verse.DebugActionsIncidents/<>c__DisplayClass6_1:<GetIncidentDebugAction>b__3 ()
LudeonTK.DebugActionNode:Enter (LudeonTK.Dialog_Debug)
LudeonTK.Dialog_Debug:DoButton (LudeonTK.DebugActionNode,single,bool)
LudeonTK.Dialog_Debug:DrawNode (LudeonTK.DebugActionNode,single,bool)
LudeonTK.DebugTabMenu:ListOptions (int,single)
LudeonTK.Dialog_Debug:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Looks like an incompatibility with BetterPrerequisites; or a broken save game. You have lots of other errors that happen when loading, which would be an indicator for the latter.

Good luck!

**Comment by Yachuk** [comment]
> Looks like an incompatibility with BetterPrerequisites; or a broken save game. You have lots of other errors that happen when loading, which would be an indicator for the latter.
> 
> Good luck!

Thanks for the quick response. Apparently “BetterPrerequisites” is a component of the “Big and Small - framework” mod, disabling it and quick start allowed to spawn guests. Perhaps the problem is that some pawns in the guest group are trying to spawn with the “giant” weapon from B&S Framework, which is impossible to pick up without the giant trait/genes on the pawn.

**Comment by OrionFive** [comment]
That's quite possible, yeah.
