### ISSUE TITLE
Hospitality/Hospitality Casino: Pay off raiders

### ISSUE THREAD

**Issue by DAzombis** [OrionFive/Hospitality#828]
**What problem does your suggestion solve**
Casinos are known for having huge stores of money or in this case silver, raiders also if they can will steal items if they deem its more worth then attacking the rest of the colony
**Describe the solution you propose**
Pay of the raiders with a certain amount of silver based of the silver the colony has aka the wealth
**Describe alternatives you've considered**
Show the raiders a good time at the casino/hotel and if they enjoy their time you may gain the ability to pay for their protection instead allowing them to stay in a nearby zone if tribal or drop pod in if you are attacked. If you dont want to pay protection anymore you can raid the area they are residing in which is very close (1 to 3 tiles away)

Adding features takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Maybe something for @tomvd
Seems out of scope to me, though. I think it should be a loose mod. Apart from story it doesn't actually have any overlap with casino.

**Comment by tomvd** [comment]
Indeed, better try the mod request channel on the rimworld discord. If I understand correctly you want before a raid starts a popup with the option to give away silver instead of being attacked. A fair mod request someone might pick up.
