### ISSUE TITLE
Hospitality: Guests remove headgear despite their ideoligion

### ISSUE THREAD

**Issue by llunak** [OrionFive/Hospitality#829]
When guests arrive, they remove their headgear and keep it in the inventory (this is a feature I guess). But if their ideoligion requires covered head, they get a negative moodlet about it.

**To Reproduce**
1. Have a faction with ideoligion that has "Female clothing" as "Pants, shirt and hat" (or male version).
2. Wait for guests from that faction to arrive and remove their headgear.
3. Check their mood and see the "Uncovered ..." mood debuff.

**Comment by OrionFive** [comment]
Good call.
