### ISSUE TITLE
Animal boxes designated for guests read back as error

### ISSUE THREAD

**Issue by PlacentaPeanut** [OrionFive/Hospitality#86]
Is causing all save files with guest designated animal boxes to not load map. Only started after most recent update. Logs are bellow as well as a screenshot of my error log.

http://steamcommunity.com/sharedfiles/filedetails/?id=972093417

https://gist.github.com/HugsLibRecordKeeper/d1ba6544250fe914bc4e0a454698f8c8

**Comment by OrionFive** [comment]
Thanks for the report. I've pushed a [commit](https://github.com/OrionFive/Hospitality/commit/810d39a43a00b439d538a93494d318990111fe70) for testing (only here, not on Steam yet). If you can spare the time, please test if it is fixed now. Then I'll update it on Steam.

**Comment by OrionFive** [comment]
Unless you report it's still broken, I consider this fixed. New version is uploaded later today.

**Comment by PlacentaPeanut** [comment]
Thank you for fixing it. It doesn't seem to have been updated on Steam,
though.

**Comment by OrionFive** [comment]
No, unfortunately I didn't have any time to upload it yesterday. I'll try again today.
