### ISSUE TITLE
Game is spamming "Visitors from so and so are leaving over and over again.

### ISSUE THREAD

**Issue by Nuclearmayhem** [OrionFive/Hospitality#88]
Posting of the log

https://gist.github.com/HugsLibRecordKeeper/620f237fb474359210e8618c43b0567d

I had a group of visitors come in who were from a hostile faction but seemed willing to visit, after a few mins they started beating each other up.  Since they were hostile I could only capture the injured parties.  The beeping stopped once everyone was captured (the remaining one tried to help in a prison break so I arrested him)

I can provide a save file if needed.

**Comment by OrionFive** [comment]
I've added an extra check against hostile visitors. Hopefully that will prevent this issue in the future.
