### ISSUE TITLE
Selling prisoners to guests causes them to get stuck when they leave

### ISSUE THREAD

**Issue by 5katz** [OrionFive/Hospitality#89]
it pushes the message that the visitors are leaving 10-15 times a second without them going anywhere, plus it makes this error every tick: 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Int32,System.Single].get_Item (Int32 key) [0x00000] in <filename unknown>:0 
  at Hospitality.LordToil_VisitPoint.GetVisitScore (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Hospitality.LordToil_VisitPoint.Leave () [0x00000] in <filename unknown>:0 
  at Hospitality.LordToil_VisitPoint.Cleanup () [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Lord.GotoToil (Verse.AI.Group.LordToil newLordToil) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Transition.Execute (Verse.AI.Group.Lord lord) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Transition.CheckSignal (Verse.AI.Group.Lord lord, TriggerSignal signal) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Lord.CheckTransitionOnSignal (TriggerSignal signal) [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.Lord.LordTick () [0x00000] in <filename unknown>:0 
  at Verse.AI.Group.LordManager.LordManagerTick () [0x00000] in <filename unknown>:0 
  at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

pls halp

**Comment by OrionFive** [comment]
Does this happen every time or only this once?

**Comment by 5katz** [comment]
i dont know, this ois the first time and i havent had visitors since, ill tell you when the next visitors leave or cant leave

**Comment by castalme** [comment]
I literally just had the same problem. Saw this:

https://steamcommunity.com/app/294100/discussions/0/359547436758273011/

I sold them a slave, so I think that's what my problem was. I didn't find a way to fix it, and unfortunately I didn't have a save while the visitors were there before I sold her, so I couldn't see for sure.

**Comment by OrionFive** [comment]
That could easily be. Selling slaves is bad, m'kay?
I can definitely see how that trips Hospitality up.

**Comment by 5katz** [comment]
OH YEAh, i sold them a slave too, that made them flip out when leaving

**Comment by castalme** [comment]
I was so poor, and they were going to pay so much...

I've never had this problem with Hospitality before, but that was the first time I sold a living creature to the visitors too.

**Comment by 5katz** [comment]
soo, no slavery to visitors?

**Comment by OrionFive** [comment]
I'll see if I can fix it. Are we talking about prisoners or slaves from a mod? 

Maybe you can update the issue description to be more descriptive.

**Comment by castalme** [comment]
I'm not using any mods that affect prisoners or slaves.

Alright-- so I sold the prisoner to them on the first day that they arrived (I only traded with them that day), and for the duration of their stay I didn't have any of the Guest settings changed from default other than that I was entertaining them. A few days later, they tried to leave naturally and the "visitors are leaving message" would ping multiple times a second continuously for the entirety of the time I kept playing that save as I tried to fix it (a few in-game days). The visitors never actually left, and just continued loitering around the base. I could no longer trade with them, but my pawns kept entertaining them.  I tried to corral them with a restriction into a room but half of them ignored it and left the home area to wander around the edges of the map without actually leaving. The "Send Away" button didn't do anything.

I deleted the broken save like a fool, so I don't have the debug error but I believe I was getting the same one 5katz posted.

**Comment by OrionFive** [comment]
If you want to recover from an error like that, you can better load a previous autosave. But it sounds like it should be pretty straightforward for me to reproduce the problem by selling a prisoner to guests.

**Comment by OrionFive** [comment]
Hm. I tried to reproduce this. But I noticed it should not be possible to sell prisoners to guests in the first place.

**Comment by Nuclearmayhem** [comment]
I have this feeling it's from one of the Call of Cthulhu mods I have installed but I also was able to sell prisoners to guests and am having the same problem of it constantly spamming visitors are leaving.

https://gist.github.com/HugsLibRecordKeeper/2c104d18e15a48f759dad48e78e08ba1

I can also provide the save file if need be.

**Comment by OrionFive** [comment]
Well there are two general rules: 
1. Don't use mods that add prisoners to guest traders.
2. Don't sell prisoners to guests.
If you break either of those rules, you'll break your game. It's not that hard. Also, it's not going to be fixed anytime soon either.

**Comment by OrionFive** [comment]
This should theoretically be fixed now. *crossesfingers*
