### ISSUE TITLE
Items of recruited pawn should be given to other visitors

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#90]
Or they should be more expensive. Any opinions?

**Comment by jaaqov** [comment]
Sounds fair, but I guess it would be better to let them join without ther inventory.. only makes sense imo.

**Comment by OrionFive** [comment]
Yeah I had a case where recruiting the right person early on gave me access to a weapon that made the first part of the game laughably easy. 

So I suppose the equipment should go to the rest of the visitors. And if one of them comes alone you just got lucky.
