### ISSUE TITLE
Hospitality blocks incidents

### ISSUE THREAD

**Issue by frokes** [OrionFive/Hospitality#92]
Have done some testing and singled out Hospitality to be the mod causing my game to not spawn any incidents (neither good nor bad). When forcing a raid with the dev tools i get the error shown in the screenshot.

![hospitality bug](https://user-images.githubusercontent.com/9216441/28746426-65d95c98-748c-11e7-9c70-7bd1ffac18a0.PNG)

**Comment by frokes** [comment]
Further singeled it down to a conflict between Medival times and Hospitality. Hope this helps

**Comment by OrionFive** [comment]
Thanks for narrowing it down! Would you mind clicking that error and sending me a copy/screenshot of the expanded view?

**Comment by frokes** [comment]
Sure! 
![hospitality bug 2](https://user-images.githubusercontent.com/9216441/28751948-734975a6-7514-11e7-87b5-5d7127f13392.PNG)
Starting to think that it might have something to do with creating / abandoning secondary town

**Comment by OrionFive** [comment]
Hmm. All I can tell is that when you try to do a raid, the target location of the raid (the map you're on) is not set to anything (it should be set to the current map). 

I can't find any evidence why this should have something to do with Hospitality or Medieval Times, though. What makes you think the problem comes from these two mods?

**Comment by frokes** [comment]
I've come to that conclusion because that specific error does not trigger
when i spawn a raid without those mods. Although i have not been able to
try it on the same world because of loading errors created by the lack of
the two mods...

**Comment by OrionFive** [comment]
Hmm... have you also tried spawning raids in a new world _with_ those two mods? As a general rule of thumb, everything works just peachy when you start a new world (unless that doesn't even work).

**Comment by frokes** [comment]
Yeah i get the error in a fresh world aswell

**Comment by OrionFive** [comment]
Okay, good. Then you're really onto something. I'll get the Medieval Times mod and see if I can reproduce the issue.

**Comment by OrionFive** [comment]
I think I found the issue. It should be resolved with the next update.

**Comment by frokes** [comment]
Thats great! Thank you for making this awesome mod!

**Comment by OrionFive** [comment]
Apparently what happens is that Hospitality events over time clog up the incident queue. Generally that wouldn't be a problem, but it seems that the storyteller holds back while there are incidents queued. So you might have to play for a year until all the incidents are done. Or just clear the queue in the save game with a text editor. 
-- 
Sent from my phone. Please excuse my brevity.On 30/08/2017, 18:50 frokes <notifications@github.com> wrote:
Thats great! Thank you for making this awesome mod!
