### ISSUE TITLE
HELP PLS Trapped in a one hex base of emotion (MinifiedFurniture)

### ISSUE THREAD

**Issue by champburgundy** [OrionFive/Hospitality#93]
Hello. I am in quite the pickle.
first off here is the F12 link https://gist.github.com/HugsLibRecordKeeper/8892d77caf3012e9c14a98ecf5e09850

I made an large post on the forum that explains what my situation is. https://ludeon.com/forums/index.php?topic=34668.0

Ok so now on to why I am here speaking to you. This started with the leaving the base issue. UnlimitedHugs From Hugslib has identified the MinifiedFurniture3077508 as an issue causing problems and large lag.

What happened with the beds is. I moved all the guest beds to another room but hit the "for prisoners" by mistake and the bed seemed to leave a version of the uninstalled guest bed on the floor even tho the bed was moved. after a reload the "MinifiedFurniture3077508" ( I assume) was no longer on the floor and I thought issue was resolved. It was not
Hugs said to delete the object and they would help more but the MinifiedFurniture is no longer on the floor after another 120 hours playing since that issue.  
Hugs asked me to do this because this MinifiedFurniture3077508 error "is spamming the log, cutting off the useful information" 

I have deconstructed all beds in my colony but the error still shows up.

If you can help with this in any way I would be so grateful.
Thanks for your time and dealing with my issue

**Comment by OrionFive** [comment]
Thanks for the thorough report. I've managed to isolate the issue and prevent future minifying of guest beds. In the next version of Hospitality, this will be prevented.

To fix your savegame, you'll have to manually edit your savegame, find MinifiedFurniture3077508 and remove the object that belongs to it. If you're not comfortable doing this, upload your savegame and I'll do it for you.

**Comment by champburgundy** [comment]
Thank you for the quick response. This is the first game in 25 years of gaming that I am using mods. I also signed up to steam originally for this game. I am as noob as it comes to this. I am trying to look into the issue and see if I can learn how to do this.
I have found this in the save I am using. Please tell me if the section in the middle with the MinifiedFurniture is the correct section to delete. and where to start and end the deletion to make sure I do not mess it up.
If this is too much of an issue I please tell me where I can upload the save so you can adjust it.
Thanks again for the help :~)

</thing>
					<thing Class="Building">
						<def>Wall</def>
						<id>Wall3072931</id>
						<map>0</map>
						<pos>(88, 0, 134)</pos>
						<health>595</health>
						<stuff>BlocksGranite</stuff>
						<faction>Faction_9</faction>
					</thing>
					<thing Class="MinifiedThing">
						<def>MinifiedFurniture</def>
						<id>MinifiedFurniture3077508</id>
						<map>0</map>
						<pos>(95, 0, 125)</pos>
						<health>100</health>
						<stackCount>1</stackCount>
						<innerContainer Class="Verse.ThingOwner`1[Verse.Thing]">
							<maxStacks>1</maxStacks>
							<innerList />
						</innerContainer>
					</thing>
					<thing Class="Building_Bed">
						<def>Bed</def>
						<id>Bed3077753</id>
						<map>0</map>
						<pos>(96, 0, 125)</pos>
						<health>56</health>
						<stuff>WoodLog</stuff>
						<faction>Faction_9</faction>
						<quality>Superior</quality>
						<desiredMinQualityReaced>False</desiredMinQualityReaced>
						<forPrisoners>True</forPrisoners>
						<alreadySetDefaultMed>True</alreadySetDefaultMed>
					</thing>

**Comment by champburgundy** [comment]
Do I remove from 
</thing> <thing Class="MinifiedThing"> 
to 
</innerContainer>
?

**Comment by champburgundy** [comment]
ok. I see I can't post that well I found the section I believe. 
"Thing" at top to "inner container" at bottem needs to be deleted I believe. in the "MinifiedFurniture3077508" section

**Comment by champburgundy** [comment]
Did my best to remove the exact chunk in save file. When opening Dev mode I no longer get an error and when forming a caravan All people and items can be seen now.
Thank You so much for the information. I have been at this game for 200 hours now and am so happy I get to leave my base. who knew that such a Minified thing could have caused such chaos :~)

**Comment by OrionFive** [comment]
Hey, I'm glad you could figure it out on your own!
Btw, above the text box here, there's a symbol with two brackets (next to the quote sign). You can use it to mark something as code:
`<def>MinifiedFurniture</def>`

That way you can post brackets and everything.
