### ISSUE TITLE
Visitors never come...

### ISSUE THREAD

**Issue by Gablbin** [OrionFive/Hospitality#95]
Hi,
At the begging of a new colony, there is always one or two visitors.  They are not really happy but it's write they will come back after some day.
But after, no one, they never come back.
And visitors, not the same never come, my map has now only my colonist so this mod is useless for me.

**Comment by OrionFive** [comment]
Sounds like you should start a new game then... 

Or settle somewhere closer to other factions.

**Comment by Gablbin** [comment]
I have tried it before but nothing to do :(

**Comment by jaaqov** [comment]
Yeah got the same problem since yesteday. Got ~2 visitors at the early start and since then (1 year+ ingametime) no visitor anymore..  
  
Little bit sad :D !

**Comment by OrionFive** [comment]
Do you have any indication to what could be the cause?

**Comment by Gablbin** [comment]
No sorry, I have disabled the mod in mod panel and i start a new game and visitors come again.
After i start again a new game with the mod this time and visitors come, buy and are happy :D

**Comment by OrionFive** [comment]
Well, if you have the problem again, you can also use developer mode and run the visitor incident.

**Comment by jaaqov** [comment]
Hey sorry for the late answer - i was resetting the trade ships via dev mode and pretty much instantly I got visitors again - dunno if there is a coherence.

**Comment by OrionFive** [comment]
How did you reset the trade ships? I'm curious how it could be related...

**Comment by jaaqov** [comment]
Going into Devmode and using the "Replace all trade ships" button - which will insta spawn 5 random trade ships.  
  
Guess it was just coincidence, but I will keep an eye on it :)

**Comment by OrionFive** [comment]
This problem should be solved in the current version (updated yesterday). It might require a new colony (not a new game), though.
