### ISSUE TITLE
Visitors ignore forbidden doors

### ISSUE THREAD

**Issue by 65001** [OrionFive/Hospitality#96]
Visitors ignore forbidden doors which means that they can put themselves into danger via stepping out into a manhunter pack. Can you forbid visitors from a) moving through forbidden doors or b)extend their stay if a manhunter pack or the like is in the region.

**Comment by OrionFive** [comment]
Actually, I can't. But you can. Make sure their guest area is not on the other side of the door. Then they will only go through when they arrive or leave.

**Comment by 65001** [comment]
The guest area was in the safe zone but the guests stay ended so he left through the front door. To my understanding restricting them to an area or making sure the guest area is safe wouldn't help?

So there is no way to stop them from killing themselves once they decide they want to leave?

**Comment by OrionFive** [comment]
That is correct. So you should either send them away before danger is at your door, or you need to escort them out.

**Comment by 65001** [comment]
Alright thanks.
