### ISSUE TITLE
guests don't have a "number of beds" -thought

### ISSUE THREAD

**Issue by forestfey** [OrionFive/Hospitality#98]
...everything works fine, but no guest arriving at my place seem to have a needs-tab-thought related to the number of beds in my guest-room, so I get an "object reference not set to an instance of an object"error, ticking happily away. I play with different race-mods, and so far all groups of all factions had that problem. 
...I also thought I saved a screenshot from the last time, but apparently that was not the case (I can make a new one in case the bug pops up again, which is quite likely). 
Log can be found here, though: https://gist.github.com/8c4d1818a98c99d9339af4f662b367b3

Thank you

**Comment by OrionFive** [comment]
Yeah I actually need a screenshot of the full error. The log file won't do in this case.

**Comment by forestfey** [comment]
had a peek and guessed so, too. Gladly, I still had a save with active visitors, here's a screenshot, including the guest-room: 
![20170906100859_1](https://user-images.githubusercontent.com/31665512/30101258-e7aac568-92eb-11e7-86e3-3ddb3f179325.jpg)

**Comment by OrionFive** [comment]
I've looked into this, but I can't find anything in that method that could cause that error. Sorry.
