### ISSUE TITLE
Guest taking/stealing items (not food)

### ISSUE THREAD

**Issue by Aiwenyar** [OrionFive/Hospitality#99]
Hi there, I've had an issue when guests will literally steal items- i.e., it will disappear from its shelf/stockpile etc and then I'll find it in one of the guests' inventories.  I assume this isn't standard behaviour for the mod?

**Comment by OrionFive** [comment]
Yeah it is. They pay for it, though. You can create an area for the guests and assign it to them. They won't buy things outside of this zone.

**Comment by Aiwenyar** [comment]
Yeah, sorry, I realised that five minutes after posting it lol. Thanks, anyway :)
